
package br.inf.portalfiscal.nfe.wsdl.recepcaoevento.svan;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b14002
 * Generated source version: 2.2
 * 
 */
@WebService(name = "RecepcaoEventoSoap", targetNamespace = "http://www.portalfiscal.inf.br/nfe/wsdl/RecepcaoEvento")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface RecepcaoEventoSoap {


    /**
     * Serviço destinado à recepção de mensagem de Evento da NF-e.
     * 
     * @param nfeCabecMsg
     * @param nfeDadosMsg
     * @return
     *     returns br.inf.portalfiscal.nfe.wsdl.recepcaoevento.NfeRecepcaoEventoResult
     */
    @WebMethod(action = "http://www.portalfiscal.inf.br/nfe/wsdl/RecepcaoEvento/nfeRecepcaoEvento")
    @WebResult(name = "nfeRecepcaoEventoResult", targetNamespace = "http://www.portalfiscal.inf.br/nfe/wsdl/RecepcaoEvento", partName = "nfeRecepcaoEventoResult")
    public NfeRecepcaoEventoResult nfeRecepcaoEvento(
        @WebParam(name = "nfeDadosMsg", targetNamespace = "http://www.portalfiscal.inf.br/nfe/wsdl/RecepcaoEvento", partName = "nfeDadosMsg")
        NfeDadosMsg nfeDadosMsg,
        @WebParam(name = "nfeCabecMsg", targetNamespace = "http://www.portalfiscal.inf.br/nfe/wsdl/RecepcaoEvento", header = true, partName = "nfeCabecMsg")
        NfeCabecMsg nfeCabecMsg);

}
