
package br.inf.portalfiscal.nfe.wsdl.nfestatusservico;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b14002
 * Generated source version: 2.2
 *
 */
@WebService(name = "NfeStatusServicoSoap", targetNamespace = "http://www.portalfiscal.inf.br/nfe/wsdl/NfeStatusServico")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface NfeStatusServicoSoap {


    /**
     * Serviço destinado à consulta do status do serviço da NF-e.
     *
     * @param nfeDadosMsg
     * @return
     *     returns br.inf.portalfiscal.nfe.wsdl.nfestatusservico.NfeStatusServicoNFResult
     */
    @WebMethod(action = "http://www.portalfiscal.inf.br/nfe/wsdl/NfeStatusServico/nfeStatusServicoNF")
    @WebResult(name = "nfeStatusServicoNFResult", targetNamespace = "http://www.portalfiscal.inf.br/nfe/wsdl/NfeStatusServico", partName = "nfeStatusServicoNFResult")
    public NfeStatusServicoNFResult nfeStatusServicoNF(
        @WebParam(name = "nfeDadosMsg", targetNamespace = "http://www.portalfiscal.inf.br/nfe/wsdl/NfeStatusServico", partName = "nfeDadosMsg")
        NfeDadosMsg nfeDadosMsg,
	    @WebParam(name = "nfeCabecMsg", targetNamespace = "http://www.portalfiscal.inf.br/nfe/wsdl/NfeStatusServico", header = true, partName = "nfeCabecMsg")
	    NfeCabecMsg nfeCabecMsg);
}
