
package br.inf.portalfiscal.nfe.wsdl.nfestatusservico;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b14002
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "NfeStatusServico", targetNamespace = "http://www.portalfiscal.inf.br/nfe/wsdl/NfeStatusServico", wsdlLocation = "https://nfe.sefaz.ba.gov.br/webservices/NfeStatusServico/NfeStatusServico.asmx?wsdl")
public class NfeStatusServico
    extends Service
{

    private final static URL NFESTATUSSERVICO_WSDL_LOCATION;
    private final static WebServiceException NFESTATUSSERVICO_EXCEPTION;
    private final static QName NFESTATUSSERVICO_QNAME = new QName("http://www.portalfiscal.inf.br/nfe/wsdl/NfeStatusServico", "NfeStatusServico");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("https://nfe.sefaz.ba.gov.br/webservices/NfeStatusServico/NfeStatusServico.asmx?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        NFESTATUSSERVICO_WSDL_LOCATION = url;
        NFESTATUSSERVICO_EXCEPTION = e;
    }

    public NfeStatusServico() {
        super(__getWsdlLocation(), NFESTATUSSERVICO_QNAME);
    }

    public NfeStatusServico(WebServiceFeature... features) {
        super(__getWsdlLocation(), NFESTATUSSERVICO_QNAME, features);
    }

    public NfeStatusServico(URL wsdlLocation) {
        super(wsdlLocation, NFESTATUSSERVICO_QNAME);
    }

    public NfeStatusServico(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, NFESTATUSSERVICO_QNAME, features);
    }

    public NfeStatusServico(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public NfeStatusServico(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns NfeStatusServicoSoap
     */
    @WebEndpoint(name = "NfeStatusServicoSoap")
    public NfeStatusServicoSoap getNfeStatusServicoSoap() {
        return super.getPort(new QName("http://www.portalfiscal.inf.br/nfe/wsdl/NfeStatusServico", "NfeStatusServicoSoap"), NfeStatusServicoSoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns NfeStatusServicoSoap
     */
    @WebEndpoint(name = "NfeStatusServicoSoap")
    public NfeStatusServicoSoap getNfeStatusServicoSoap(WebServiceFeature... features) {
        return super.getPort(new QName("http://www.portalfiscal.inf.br/nfe/wsdl/NfeStatusServico", "NfeStatusServicoSoap"), NfeStatusServicoSoap.class, features);
    }

    /**
     * 
     * @return
     *     returns NfeStatusServicoSoap
     */
    @WebEndpoint(name = "NfeStatusServicoSoap12")
    public NfeStatusServicoSoap getNfeStatusServicoSoap12() {
        return super.getPort(new QName("http://www.portalfiscal.inf.br/nfe/wsdl/NfeStatusServico", "NfeStatusServicoSoap12"), NfeStatusServicoSoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns NfeStatusServicoSoap
     */
    @WebEndpoint(name = "NfeStatusServicoSoap12")
    public NfeStatusServicoSoap getNfeStatusServicoSoap12(WebServiceFeature... features) {
        return super.getPort(new QName("http://www.portalfiscal.inf.br/nfe/wsdl/NfeStatusServico", "NfeStatusServicoSoap12"), NfeStatusServicoSoap.class, features);
    }

    private static URL __getWsdlLocation() {
        if (NFESTATUSSERVICO_EXCEPTION!= null) {
            throw NFESTATUSSERVICO_EXCEPTION;
        }
        return NFESTATUSSERVICO_WSDL_LOCATION;
    }

}
