
package br.inf.portalfiscal.nfe.wsdl.recepcaoevento;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b14002
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "RecepcaoEvento", targetNamespace = "http://www.portalfiscal.inf.br/nfe/wsdl/RecepcaoEvento", wsdlLocation = "https://www.sefazvirtual.fazenda.gov.br/RecepcaoEvento/RecepcaoEvento.asmx?WSDL")
public class RecepcaoEvento
    extends Service
{

    private final static URL RECEPCAOEVENTO_WSDL_LOCATION;
    private final static WebServiceException RECEPCAOEVENTO_EXCEPTION;
    private final static QName RECEPCAOEVENTO_QNAME = new QName("http://www.portalfiscal.inf.br/nfe/wsdl/RecepcaoEvento", "RecepcaoEvento");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("https://www.sefazvirtual.fazenda.gov.br/RecepcaoEvento/RecepcaoEvento.asmx?WSDL");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        RECEPCAOEVENTO_WSDL_LOCATION = url;
        RECEPCAOEVENTO_EXCEPTION = e;
    }

    public RecepcaoEvento() {
        super(__getWsdlLocation(), RECEPCAOEVENTO_QNAME);
    }

    public RecepcaoEvento(WebServiceFeature... features) {
        super(__getWsdlLocation(), RECEPCAOEVENTO_QNAME, features);
    }

    public RecepcaoEvento(URL wsdlLocation) {
        super(wsdlLocation, RECEPCAOEVENTO_QNAME);
    }

    public RecepcaoEvento(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, RECEPCAOEVENTO_QNAME, features);
    }

    public RecepcaoEvento(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public RecepcaoEvento(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns RecepcaoEventoSoap
     */
    @WebEndpoint(name = "RecepcaoEventoSoap")
    public RecepcaoEventoSoap getRecepcaoEventoSoap() {
        return super.getPort(new QName("http://www.portalfiscal.inf.br/nfe/wsdl/RecepcaoEvento", "RecepcaoEventoSoap"), RecepcaoEventoSoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns RecepcaoEventoSoap
     */
    @WebEndpoint(name = "RecepcaoEventoSoap")
    public RecepcaoEventoSoap getRecepcaoEventoSoap(WebServiceFeature... features) {
        return super.getPort(new QName("http://www.portalfiscal.inf.br/nfe/wsdl/RecepcaoEvento", "RecepcaoEventoSoap"), RecepcaoEventoSoap.class, features);
    }

    /**
     * 
     * @return
     *     returns RecepcaoEventoSoap
     */
    @WebEndpoint(name = "RecepcaoEventoSoap12")
    public RecepcaoEventoSoap getRecepcaoEventoSoap12() {
        return super.getPort(new QName("http://www.portalfiscal.inf.br/nfe/wsdl/RecepcaoEvento", "RecepcaoEventoSoap12"), RecepcaoEventoSoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns RecepcaoEventoSoap
     */
    @WebEndpoint(name = "RecepcaoEventoSoap12")
    public RecepcaoEventoSoap getRecepcaoEventoSoap12(WebServiceFeature... features) {
        return super.getPort(new QName("http://www.portalfiscal.inf.br/nfe/wsdl/RecepcaoEvento", "RecepcaoEventoSoap12"), RecepcaoEventoSoap.class, features);
    }

    private static URL __getWsdlLocation() {
        if (RECEPCAOEVENTO_EXCEPTION!= null) {
            throw RECEPCAOEVENTO_EXCEPTION;
        }
        return RECEPCAOEVENTO_WSDL_LOCATION;
    }

}
