
package br.inf.portalfiscal.nfe.wsdl.nfedownloadnf;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b14002
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "NfeDownloadNF", targetNamespace = "http://www.portalfiscal.inf.br/nfe/wsdl/NfeDownloadNF", wsdlLocation = "https://www.sefazvirtual.fazenda.gov.br/NfeDownloadNF/NfeDownloadNF.asmx?WSDL")
public class NfeDownloadNF
    extends Service
{

    private final static URL NFEDOWNLOADNF_WSDL_LOCATION;
    private final static WebServiceException NFEDOWNLOADNF_EXCEPTION;
    private final static QName NFEDOWNLOADNF_QNAME = new QName("http://www.portalfiscal.inf.br/nfe/wsdl/NfeDownloadNF", "NfeDownloadNF");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("https://www.sefazvirtual.fazenda.gov.br/NfeDownloadNF/NfeDownloadNF.asmx?WSDL");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        NFEDOWNLOADNF_WSDL_LOCATION = url;
        NFEDOWNLOADNF_EXCEPTION = e;
    }

    public NfeDownloadNF() {
        super(__getWsdlLocation(), NFEDOWNLOADNF_QNAME);
    }

    public NfeDownloadNF(WebServiceFeature... features) {
        super(__getWsdlLocation(), NFEDOWNLOADNF_QNAME, features);
    }

    public NfeDownloadNF(URL wsdlLocation) {
        super(wsdlLocation, NFEDOWNLOADNF_QNAME);
    }

    public NfeDownloadNF(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, NFEDOWNLOADNF_QNAME, features);
    }

    public NfeDownloadNF(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public NfeDownloadNF(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns NfeDownloadNFSoap
     */
    @WebEndpoint(name = "NfeDownloadNFSoap")
    public NfeDownloadNFSoap getNfeDownloadNFSoap() {
        return super.getPort(new QName("http://www.portalfiscal.inf.br/nfe/wsdl/NfeDownloadNF", "NfeDownloadNFSoap"), NfeDownloadNFSoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns NfeDownloadNFSoap
     */
    @WebEndpoint(name = "NfeDownloadNFSoap")
    public NfeDownloadNFSoap getNfeDownloadNFSoap(WebServiceFeature... features) {
        return super.getPort(new QName("http://www.portalfiscal.inf.br/nfe/wsdl/NfeDownloadNF", "NfeDownloadNFSoap"), NfeDownloadNFSoap.class, features);
    }

    /**
     * 
     * @return
     *     returns NfeDownloadNFSoap
     */
    @WebEndpoint(name = "NfeDownloadNFSoap12")
    public NfeDownloadNFSoap getNfeDownloadNFSoap12() {
        return super.getPort(new QName("http://www.portalfiscal.inf.br/nfe/wsdl/NfeDownloadNF", "NfeDownloadNFSoap12"), NfeDownloadNFSoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns NfeDownloadNFSoap
     */
    @WebEndpoint(name = "NfeDownloadNFSoap12")
    public NfeDownloadNFSoap getNfeDownloadNFSoap12(WebServiceFeature... features) {
        return super.getPort(new QName("http://www.portalfiscal.inf.br/nfe/wsdl/NfeDownloadNF", "NfeDownloadNFSoap12"), NfeDownloadNFSoap.class, features);
    }

    private static URL __getWsdlLocation() {
        if (NFEDOWNLOADNF_EXCEPTION!= null) {
            throw NFEDOWNLOADNF_EXCEPTION;
        }
        return NFEDOWNLOADNF_WSDL_LOCATION;
    }

}
