
package br.inf.portalfiscal.mdfe.wsdl.mdferecepcaoevento;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Holder;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b14002
 * Generated source version: 2.2
 * 
 */
@WebService(name = "MDFeRecepcaoEventoSoap12", targetNamespace = "http://www.portalfiscal.inf.br/mdfe/wsdl/MDFeRecepcaoEvento")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class, br.inf.portalfiscal.mdfe.ObjectFactory.class
})
public interface MDFeRecepcaoEventoSoap12 {


    /**
     * 
     * @param mdfeDadosMsg
     * @param mdfeCabecMsg
     * @return
     *     returns br.inf.portalfiscal.mdfe.wsdl.mdferecepcaoevento.MdfeRecepcaoEventoResult
     */
    @WebMethod(action = "http://www.portalfiscal.inf.br/mdfe/wsdl/MDFeRecepcaoEvento/mdfeRecepcaoEvento")
    @WebResult(name = "mdfeRecepcaoEventoResult", targetNamespace = "http://www.portalfiscal.inf.br/mdfe/wsdl/MDFeRecepcaoEvento", partName = "mdfeRecepcaoEventoResult")
    public MdfeRecepcaoEventoResult mdfeRecepcaoEvento(
        @WebParam(name = "mdfeDadosMsg", targetNamespace = "http://www.portalfiscal.inf.br/mdfe/wsdl/MDFeRecepcaoEvento", partName = "mdfeDadosMsg")
        MdfeDadosMsg mdfeDadosMsg,
        @WebParam(name = "mdfeCabecMsg", targetNamespace = "http://www.portalfiscal.inf.br/mdfe/wsdl/MDFeRecepcaoEvento", header = true, mode = WebParam.Mode.INOUT, partName = "mdfeCabecMsg")
        Holder<MdfeCabecMsg> mdfeCabecMsg);

}
