
package br.inf.portalfiscal.mdfe.wsdl.mdferecepcaoevento;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b14002
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "MDFeRecepcaoEvento", targetNamespace = "http://www.portalfiscal.inf.br/mdfe/wsdl/MDFeRecepcaoEvento", wsdlLocation = "https://mdfe.svrs.rs.gov.br/ws/MDFeRecepcaoEvento/MDFeRecepcaoEvento.asmx?WSDL")
public class MDFeRecepcaoEvento
    extends Service
{

    private final static URL MDFERECEPCAOEVENTO_WSDL_LOCATION;
    private final static WebServiceException MDFERECEPCAOEVENTO_EXCEPTION;
    private final static QName MDFERECEPCAOEVENTO_QNAME = new QName("http://www.portalfiscal.inf.br/mdfe/wsdl/MDFeRecepcaoEvento", "MDFeRecepcaoEvento");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("https://mdfe.svrs.rs.gov.br/ws/MDFeRecepcaoEvento/MDFeRecepcaoEvento.asmx?WSDL");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        MDFERECEPCAOEVENTO_WSDL_LOCATION = url;
        MDFERECEPCAOEVENTO_EXCEPTION = e;
    }

    public MDFeRecepcaoEvento() {
        super(__getWsdlLocation(), MDFERECEPCAOEVENTO_QNAME);
    }

    public MDFeRecepcaoEvento(WebServiceFeature... features) {
        super(__getWsdlLocation(), MDFERECEPCAOEVENTO_QNAME, features);
    }

    public MDFeRecepcaoEvento(URL wsdlLocation) {
        super(wsdlLocation, MDFERECEPCAOEVENTO_QNAME);
    }

    public MDFeRecepcaoEvento(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, MDFERECEPCAOEVENTO_QNAME, features);
    }

    public MDFeRecepcaoEvento(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public MDFeRecepcaoEvento(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns MDFeRecepcaoEventoSoap12
     */
    @WebEndpoint(name = "MDFeRecepcaoEventoSoap12")
    public MDFeRecepcaoEventoSoap12 getMDFeRecepcaoEventoSoap12() {
        return super.getPort(new QName("http://www.portalfiscal.inf.br/mdfe/wsdl/MDFeRecepcaoEvento", "MDFeRecepcaoEventoSoap12"), MDFeRecepcaoEventoSoap12.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns MDFeRecepcaoEventoSoap12
     */
    @WebEndpoint(name = "MDFeRecepcaoEventoSoap12")
    public MDFeRecepcaoEventoSoap12 getMDFeRecepcaoEventoSoap12(WebServiceFeature... features) {
        return super.getPort(new QName("http://www.portalfiscal.inf.br/mdfe/wsdl/MDFeRecepcaoEvento", "MDFeRecepcaoEventoSoap12"), MDFeRecepcaoEventoSoap12.class, features);
    }

    private static URL __getWsdlLocation() {
        if (MDFERECEPCAOEVENTO_EXCEPTION!= null) {
            throw MDFERECEPCAOEVENTO_EXCEPTION;
        }
        return MDFERECEPCAOEVENTO_WSDL_LOCATION;
    }

}
