
package br.inf.portalfiscal.nfe.wsdl.nfedistribuicaodfe;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b14002
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "NFeDistribuicaoDFe", targetNamespace = "http://www.portalfiscal.inf.br/nfe/wsdl/NFeDistribuicaoDFe", wsdlLocation = "https://www1.nfe.fazenda.gov.br/NFeDistribuicaoDFe/NFeDistribuicaoDFe.asmx?WSDL")
public class NFeDistribuicaoDFe
    extends Service
{

    private final static URL NFEDISTRIBUICAODFE_WSDL_LOCATION;
    private final static WebServiceException NFEDISTRIBUICAODFE_EXCEPTION;
    private final static QName NFEDISTRIBUICAODFE_QNAME = new QName("http://www.portalfiscal.inf.br/nfe/wsdl/NFeDistribuicaoDFe", "NFeDistribuicaoDFe");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("https://www1.nfe.fazenda.gov.br/NFeDistribuicaoDFe/NFeDistribuicaoDFe.asmx?WSDL");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        NFEDISTRIBUICAODFE_WSDL_LOCATION = url;
        NFEDISTRIBUICAODFE_EXCEPTION = e;
    }

    public NFeDistribuicaoDFe() {
        super(__getWsdlLocation(), NFEDISTRIBUICAODFE_QNAME);
    }

    public NFeDistribuicaoDFe(WebServiceFeature... features) {
        super(__getWsdlLocation(), NFEDISTRIBUICAODFE_QNAME, features);
    }

    public NFeDistribuicaoDFe(URL wsdlLocation) {
        super(wsdlLocation, NFEDISTRIBUICAODFE_QNAME);
    }

    public NFeDistribuicaoDFe(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, NFEDISTRIBUICAODFE_QNAME, features);
    }

    public NFeDistribuicaoDFe(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public NFeDistribuicaoDFe(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns NFeDistribuicaoDFeSoap
     */
    @WebEndpoint(name = "NFeDistribuicaoDFeSoap")
    public NFeDistribuicaoDFeSoap getNFeDistribuicaoDFeSoap() {
        return super.getPort(new QName("http://www.portalfiscal.inf.br/nfe/wsdl/NFeDistribuicaoDFe", "NFeDistribuicaoDFeSoap"), NFeDistribuicaoDFeSoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns NFeDistribuicaoDFeSoap
     */
    @WebEndpoint(name = "NFeDistribuicaoDFeSoap")
    public NFeDistribuicaoDFeSoap getNFeDistribuicaoDFeSoap(WebServiceFeature... features) {
        return super.getPort(new QName("http://www.portalfiscal.inf.br/nfe/wsdl/NFeDistribuicaoDFe", "NFeDistribuicaoDFeSoap"), NFeDistribuicaoDFeSoap.class, features);
    }

    /**
     * 
     * @return
     *     returns NFeDistribuicaoDFeSoap
     */
    @WebEndpoint(name = "NFeDistribuicaoDFeSoap12")
    public NFeDistribuicaoDFeSoap getNFeDistribuicaoDFeSoap12() {
        return super.getPort(new QName("http://www.portalfiscal.inf.br/nfe/wsdl/NFeDistribuicaoDFe", "NFeDistribuicaoDFeSoap12"), NFeDistribuicaoDFeSoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns NFeDistribuicaoDFeSoap
     */
    @WebEndpoint(name = "NFeDistribuicaoDFeSoap12")
    public NFeDistribuicaoDFeSoap getNFeDistribuicaoDFeSoap12(WebServiceFeature... features) {
        return super.getPort(new QName("http://www.portalfiscal.inf.br/nfe/wsdl/NFeDistribuicaoDFe", "NFeDistribuicaoDFeSoap12"), NFeDistribuicaoDFeSoap.class, features);
    }

    private static URL __getWsdlLocation() {
        if (NFEDISTRIBUICAODFE_EXCEPTION!= null) {
            throw NFEDISTRIBUICAODFE_EXCEPTION;
        }
        return NFEDISTRIBUICAODFE_WSDL_LOCATION;
    }

}
