
package br.inf.portalfiscal.nfe.wsdl.nfeautorizacao.svan;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b14002
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "NfeAutorizacao", targetNamespace = "http://www.portalfiscal.inf.br/nfe/wsdl/NfeAutorizacao", wsdlLocation = "https://www.sefazvirtual.fazenda.gov.br/NfeAutorizacao/NfeAutorizacao.asmx?WSDL")
public class NfeAutorizacao
    extends Service
{

    private final static URL NFEAUTORIZACAO_WSDL_LOCATION;
    private final static WebServiceException NFEAUTORIZACAO_EXCEPTION;
    private final static QName NFEAUTORIZACAO_QNAME = new QName("http://www.portalfiscal.inf.br/nfe/wsdl/NfeAutorizacao", "NfeAutorizacao");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("https://www.sefazvirtual.fazenda.gov.br/NfeAutorizacao/NfeAutorizacao.asmx?WSDL");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        NFEAUTORIZACAO_WSDL_LOCATION = url;
        NFEAUTORIZACAO_EXCEPTION = e;
    }

    public NfeAutorizacao() {
        super(__getWsdlLocation(), NFEAUTORIZACAO_QNAME);
    }

    public NfeAutorizacao(WebServiceFeature... features) {
        super(__getWsdlLocation(), NFEAUTORIZACAO_QNAME, features);
    }

    public NfeAutorizacao(URL wsdlLocation) {
        super(wsdlLocation, NFEAUTORIZACAO_QNAME);
    }

    public NfeAutorizacao(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, NFEAUTORIZACAO_QNAME, features);
    }

    public NfeAutorizacao(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public NfeAutorizacao(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns NfeAutorizacaoSoap
     */
    @WebEndpoint(name = "NfeAutorizacaoSoap")
    public NfeAutorizacaoSoap getNfeAutorizacaoSoap() {
        return super.getPort(new QName("http://www.portalfiscal.inf.br/nfe/wsdl/NfeAutorizacao", "NfeAutorizacaoSoap"), NfeAutorizacaoSoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns NfeAutorizacaoSoap
     */
    @WebEndpoint(name = "NfeAutorizacaoSoap")
    public NfeAutorizacaoSoap getNfeAutorizacaoSoap(WebServiceFeature... features) {
        return super.getPort(new QName("http://www.portalfiscal.inf.br/nfe/wsdl/NfeAutorizacao", "NfeAutorizacaoSoap"), NfeAutorizacaoSoap.class, features);
    }

    /**
     * 
     * @return
     *     returns NfeAutorizacaoSoap
     */
    @WebEndpoint(name = "NfeAutorizacaoSoap12")
    public NfeAutorizacaoSoap getNfeAutorizacaoSoap12() {
        return super.getPort(new QName("http://www.portalfiscal.inf.br/nfe/wsdl/NfeAutorizacao", "NfeAutorizacaoSoap12"), NfeAutorizacaoSoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns NfeAutorizacaoSoap
     */
    @WebEndpoint(name = "NfeAutorizacaoSoap12")
    public NfeAutorizacaoSoap getNfeAutorizacaoSoap12(WebServiceFeature... features) {
        return super.getPort(new QName("http://www.portalfiscal.inf.br/nfe/wsdl/NfeAutorizacao", "NfeAutorizacaoSoap12"), NfeAutorizacaoSoap.class, features);
    }

    private static URL __getWsdlLocation() {
        if (NFEAUTORIZACAO_EXCEPTION!= null) {
            throw NFEAUTORIZACAO_EXCEPTION;
        }
        return NFEAUTORIZACAO_WSDL_LOCATION;
    }

}
