
package br.inf.portalfiscal.nfe.wsdl.nferetautorizacao;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b14002
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "NfeRetAutorizacao", targetNamespace = "http://www.portalfiscal.inf.br/nfe/wsdl/NfeRetAutorizacao", wsdlLocation = "https://www.sefazvirtual.fazenda.gov.br/NfeRetAutorizacao/NfeRetAutorizacao.asmx?WSDL")
public class NfeRetAutorizacao
    extends Service
{

    private final static URL NFERETAUTORIZACAO_WSDL_LOCATION;
    private final static WebServiceException NFERETAUTORIZACAO_EXCEPTION;
    private final static QName NFERETAUTORIZACAO_QNAME = new QName("http://www.portalfiscal.inf.br/nfe/wsdl/NfeRetAutorizacao", "NfeRetAutorizacao");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("https://www.sefazvirtual.fazenda.gov.br/NfeRetAutorizacao/NfeRetAutorizacao.asmx?WSDL");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        NFERETAUTORIZACAO_WSDL_LOCATION = url;
        NFERETAUTORIZACAO_EXCEPTION = e;
    }

    public NfeRetAutorizacao() {
        super(__getWsdlLocation(), NFERETAUTORIZACAO_QNAME);
    }

    public NfeRetAutorizacao(WebServiceFeature... features) {
        super(__getWsdlLocation(), NFERETAUTORIZACAO_QNAME, features);
    }

    public NfeRetAutorizacao(URL wsdlLocation) {
        super(wsdlLocation, NFERETAUTORIZACAO_QNAME);
    }

    public NfeRetAutorizacao(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, NFERETAUTORIZACAO_QNAME, features);
    }

    public NfeRetAutorizacao(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public NfeRetAutorizacao(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns NfeRetAutorizacaoSoap
     */
    @WebEndpoint(name = "NfeRetAutorizacaoSoap")
    public NfeRetAutorizacaoSoap getNfeRetAutorizacaoSoap() {
        return super.getPort(new QName("http://www.portalfiscal.inf.br/nfe/wsdl/NfeRetAutorizacao", "NfeRetAutorizacaoSoap"), NfeRetAutorizacaoSoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns NfeRetAutorizacaoSoap
     */
    @WebEndpoint(name = "NfeRetAutorizacaoSoap")
    public NfeRetAutorizacaoSoap getNfeRetAutorizacaoSoap(WebServiceFeature... features) {
        return super.getPort(new QName("http://www.portalfiscal.inf.br/nfe/wsdl/NfeRetAutorizacao", "NfeRetAutorizacaoSoap"), NfeRetAutorizacaoSoap.class, features);
    }

    /**
     * 
     * @return
     *     returns NfeRetAutorizacaoSoap
     */
    @WebEndpoint(name = "NfeRetAutorizacaoSoap12")
    public NfeRetAutorizacaoSoap getNfeRetAutorizacaoSoap12() {
        return super.getPort(new QName("http://www.portalfiscal.inf.br/nfe/wsdl/NfeRetAutorizacao", "NfeRetAutorizacaoSoap12"), NfeRetAutorizacaoSoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns NfeRetAutorizacaoSoap
     */
    @WebEndpoint(name = "NfeRetAutorizacaoSoap12")
    public NfeRetAutorizacaoSoap getNfeRetAutorizacaoSoap12(WebServiceFeature... features) {
        return super.getPort(new QName("http://www.portalfiscal.inf.br/nfe/wsdl/NfeRetAutorizacao", "NfeRetAutorizacaoSoap12"), NfeRetAutorizacaoSoap.class, features);
    }

    private static URL __getWsdlLocation() {
        if (NFERETAUTORIZACAO_EXCEPTION!= null) {
            throw NFERETAUTORIZACAO_EXCEPTION;
        }
        return NFERETAUTORIZACAO_WSDL_LOCATION;
    }

}
