
package br.inf.portalfiscal.cte.wsdl.cteconsulta.svrs;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b14002
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "CteConsulta", targetNamespace = "http://www.portalfiscal.inf.br/cte/wsdl/CteConsulta", wsdlLocation = "https://cte.svrs.rs.gov.br/ws/cteconsulta/CteConsulta.asmx?WSDL")
public class CteConsulta
    extends Service
{

    private final static URL CTECONSULTA_WSDL_LOCATION;
    private final static WebServiceException CTECONSULTA_EXCEPTION;
    private final static QName CTECONSULTA_QNAME = new QName("http://www.portalfiscal.inf.br/cte/wsdl/CteConsulta", "CteConsulta");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("https://cte.svrs.rs.gov.br/ws/cteconsulta/CteConsulta.asmx?WSDL");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        CTECONSULTA_WSDL_LOCATION = url;
        CTECONSULTA_EXCEPTION = e;
    }

    public CteConsulta() {
        super(__getWsdlLocation(), CTECONSULTA_QNAME);
    }

    public CteConsulta(WebServiceFeature... features) {
        super(__getWsdlLocation(), CTECONSULTA_QNAME, features);
    }

    public CteConsulta(URL wsdlLocation) {
        super(wsdlLocation, CTECONSULTA_QNAME);
    }

    public CteConsulta(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, CTECONSULTA_QNAME, features);
    }

    public CteConsulta(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public CteConsulta(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns CteConsultaSoap12
     */
    @WebEndpoint(name = "CteConsultaSoap12")
    public CteConsultaSoap12 getCteConsultaSoap12() {
        return super.getPort(new QName("http://www.portalfiscal.inf.br/cte/wsdl/CteConsulta", "CteConsultaSoap12"), CteConsultaSoap12.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns CteConsultaSoap12
     */
    @WebEndpoint(name = "CteConsultaSoap12")
    public CteConsultaSoap12 getCteConsultaSoap12(WebServiceFeature... features) {
        return super.getPort(new QName("http://www.portalfiscal.inf.br/cte/wsdl/CteConsulta", "CteConsultaSoap12"), CteConsultaSoap12.class, features);
    }

    private static URL __getWsdlLocation() {
        if (CTECONSULTA_EXCEPTION!= null) {
            throw CTECONSULTA_EXCEPTION;
        }
        return CTECONSULTA_WSDL_LOCATION;
    }

}
