
package br.inf.portalfiscal.cte.wsdl.cteconsulta.svrs;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Holder;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b14002
 * Generated source version: 2.2
 * 
 */
@WebService(name = "CteConsultaSoap12", targetNamespace = "http://www.portalfiscal.inf.br/cte/wsdl/CteConsulta")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface CteConsultaSoap12 {


    /**
     * 
     * @param cteDadosMsg
     * @param cteCabecMsg
     * @return
     *     returns br.inf.portalfiscal.cte.wsdl.cteconsulta.CteConsultaCTResult
     */
    @WebMethod(action = "http://www.portalfiscal.inf.br/cte/wsdl/CteConsulta/cteConsultaCT")
    @WebResult(name = "cteConsultaCTResult", targetNamespace = "http://www.portalfiscal.inf.br/cte/wsdl/CteConsulta", partName = "cteConsultaCTResult")
    public CteConsultaCTResult cteConsultaCT(
        @WebParam(name = "cteDadosMsg", targetNamespace = "http://www.portalfiscal.inf.br/cte/wsdl/CteConsulta", partName = "cteDadosMsg")
        CteDadosMsg cteDadosMsg,
        @WebParam(name = "cteCabecMsg", targetNamespace = "http://www.portalfiscal.inf.br/cte/wsdl/CteConsulta", header = true, mode = WebParam.Mode.INOUT, partName = "cteCabecMsg")
        Holder<CteCabecMsg> cteCabecMsg);

}
