
package br.inf.portalfiscal.mdfe.wsdl.mdferecepcao;

import java.net.MalformedURLException;
import java.net.URL;
import javax.jws.HandlerChain;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b14002
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "MDFeRecepcao", targetNamespace = "http://www.portalfiscal.inf.br/mdfe/wsdl/MDFeRecepcao", wsdlLocation = "https://mdfe.svrs.rs.gov.br/ws/MDFerecepcao/MDFeRecepcao.asmx?WSDL")
@HandlerChain(file="handler-mdferecepcao.xml")
public class MDFeRecepcao
    extends Service
{

    private final static URL MDFERECEPCAO_WSDL_LOCATION;
    private final static WebServiceException MDFERECEPCAO_EXCEPTION;
    private final static QName MDFERECEPCAO_QNAME = new QName("http://www.portalfiscal.inf.br/mdfe/wsdl/MDFeRecepcao", "MDFeRecepcao");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("https://mdfe.svrs.rs.gov.br/ws/MDFerecepcao/MDFeRecepcao.asmx?WSDL");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        MDFERECEPCAO_WSDL_LOCATION = url;
        MDFERECEPCAO_EXCEPTION = e;
    }

    public MDFeRecepcao() {
        super(__getWsdlLocation(), MDFERECEPCAO_QNAME);
    }

    public MDFeRecepcao(WebServiceFeature... features) {
        super(__getWsdlLocation(), MDFERECEPCAO_QNAME, features);
    }

    public MDFeRecepcao(URL wsdlLocation) {
        super(wsdlLocation, MDFERECEPCAO_QNAME);
    }

    public MDFeRecepcao(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, MDFERECEPCAO_QNAME, features);
    }

    public MDFeRecepcao(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public MDFeRecepcao(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns MDFeRecepcaoSoap12
     */
    @WebEndpoint(name = "MDFeRecepcaoSoap12")
    public MDFeRecepcaoSoap12 getMDFeRecepcaoSoap12() {
        return super.getPort(new QName("http://www.portalfiscal.inf.br/mdfe/wsdl/MDFeRecepcao", "MDFeRecepcaoSoap12"), MDFeRecepcaoSoap12.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns MDFeRecepcaoSoap12
     */
    @WebEndpoint(name = "MDFeRecepcaoSoap12")
    public MDFeRecepcaoSoap12 getMDFeRecepcaoSoap12(WebServiceFeature... features) {
        return super.getPort(new QName("http://www.portalfiscal.inf.br/mdfe/wsdl/MDFeRecepcao", "MDFeRecepcaoSoap12"), MDFeRecepcaoSoap12.class, features);
    }

    private static URL __getWsdlLocation() {
        if (MDFERECEPCAO_EXCEPTION!= null) {
            throw MDFERECEPCAO_EXCEPTION;
        }
        return MDFERECEPCAO_WSDL_LOCATION;
    }

}
