
package br.inf.portalfiscal.nfe.wsdl.nfestatusservico2;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b14002
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "NfeStatusServico2", targetNamespace = "http://www.portalfiscal.inf.br/nfe/wsdl/NfeStatusServico2", wsdlLocation = "https://www.sefazvirtual.fazenda.gov.br/NfeStatusServico2/NfeStatusServico2.asmx?WSDL")
public class NfeStatusServico2
    extends Service
{

    private final static URL NFESTATUSSERVICO2_WSDL_LOCATION;
    private final static WebServiceException NFESTATUSSERVICO2_EXCEPTION;
    private final static QName NFESTATUSSERVICO2_QNAME = new QName("http://www.portalfiscal.inf.br/nfe/wsdl/NfeStatusServico2", "NfeStatusServico2");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("https://www.sefazvirtual.fazenda.gov.br/NfeStatusServico2/NfeStatusServico2.asmx?WSDL");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        NFESTATUSSERVICO2_WSDL_LOCATION = url;
        NFESTATUSSERVICO2_EXCEPTION = e;
    }

    public NfeStatusServico2() {
        super(__getWsdlLocation(), NFESTATUSSERVICO2_QNAME);
    }

    public NfeStatusServico2(WebServiceFeature... features) {
        super(__getWsdlLocation(), NFESTATUSSERVICO2_QNAME, features);
    }

    public NfeStatusServico2(URL wsdlLocation) {
        super(wsdlLocation, NFESTATUSSERVICO2_QNAME);
    }

    public NfeStatusServico2(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, NFESTATUSSERVICO2_QNAME, features);
    }

    public NfeStatusServico2(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public NfeStatusServico2(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns NfeStatusServico2Soap
     */
    @WebEndpoint(name = "NfeStatusServico2Soap")
    public NfeStatusServico2Soap getNfeStatusServico2Soap() {
        return super.getPort(new QName("http://www.portalfiscal.inf.br/nfe/wsdl/NfeStatusServico2", "NfeStatusServico2Soap"), NfeStatusServico2Soap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns NfeStatusServico2Soap
     */
    @WebEndpoint(name = "NfeStatusServico2Soap")
    public NfeStatusServico2Soap getNfeStatusServico2Soap(WebServiceFeature... features) {
        return super.getPort(new QName("http://www.portalfiscal.inf.br/nfe/wsdl/NfeStatusServico2", "NfeStatusServico2Soap"), NfeStatusServico2Soap.class, features);
    }

    /**
     * 
     * @return
     *     returns NfeStatusServico2Soap
     */
    @WebEndpoint(name = "NfeStatusServico2Soap12")
    public NfeStatusServico2Soap getNfeStatusServico2Soap12() {
        return super.getPort(new QName("http://www.portalfiscal.inf.br/nfe/wsdl/NfeStatusServico2", "NfeStatusServico2Soap12"), NfeStatusServico2Soap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns NfeStatusServico2Soap
     */
    @WebEndpoint(name = "NfeStatusServico2Soap12")
    public NfeStatusServico2Soap getNfeStatusServico2Soap12(WebServiceFeature... features) {
        return super.getPort(new QName("http://www.portalfiscal.inf.br/nfe/wsdl/NfeStatusServico2", "NfeStatusServico2Soap12"), NfeStatusServico2Soap.class, features);
    }

    private static URL __getWsdlLocation() {
        if (NFESTATUSSERVICO2_EXCEPTION!= null) {
            throw NFESTATUSSERVICO2_EXCEPTION;
        }
        return NFESTATUSSERVICO2_WSDL_LOCATION;
    }

}
