
package br.inf.portalfiscal.nfe.wsdl.nfeconsulta2;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b14002
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "NfeConsulta2", targetNamespace = "http://www.portalfiscal.inf.br/nfe/wsdl/NfeConsulta2", wsdlLocation = "https://www.sefazvirtual.fazenda.gov.br/NfeConsulta2/NfeConsulta2.asmx?WSDL")
public class NfeConsulta2
    extends Service
{

    private final static URL NFECONSULTA2_WSDL_LOCATION;
    private final static WebServiceException NFECONSULTA2_EXCEPTION;
    private final static QName NFECONSULTA2_QNAME = new QName("http://www.portalfiscal.inf.br/nfe/wsdl/NfeConsulta2", "NfeConsulta2");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("https://www.sefazvirtual.fazenda.gov.br/NfeConsulta2/NfeConsulta2.asmx?WSDL");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        NFECONSULTA2_WSDL_LOCATION = url;
        NFECONSULTA2_EXCEPTION = e;
    }

    public NfeConsulta2() {
        super(__getWsdlLocation(), NFECONSULTA2_QNAME);
    }

    public NfeConsulta2(WebServiceFeature... features) {
        super(__getWsdlLocation(), NFECONSULTA2_QNAME, features);
    }

    public NfeConsulta2(URL wsdlLocation) {
        super(wsdlLocation, NFECONSULTA2_QNAME);
    }

    public NfeConsulta2(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, NFECONSULTA2_QNAME, features);
    }

    public NfeConsulta2(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public NfeConsulta2(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns NfeConsulta2Soap
     */
    @WebEndpoint(name = "NfeConsulta2Soap")
    public NfeConsulta2Soap getNfeConsulta2Soap() {
        return super.getPort(new QName("http://www.portalfiscal.inf.br/nfe/wsdl/NfeConsulta2", "NfeConsulta2Soap"), NfeConsulta2Soap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns NfeConsulta2Soap
     */
    @WebEndpoint(name = "NfeConsulta2Soap")
    public NfeConsulta2Soap getNfeConsulta2Soap(WebServiceFeature... features) {
        return super.getPort(new QName("http://www.portalfiscal.inf.br/nfe/wsdl/NfeConsulta2", "NfeConsulta2Soap"), NfeConsulta2Soap.class, features);
    }

    /**
     * 
     * @return
     *     returns NfeConsulta2Soap
     */
    @WebEndpoint(name = "NfeConsulta2Soap12")
    public NfeConsulta2Soap getNfeConsulta2Soap12() {
        return super.getPort(new QName("http://www.portalfiscal.inf.br/nfe/wsdl/NfeConsulta2", "NfeConsulta2Soap12"), NfeConsulta2Soap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns NfeConsulta2Soap
     */
    @WebEndpoint(name = "NfeConsulta2Soap12")
    public NfeConsulta2Soap getNfeConsulta2Soap12(WebServiceFeature... features) {
        return super.getPort(new QName("http://www.portalfiscal.inf.br/nfe/wsdl/NfeConsulta2", "NfeConsulta2Soap12"), NfeConsulta2Soap.class, features);
    }

    private static URL __getWsdlLocation() {
        if (NFECONSULTA2_EXCEPTION!= null) {
            throw NFECONSULTA2_EXCEPTION;
        }
        return NFECONSULTA2_WSDL_LOCATION;
    }

}
