
package br.inf.portalfiscal.nfe.wsdl.nfestatusservico3;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b14002
 * Generated source version: 2.2
 *
 */
@WebService(name = "NfeStatusServicoSoap12", targetNamespace = "http://www.portalfiscal.inf.br/nfe/wsdl/NfeStatusServico3")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface NfeStatusServicoSoap12 {


    /**
     *
     * @param nfeDadosMsg
     * @return
     *     returns br.inf.portalfiscal.nfe.wsdl.nfestatusservico3.NfeStatusServicoNFResult
     */
    @WebMethod(action = "http://www.portalfiscal.inf.br/nfe/wsdl/NfeStatusServico3/nfeStatusServicoNF")
    @WebResult(name = "nfeStatusServicoNFResult", targetNamespace = "http://www.portalfiscal.inf.br/nfe/wsdl/NfeStatusServico3", partName = "nfeStatusServicoNFResult")
    public NfeStatusServicoNFResult nfeStatusServicoNF(
        @WebParam(name = "nfeDadosMsg", targetNamespace = "http://www.portalfiscal.inf.br/nfe/wsdl/NfeStatusServico3", partName = "nfeDadosMsg")
        NfeDadosMsg nfeDadosMsg,
	    @WebParam(name = "nfeCabecMsg", targetNamespace = "http://www.portalfiscal.inf.br/nfe/wsdl/NfeStatusServico3", header = true, partName = "nfeCabecMsg")
	    NfeCabecMsg nfeCabecMsg);

}
