
package br.inf.portalfiscal.mdfe.wsdl.mdfestatusservico;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Holder;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b14002
 * Generated source version: 2.2
 * 
 */
@WebService(name = "MDFeStatusServicoSoap12", targetNamespace = "http://www.portalfiscal.inf.br/mdfe/wsdl/MDFeStatusServico")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface MDFeStatusServicoSoap12 {


    /**
     * 
     * @param mdfeDadosMsg
     * @param mdfeCabecMsg
     * @return
     *     returns br.inf.portalfiscal.mdfe.wsdl.mdfestatusservico.MdfeStatusServicoMDFResult
     */
    @WebMethod(action = "http://www.portalfiscal.inf.br/mdfe/wsdl/MDFeStatusServico/mdfeStatusServicoMDF")
    @WebResult(name = "mdfeStatusServicoMDFResult", targetNamespace = "http://www.portalfiscal.inf.br/mdfe/wsdl/MDFeStatusServico", partName = "mdfeStatusServicoMDFResult")
    public MdfeStatusServicoMDFResult mdfeStatusServicoMDF(
        @WebParam(name = "mdfeDadosMsg", targetNamespace = "http://www.portalfiscal.inf.br/mdfe/wsdl/MDFeStatusServico", partName = "mdfeDadosMsg")
        MdfeDadosMsg mdfeDadosMsg,
        @WebParam(name = "mdfeCabecMsg", targetNamespace = "http://www.portalfiscal.inf.br/mdfe/wsdl/MDFeStatusServico", header = true, mode = WebParam.Mode.INOUT, partName = "mdfeCabecMsg")
        Holder<MdfeCabecMsg> mdfeCabecMsg);

}
