
package br.inf.portalfiscal.mdfe.wsdl.mdfestatusservico;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b14002
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "MDFeStatusServico", targetNamespace = "http://www.portalfiscal.inf.br/mdfe/wsdl/MDFeStatusServico", wsdlLocation = "https://mdfe.svrs.rs.gov.br/ws/MDFeStatusServico/MDFeStatusServico.asmx?WSDL")
public class MDFeStatusServico
    extends Service
{

    private final static URL MDFESTATUSSERVICO_WSDL_LOCATION;
    private final static WebServiceException MDFESTATUSSERVICO_EXCEPTION;
    private final static QName MDFESTATUSSERVICO_QNAME = new QName("http://www.portalfiscal.inf.br/mdfe/wsdl/MDFeStatusServico", "MDFeStatusServico");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("https://mdfe.svrs.rs.gov.br/ws/MDFeStatusServico/MDFeStatusServico.asmx?WSDL");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        MDFESTATUSSERVICO_WSDL_LOCATION = url;
        MDFESTATUSSERVICO_EXCEPTION = e;
    }

    public MDFeStatusServico() {
        super(__getWsdlLocation(), MDFESTATUSSERVICO_QNAME);
    }

    public MDFeStatusServico(WebServiceFeature... features) {
        super(__getWsdlLocation(), MDFESTATUSSERVICO_QNAME, features);
    }

    public MDFeStatusServico(URL wsdlLocation) {
        super(wsdlLocation, MDFESTATUSSERVICO_QNAME);
    }

    public MDFeStatusServico(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, MDFESTATUSSERVICO_QNAME, features);
    }

    public MDFeStatusServico(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public MDFeStatusServico(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns MDFeStatusServicoSoap12
     */
    @WebEndpoint(name = "MDFeStatusServicoSoap12")
    public MDFeStatusServicoSoap12 getMDFeStatusServicoSoap12() {
        return super.getPort(new QName("http://www.portalfiscal.inf.br/mdfe/wsdl/MDFeStatusServico", "MDFeStatusServicoSoap12"), MDFeStatusServicoSoap12.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns MDFeStatusServicoSoap12
     */
    @WebEndpoint(name = "MDFeStatusServicoSoap12")
    public MDFeStatusServicoSoap12 getMDFeStatusServicoSoap12(WebServiceFeature... features) {
        return super.getPort(new QName("http://www.portalfiscal.inf.br/mdfe/wsdl/MDFeStatusServico", "MDFeStatusServicoSoap12"), MDFeStatusServicoSoap12.class, features);
    }

    private static URL __getWsdlLocation() {
        if (MDFESTATUSSERVICO_EXCEPTION!= null) {
            throw MDFESTATUSSERVICO_EXCEPTION;
        }
        return MDFESTATUSSERVICO_WSDL_LOCATION;
    }

}
