
package br.inf.portalfiscal.cte.wsdl.ctedistribuicaodfe.an;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b14002
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "CTeDistribuicaoDFe", targetNamespace = "http://www.portalfiscal.inf.br/cte/wsdl/CTeDistribuicaoDFe", wsdlLocation = "https://www1.cte.fazenda.gov.br/CTeDistribuicaoDFe/CTeDistribuicaoDFe.asmx?WSDL")
public class CTeDistribuicaoDFe
    extends Service
{

    private final static URL CTEDISTRIBUICAODFE_WSDL_LOCATION;
    private final static WebServiceException CTEDISTRIBUICAODFE_EXCEPTION;
    private final static QName CTEDISTRIBUICAODFE_QNAME = new QName("http://www.portalfiscal.inf.br/cte/wsdl/CTeDistribuicaoDFe", "CTeDistribuicaoDFe");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("https://www1.cte.fazenda.gov.br/CTeDistribuicaoDFe/CTeDistribuicaoDFe.asmx?WSDL");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        CTEDISTRIBUICAODFE_WSDL_LOCATION = url;
        CTEDISTRIBUICAODFE_EXCEPTION = e;
    }

    public CTeDistribuicaoDFe() {
        super(__getWsdlLocation(), CTEDISTRIBUICAODFE_QNAME);
    }

    public CTeDistribuicaoDFe(WebServiceFeature... features) {
        super(__getWsdlLocation(), CTEDISTRIBUICAODFE_QNAME, features);
    }

    public CTeDistribuicaoDFe(URL wsdlLocation) {
        super(wsdlLocation, CTEDISTRIBUICAODFE_QNAME);
    }

    public CTeDistribuicaoDFe(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, CTEDISTRIBUICAODFE_QNAME, features);
    }

    public CTeDistribuicaoDFe(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public CTeDistribuicaoDFe(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns CTeDistribuicaoDFeSoap
     */
    @WebEndpoint(name = "CTeDistribuicaoDFeSoap")
    public CTeDistribuicaoDFeSoap getCTeDistribuicaoDFeSoap() {
        return super.getPort(new QName("http://www.portalfiscal.inf.br/cte/wsdl/CTeDistribuicaoDFe", "CTeDistribuicaoDFeSoap"), CTeDistribuicaoDFeSoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns CTeDistribuicaoDFeSoap
     */
    @WebEndpoint(name = "CTeDistribuicaoDFeSoap")
    public CTeDistribuicaoDFeSoap getCTeDistribuicaoDFeSoap(WebServiceFeature... features) {
        return super.getPort(new QName("http://www.portalfiscal.inf.br/cte/wsdl/CTeDistribuicaoDFe", "CTeDistribuicaoDFeSoap"), CTeDistribuicaoDFeSoap.class, features);
    }

    /**
     * 
     * @return
     *     returns CTeDistribuicaoDFeSoap
     */
    @WebEndpoint(name = "CTeDistribuicaoDFeSoap12")
    public CTeDistribuicaoDFeSoap getCTeDistribuicaoDFeSoap12() {
        return super.getPort(new QName("http://www.portalfiscal.inf.br/cte/wsdl/CTeDistribuicaoDFe", "CTeDistribuicaoDFeSoap12"), CTeDistribuicaoDFeSoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns CTeDistribuicaoDFeSoap
     */
    @WebEndpoint(name = "CTeDistribuicaoDFeSoap12")
    public CTeDistribuicaoDFeSoap getCTeDistribuicaoDFeSoap12(WebServiceFeature... features) {
        return super.getPort(new QName("http://www.portalfiscal.inf.br/cte/wsdl/CTeDistribuicaoDFe", "CTeDistribuicaoDFeSoap12"), CTeDistribuicaoDFeSoap.class, features);
    }

    private static URL __getWsdlLocation() {
        if (CTEDISTRIBUICAODFE_EXCEPTION!= null) {
            throw CTEDISTRIBUICAODFE_EXCEPTION;
        }
        return CTEDISTRIBUICAODFE_WSDL_LOCATION;
    }

}
