
package br.inf.portalfiscal.nfe.wsdl.nfedownloadnf.svan;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b14002
 * Generated source version: 2.2
 * 
 */
@WebService(name = "NfeDownloadNFSoap", targetNamespace = "http://www.portalfiscal.inf.br/nfe/wsdl/NfeDownloadNF")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface NfeDownloadNFSoap {


    /**
     * Serviço destinado ao atendimento de solicitações de download de Notas Fiscais Eletrônicas por seus destinatários.
     * 
     * @param nfeCabecMsg
     * @param nfeDadosMsg
     * @return
     *     returns br.inf.portalfiscal.nfe.wsdl.nfedownloadnf.NfeDownloadNFResult
     */
    @WebMethod(action = "http://www.portalfiscal.inf.br/nfe/wsdl/NfeDownloadNF/nfeDownloadNF")
    @WebResult(name = "nfeDownloadNFResult", targetNamespace = "http://www.portalfiscal.inf.br/nfe/wsdl/NfeDownloadNF", partName = "nfeDownloadNFResult")
    public NfeDownloadNFResult nfeDownloadNF(
        @WebParam(name = "nfeDadosMsg", targetNamespace = "http://www.portalfiscal.inf.br/nfe/wsdl/NfeDownloadNF", partName = "nfeDadosMsg")
        NfeDadosMsg nfeDadosMsg,
        @WebParam(name = "nfeCabecMsg", targetNamespace = "http://www.portalfiscal.inf.br/nfe/wsdl/NfeDownloadNF", header = true, partName = "nfeCabecMsg")
        NfeCabecMsg nfeCabecMsg);

}
