
package br.inf.portalfiscal.cte.wsdl.ctestatusservico;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b14002
 * Generated source version: 2.2
 *
 */
@WebServiceClient(name = "CteStatusServico", targetNamespace = "http://www.portalfiscal.inf.br/cte/wsdl/CteStatusServico", wsdlLocation = "https://cte.svrs.rs.gov.br/ws/ctestatusservico/CteStatusServico.asmx?WSDL")
public class CteStatusServico
    extends Service
{

    private final static URL CTESTATUSSERVICO_WSDL_LOCATION;
    private final static WebServiceException CTESTATUSSERVICO_EXCEPTION;
    private final static QName CTESTATUSSERVICO_QNAME = new QName("http://www.portalfiscal.inf.br/cte/wsdl/CteStatusServico", "CteStatusServico");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("https://cte.svrs.rs.gov.br/ws/ctestatusservico/CteStatusServico.asmx?WSDL");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        CTESTATUSSERVICO_WSDL_LOCATION = url;
        CTESTATUSSERVICO_EXCEPTION = e;
    }

    public CteStatusServico() {
        super(__getWsdlLocation(), CTESTATUSSERVICO_QNAME);
    }

    public CteStatusServico(WebServiceFeature... features) {
        super(__getWsdlLocation(), CTESTATUSSERVICO_QNAME, features);
    }

    public CteStatusServico(URL wsdlLocation) {
        super(wsdlLocation, CTESTATUSSERVICO_QNAME);
    }

    public CteStatusServico(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, CTESTATUSSERVICO_QNAME, features);
    }

    public CteStatusServico(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public CteStatusServico(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     *
     * @return
     *     returns CteStatusServicoSoap12
     */
    @WebEndpoint(name = "CteStatusServicoSoap12")
    public CteStatusServicoSoap12 getCteStatusServicoSoap12() {
        return super.getPort(new QName("http://www.portalfiscal.inf.br/cte/wsdl/CteStatusServico", "CteStatusServicoSoap12"), CteStatusServicoSoap12.class);
    }

    /**
     *
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns CteStatusServicoSoap12
     */
    @WebEndpoint(name = "CteStatusServicoSoap12")
    public CteStatusServicoSoap12 getCteStatusServicoSoap12(WebServiceFeature... features) {
        return super.getPort(new QName("http://www.portalfiscal.inf.br/cte/wsdl/CteStatusServico", "CteStatusServicoSoap12"), CteStatusServicoSoap12.class, features);
    }

    private static URL __getWsdlLocation() {
        if (CTESTATUSSERVICO_EXCEPTION!= null) {
            throw CTESTATUSSERVICO_EXCEPTION;
        }
        return CTESTATUSSERVICO_WSDL_LOCATION;
    }

}
