
package br.inf.portalfiscal.nfe.wsdl.nfeautorizacao;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b14002
 * Generated source version: 2.2
 * 
 */
@WebService(name = "NfeAutorizacaoSoap", targetNamespace = "http://www.portalfiscal.inf.br/nfe/wsdl/NfeAutorizacao")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface NfeAutorizacaoSoap {


    /**
     * Serviço destinado à recepção de mensagens de lote de NF-e
     * 
     * @param nfeCabecMsg
     * @param nfeDadosMsg
     * @return
     *     returns br.inf.portalfiscal.nfe.wsdl.nfeautorizacao.NfeAutorizacaoLoteResult
     */
    @WebMethod(action = "http://www.portalfiscal.inf.br/nfe/wsdl/NfeAutorizacao/nfeAutorizacaoLote")
    @WebResult(name = "nfeAutorizacaoLoteResult", targetNamespace = "http://www.portalfiscal.inf.br/nfe/wsdl/NfeAutorizacao", partName = "nfeAutorizacaoLoteResult")
    public NfeAutorizacaoLoteResult nfeAutorizacaoLote(
        @WebParam(name = "nfeDadosMsg", targetNamespace = "http://www.portalfiscal.inf.br/nfe/wsdl/NfeAutorizacao", partName = "nfeDadosMsg")
        NfeDadosMsg nfeDadosMsg,
        @WebParam(name = "nfeCabecMsg", targetNamespace = "http://www.portalfiscal.inf.br/nfe/wsdl/NfeAutorizacao", header = true, partName = "nfeCabecMsg")
        NfeCabecMsg nfeCabecMsg);

    /**
     * Serviço destinado à recepção de mensagens de lote de NF-e compactada
     * 
     * @param nfeDadosMsgZip
     * @param nfeCabecMsg
     * @return
     *     returns br.inf.portalfiscal.nfe.wsdl.nfeautorizacao.NfeAutorizacaoLoteZipResult
     */
    @WebMethod(action = "http://www.portalfiscal.inf.br/nfe/wsdl/NfeAutorizacao/nfeAutorizacaoLoteZip")
    @WebResult(name = "nfeAutorizacaoLoteZipResult", targetNamespace = "http://www.portalfiscal.inf.br/nfe/wsdl/NfeAutorizacao", partName = "nfeAutorizacaoLoteZipResult")
    public NfeAutorizacaoLoteZipResult nfeAutorizacaoLoteZip(
        @WebParam(name = "nfeDadosMsgZip", targetNamespace = "http://www.portalfiscal.inf.br/nfe/wsdl/NfeAutorizacao", partName = "nfeDadosMsgZip")
        String nfeDadosMsgZip,
        @WebParam(name = "nfeCabecMsg", targetNamespace = "http://www.portalfiscal.inf.br/nfe/wsdl/NfeAutorizacao", header = true, partName = "nfeCabecMsg")
        NfeCabecMsg nfeCabecMsg);

}
