
package br.inf.portalfiscal.mdfe.wsdl.mdferetrecepcao;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Holder;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b14002
 * Generated source version: 2.2
 * 
 */
@WebService(name = "MDFeRetRecepcaoSoap12", targetNamespace = "http://www.portalfiscal.inf.br/mdfe/wsdl/MDFeRetRecepcao")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface MDFeRetRecepcaoSoap12 {


    /**
     * 
     * @param mdfeDadosMsg
     * @param mdfeCabecMsg
     * @return
     *     returns br.inf.portalfiscal.mdfe.wsdl.mdferetrecepcao.MdfeRetRecepcaoResult
     */
    @WebMethod(action = "http://www.portalfiscal.inf.br/mdfe/wsdl/MDFeRetRecepcao/mdfeRetRecepcao")
    @WebResult(name = "mdfeRetRecepcaoResult", targetNamespace = "http://www.portalfiscal.inf.br/mdfe/wsdl/MDFeRetRecepcao", partName = "mdfeRetRecepcaoResult")
    public MdfeRetRecepcaoResult mdfeRetRecepcao(
        @WebParam(name = "mdfeDadosMsg", targetNamespace = "http://www.portalfiscal.inf.br/mdfe/wsdl/MDFeRetRecepcao", partName = "mdfeDadosMsg")
        MdfeDadosMsg mdfeDadosMsg,
        @WebParam(name = "mdfeCabecMsg", targetNamespace = "http://www.portalfiscal.inf.br/mdfe/wsdl/MDFeRetRecepcao", header = true, mode = WebParam.Mode.INOUT, partName = "mdfeCabecMsg")
        Holder<MdfeCabecMsg> mdfeCabecMsg);

}
