
package br.inf.portalfiscal.cte.wsdl.cterecepcao.svrs;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b14002
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "CteRecepcao", targetNamespace = "http://www.portalfiscal.inf.br/cte/wsdl/CteRecepcao", wsdlLocation = "https://cte.svrs.rs.gov.br/ws/cterecepcao/CteRecepcao.asmx?WSDL")
public class CteRecepcao
    extends Service
{

    private final static URL CTERECEPCAO_WSDL_LOCATION;
    private final static WebServiceException CTERECEPCAO_EXCEPTION;
    private final static QName CTERECEPCAO_QNAME = new QName("http://www.portalfiscal.inf.br/cte/wsdl/CteRecepcao", "CteRecepcao");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("https://cte.svrs.rs.gov.br/ws/cterecepcao/CteRecepcao.asmx?WSDL");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        CTERECEPCAO_WSDL_LOCATION = url;
        CTERECEPCAO_EXCEPTION = e;
    }

    public CteRecepcao() {
        super(__getWsdlLocation(), CTERECEPCAO_QNAME);
    }

    public CteRecepcao(WebServiceFeature... features) {
        super(__getWsdlLocation(), CTERECEPCAO_QNAME, features);
    }

    public CteRecepcao(URL wsdlLocation) {
        super(wsdlLocation, CTERECEPCAO_QNAME);
    }

    public CteRecepcao(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, CTERECEPCAO_QNAME, features);
    }

    public CteRecepcao(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public CteRecepcao(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns CteRecepcaoSoap12
     */
    @WebEndpoint(name = "CteRecepcaoSoap12")
    public CteRecepcaoSoap12 getCteRecepcaoSoap12() {
        return super.getPort(new QName("http://www.portalfiscal.inf.br/cte/wsdl/CteRecepcao", "CteRecepcaoSoap12"), CteRecepcaoSoap12.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns CteRecepcaoSoap12
     */
    @WebEndpoint(name = "CteRecepcaoSoap12")
    public CteRecepcaoSoap12 getCteRecepcaoSoap12(WebServiceFeature... features) {
        return super.getPort(new QName("http://www.portalfiscal.inf.br/cte/wsdl/CteRecepcao", "CteRecepcaoSoap12"), CteRecepcaoSoap12.class, features);
    }

    private static URL __getWsdlLocation() {
        if (CTERECEPCAO_EXCEPTION!= null) {
            throw CTERECEPCAO_EXCEPTION;
        }
        return CTERECEPCAO_WSDL_LOCATION;
    }

}
