package com.fincatto.documentofiscal;

import org.junit.Assert;
import org.junit.Test;

import java.util.Arrays;

/**
 * Created by Eldevan Nery Junior on 07/05/18.
 * Define os Testes para a classe com.fincatto.documentofiscal.DFPais.java
 *
 */
public class DFPaisTest {

    @Test
    public void deveRepresentarOCodigoCorretamente() {
        Assert.assertEquals("AFEGANISTAO", DFPais.AFEGANISTAO.getDescricao());
        Assert.assertEquals(new Integer(132), DFPais.AFEGANISTAO.getCodigo());
        Assert.assertEquals("ALAND, ILHAS", DFPais.ALAND_ILHAS.getDescricao());
        Assert.assertEquals(new Integer(153), DFPais.ALAND_ILHAS.getCodigo());
        Assert.assertEquals("ALBANIA, REPUBLICA  DA", DFPais.ALBANIA_REPUBLICA_DA.getDescricao());
        Assert.assertEquals(new Integer(175), DFPais.ALBANIA_REPUBLICA_DA.getCodigo());
        Assert.assertEquals("ALEMANHA", DFPais.ALEMANHA.getDescricao());
        Assert.assertEquals(new Integer(230), DFPais.ALEMANHA.getCodigo());
        Assert.assertEquals("BURKINA FASO", DFPais.BURKINA_FASO.getDescricao());
        Assert.assertEquals(new Integer(310), DFPais.BURKINA_FASO.getCodigo());
        Assert.assertEquals("ANDORRA", DFPais.ANDORRA.getDescricao());
        Assert.assertEquals(new Integer(370), DFPais.ANDORRA.getCodigo());
        Assert.assertEquals("ANGOLA", DFPais.ANGOLA.getDescricao());
        Assert.assertEquals(new Integer(400), DFPais.ANGOLA.getCodigo());
        Assert.assertEquals("ANGUILLA", DFPais.ANGUILLA.getDescricao());
        Assert.assertEquals(new Integer(418), DFPais.ANGUILLA.getCodigo());
        Assert.assertEquals("ANTARTICA", DFPais.ANTARTICA.getDescricao());
        Assert.assertEquals(new Integer(420), DFPais.ANTARTICA.getCodigo());
        Assert.assertEquals("ANTIGUA E BARBUDA", DFPais.ANTIGUA_E_BARBUDA.getDescricao());
        Assert.assertEquals(new Integer(434), DFPais.ANTIGUA_E_BARBUDA.getCodigo());
        Assert.assertEquals("ANTILHAS HOLANDESAS", DFPais.ANTILHAS_HOLANDESAS.getDescricao());
        Assert.assertEquals(new Integer(477), DFPais.ANTILHAS_HOLANDESAS.getCodigo());
        Assert.assertEquals("ARABIA SAUDITA", DFPais.ARABIA_SAUDITA.getDescricao());
        Assert.assertEquals(new Integer(531), DFPais.ARABIA_SAUDITA.getCodigo());
        Assert.assertEquals("ARGELIA", DFPais.ARGELIA.getDescricao());
        Assert.assertEquals(new Integer(590), DFPais.ARGELIA.getCodigo());
        Assert.assertEquals("ARGENTINA", DFPais.ARGENTINA.getDescricao());
        Assert.assertEquals(new Integer(639), DFPais.ARGENTINA.getCodigo());
        Assert.assertEquals("ARMENIA, REPUBLICA DA", DFPais.ARMENIA_REPUBLICA_DA.getDescricao());
        Assert.assertEquals(new Integer(647), DFPais.ARMENIA_REPUBLICA_DA.getCodigo());
        Assert.assertEquals("ARUBA", DFPais.ARUBA.getDescricao());
        Assert.assertEquals(new Integer(655), DFPais.ARUBA.getCodigo());
        Assert.assertEquals("AUSTRALIA", DFPais.AUSTRALIA.getDescricao());
        Assert.assertEquals(new Integer(698), DFPais.AUSTRALIA.getCodigo());
        Assert.assertEquals("AUSTRIA", DFPais.AUSTRIA.getDescricao());
        Assert.assertEquals(new Integer(728), DFPais.AUSTRIA.getCodigo());
        Assert.assertEquals("AZERBAIJAO, REPUBLICA DO", DFPais.AZERBAIJAO_REPUBLICA_DO.getDescricao());
        Assert.assertEquals(new Integer(736), DFPais.AZERBAIJAO_REPUBLICA_DO.getCodigo());
        Assert.assertEquals("BAHAMAS, ILHAS", DFPais.BAHAMAS_ILHAS.getDescricao());
        Assert.assertEquals(new Integer(779), DFPais.BAHAMAS_ILHAS.getCodigo());
        Assert.assertEquals("BAHREIN, ILHAS", DFPais.BAHREIN_ILHAS.getDescricao());
        Assert.assertEquals(new Integer(809), DFPais.BAHREIN_ILHAS.getCodigo());
        Assert.assertEquals("BANGLADESH", DFPais.BANGLADESH.getDescricao());
        Assert.assertEquals(new Integer(817), DFPais.BANGLADESH.getCodigo());
        Assert.assertEquals("BARBADOS", DFPais.BARBADOS.getDescricao());
        Assert.assertEquals(new Integer(833), DFPais.BARBADOS.getCodigo());
        Assert.assertEquals("BELARUS, REPUBLICA DA", DFPais.BELARUS_REPUBLICA_DA.getDescricao());
        Assert.assertEquals(new Integer(850), DFPais.BELARUS_REPUBLICA_DA.getCodigo());
        Assert.assertEquals("BELGICA", DFPais.BELGICA.getDescricao());
        Assert.assertEquals(new Integer(876), DFPais.BELGICA.getCodigo());
        Assert.assertEquals("BELIZE", DFPais.BELIZE.getDescricao());
        Assert.assertEquals(new Integer(884), DFPais.BELIZE.getCodigo());
        Assert.assertEquals("BERMUDAS", DFPais.BERMUDAS.getDescricao());
        Assert.assertEquals(new Integer(906), DFPais.BERMUDAS.getCodigo());
        Assert.assertEquals("MIANMAR (BIRMANIA)", DFPais.MIANMAR_BIRMANIA.getDescricao());
        Assert.assertEquals(new Integer(930), DFPais.MIANMAR_BIRMANIA.getCodigo());
        Assert.assertEquals("BOLIVIA, ESTADO PLURINACIONAL DA", DFPais.BOLIVIA_ESTADO_PLURINACIONAL_DA.getDescricao());
        Assert.assertEquals(new Integer(973), DFPais.BOLIVIA_ESTADO_PLURINACIONAL_DA.getCodigo());
        Assert.assertEquals("BOSNIA-HERZEGOVINA (REPUBLICA DA)", DFPais.BOSNIA_HERZEGOVINA_REPUBLICA_DA.getDescricao());
        Assert.assertEquals(new Integer(981), DFPais.BOSNIA_HERZEGOVINA_REPUBLICA_DA.getCodigo());
        Assert.assertEquals("BONAIRE", DFPais.BONAIRE.getDescricao());
        Assert.assertEquals(new Integer(990), DFPais.BONAIRE.getCodigo());
        Assert.assertEquals("BOTSUANA", DFPais.BOTSUANA.getDescricao());
        Assert.assertEquals(new Integer(1015), DFPais.BOTSUANA.getCodigo());
        Assert.assertEquals("BOUVET, ILHA", DFPais.BOUVET_ILHA.getDescricao());
        Assert.assertEquals(new Integer(1023), DFPais.BOUVET_ILHA.getCodigo());
        Assert.assertEquals("BRASIL", DFPais.BRASIL.getDescricao());
        Assert.assertEquals(new Integer(1058), DFPais.BRASIL.getCodigo());
        Assert.assertEquals("BRUNEI", DFPais.BRUNEI.getDescricao());
        Assert.assertEquals(new Integer(1082), DFPais.BRUNEI.getCodigo());
        Assert.assertEquals("BULGARIA, REPUBLICA DA", DFPais.BULGARIA_REPUBLICA_DA.getDescricao());
        Assert.assertEquals(new Integer(1112), DFPais.BULGARIA_REPUBLICA_DA.getCodigo());
        Assert.assertEquals("BURUNDI", DFPais.BURUNDI.getDescricao());
        Assert.assertEquals(new Integer(1155), DFPais.BURUNDI.getCodigo());
        Assert.assertEquals("BUTAO", DFPais.BUTAO.getDescricao());
        Assert.assertEquals(new Integer(1198), DFPais.BUTAO.getCodigo());
        Assert.assertEquals("CABO VERDE, REPUBLICA DE", DFPais.CABO_VERDE_REPUBLICA_DE.getDescricao());
        Assert.assertEquals(new Integer(1279), DFPais.CABO_VERDE_REPUBLICA_DE.getCodigo());
        Assert.assertEquals("CAYMAN, ILHAS", DFPais.CAYMAN_ILHAS.getDescricao());
        Assert.assertEquals(new Integer(1376), DFPais.CAYMAN_ILHAS.getCodigo());
        Assert.assertEquals("CAMBOJA", DFPais.CAMBOJA.getDescricao());
        Assert.assertEquals(new Integer(1414), DFPais.CAMBOJA.getCodigo());
        Assert.assertEquals("CAMAROES", DFPais.CAMAROES.getDescricao());
        Assert.assertEquals(new Integer(1457), DFPais.CAMAROES.getCodigo());
        Assert.assertEquals("CANADA", DFPais.CANADA.getDescricao());
        Assert.assertEquals(new Integer(1490), DFPais.CANADA.getCodigo());
        Assert.assertEquals("CAZAQUISTAO, REPUBLICA DO", DFPais.CAZAQUISTAO_REPUBLICA_DO.getDescricao());
        Assert.assertEquals(new Integer(1538), DFPais.CAZAQUISTAO_REPUBLICA_DO.getCodigo());
        Assert.assertEquals("CATAR", DFPais.CATAR.getDescricao());
        Assert.assertEquals(new Integer(1546), DFPais.CATAR.getCodigo());
        Assert.assertEquals("CHILE", DFPais.CHILE.getDescricao());
        Assert.assertEquals(new Integer(1589), DFPais.CHILE.getCodigo());
        Assert.assertEquals("CHINA, REPUBLICA POPULAR", DFPais.CHINA_REPUBLICA_POPULAR.getDescricao());
        Assert.assertEquals(new Integer(1600), DFPais.CHINA_REPUBLICA_POPULAR.getCodigo());
        Assert.assertEquals("FORMOSA (TAIWAN)", DFPais.FORMOSA_TAIWAN.getDescricao());
        Assert.assertEquals(new Integer(1619), DFPais.FORMOSA_TAIWAN.getCodigo());
        Assert.assertEquals("CHIPRE", DFPais.CHIPRE.getDescricao());
        Assert.assertEquals(new Integer(1635), DFPais.CHIPRE.getCodigo());
        Assert.assertEquals("COCOS(KEELING),ILHAS", DFPais.COCOS_KEELING_ILHAS.getDescricao());
        Assert.assertEquals(new Integer(1651), DFPais.COCOS_KEELING_ILHAS.getCodigo());
        Assert.assertEquals("COLOMBIA", DFPais.COLOMBIA.getDescricao());
        Assert.assertEquals(new Integer(1694), DFPais.COLOMBIA.getCodigo());
        Assert.assertEquals("COMORES, ILHAS", DFPais.COMORES_ILHAS.getDescricao());
        Assert.assertEquals(new Integer(1732), DFPais.COMORES_ILHAS.getCodigo());
        Assert.assertEquals("CONGO", DFPais.CONGO.getDescricao());
        Assert.assertEquals(new Integer(1775), DFPais.CONGO.getCodigo());
        Assert.assertEquals("COOK, ILHAS", DFPais.COOK_ILHAS.getDescricao());
        Assert.assertEquals(new Integer(1830), DFPais.COOK_ILHAS.getCodigo());
        Assert.assertEquals("COREIA (DO NORTE), REP.POP.DEMOCRATICA", DFPais.COREIA_DO_NORTE__REP_POP_DEMOCRATICA.getDescricao());
        Assert.assertEquals(new Integer(1872), DFPais.COREIA_DO_NORTE__REP_POP_DEMOCRATICA.getCodigo());
        Assert.assertEquals("COREIA (DO SUL), REPUBLICA DA", DFPais.COREIA_DO_SUL__REPUBLICA_DA.getDescricao());
        Assert.assertEquals(new Integer(1902), DFPais.COREIA_DO_SUL__REPUBLICA_DA.getCodigo());
        Assert.assertEquals("COSTA DO MARFIM", DFPais.COSTA_DO_MARFIM.getDescricao());
        Assert.assertEquals(new Integer(1937), DFPais.COSTA_DO_MARFIM.getCodigo());
        Assert.assertEquals("CROACIA (REPUBLICA DA)", DFPais.CROACIA_REPUBLICA_DA.getDescricao());
        Assert.assertEquals(new Integer(1953), DFPais.CROACIA_REPUBLICA_DA.getCodigo());
        Assert.assertEquals("COSTA RICA", DFPais.COSTA_RICA.getDescricao());
        Assert.assertEquals(new Integer(1961), DFPais.COSTA_RICA.getCodigo());
        Assert.assertEquals("COVEITE", DFPais.COVEITE.getDescricao());
        Assert.assertEquals(new Integer(1988), DFPais.COVEITE.getCodigo());
        Assert.assertEquals("KUWAIT", DFPais.KUWAIT.getDescricao());
        Assert.assertEquals(new Integer(1988), DFPais.KUWAIT.getCodigo());
        Assert.assertEquals("CUBA", DFPais.CUBA.getDescricao());
        Assert.assertEquals(new Integer(1996), DFPais.CUBA.getCodigo());
        Assert.assertEquals("CURACAO", DFPais.CURACAO.getDescricao());
        Assert.assertEquals(new Integer(2003), DFPais.CURACAO.getCodigo());
        Assert.assertEquals("BENIN", DFPais.BENIN.getDescricao());
        Assert.assertEquals(new Integer(2291), DFPais.BENIN.getCodigo());
        Assert.assertEquals("DINAMARCA", DFPais.DINAMARCA.getDescricao());
        Assert.assertEquals(new Integer(2321), DFPais.DINAMARCA.getCodigo());
        Assert.assertEquals("DOMINICA,ILHA", DFPais.DOMINICA_ILHA.getDescricao());
        Assert.assertEquals(new Integer(2356), DFPais.DOMINICA_ILHA.getCodigo());
        Assert.assertEquals("EQUADOR", DFPais.EQUADOR.getDescricao());
        Assert.assertEquals(new Integer(2399), DFPais.EQUADOR.getCodigo());
        Assert.assertEquals("EGITO", DFPais.EGITO.getDescricao());
        Assert.assertEquals(new Integer(2402), DFPais.EGITO.getCodigo());
        Assert.assertEquals("ERITREIA", DFPais.ERITREIA.getDescricao());
        Assert.assertEquals(new Integer(2437), DFPais.ERITREIA.getCodigo());
        Assert.assertEquals("EMIRADOS ARABES UNIDOS", DFPais.EMIRADOS_ARABES_UNIDOS.getDescricao());
        Assert.assertEquals(new Integer(2445), DFPais.EMIRADOS_ARABES_UNIDOS.getCodigo());
        Assert.assertEquals("ESPANHA", DFPais.ESPANHA.getDescricao());
        Assert.assertEquals(new Integer(2453), DFPais.ESPANHA.getCodigo());
        Assert.assertEquals("ESLOVENIA, REPUBLICA DA", DFPais.ESLOVENIA_REPUBLICA_DA.getDescricao());
        Assert.assertEquals(new Integer(2461), DFPais.ESLOVENIA_REPUBLICA_DA.getCodigo());
        Assert.assertEquals("ESLOVACA, REPUBLICA", DFPais.ESLOVACA_REPUBLICA.getDescricao());
        Assert.assertEquals(new Integer(2470), DFPais.ESLOVACA_REPUBLICA.getCodigo());
        Assert.assertEquals("ESTADOS UNIDOS", DFPais.ESTADOS_UNIDOS.getDescricao());
        Assert.assertEquals(new Integer(2496), DFPais.ESTADOS_UNIDOS.getCodigo());
        Assert.assertEquals("ESTONIA, REPUBLICA DA", DFPais.ESTONIA_REPUBLICA_DA.getDescricao());
        Assert.assertEquals(new Integer(2518), DFPais.ESTONIA_REPUBLICA_DA.getCodigo());
        Assert.assertEquals("ETIOPIA", DFPais.ETIOPIA.getDescricao());
        Assert.assertEquals(new Integer(2534), DFPais.ETIOPIA.getCodigo());
        Assert.assertEquals("FALKLAND (ILHAS MALVINAS)", DFPais.FALKLAND_ILHAS_MALVINAS.getDescricao());
        Assert.assertEquals(new Integer(2550), DFPais.FALKLAND_ILHAS_MALVINAS.getCodigo());
        Assert.assertEquals("FEROE, ILHAS", DFPais.FEROE_ILHAS.getDescricao());
        Assert.assertEquals(new Integer(2593), DFPais.FEROE_ILHAS.getCodigo());
        Assert.assertEquals("FILIPINAS", DFPais.FILIPINAS.getDescricao());
        Assert.assertEquals(new Integer(2674), DFPais.FILIPINAS.getCodigo());
        Assert.assertEquals("FINLANDIA", DFPais.FINLANDIA.getDescricao());
        Assert.assertEquals(new Integer(2712), DFPais.FINLANDIA.getCodigo());
        Assert.assertEquals("FRANCA", DFPais.FRANCA.getDescricao());
        Assert.assertEquals(new Integer(2755), DFPais.FRANCA.getCodigo());
        Assert.assertEquals("GABAO", DFPais.GABAO.getDescricao());
        Assert.assertEquals(new Integer(2810), DFPais.GABAO.getCodigo());
        Assert.assertEquals("GAMBIA", DFPais.GAMBIA.getDescricao());
        Assert.assertEquals(new Integer(2852), DFPais.GAMBIA.getCodigo());
        Assert.assertEquals("GANA", DFPais.GANA.getDescricao());
        Assert.assertEquals(new Integer(2895), DFPais.GANA.getCodigo());
        Assert.assertEquals("GEORGIA, REPUBLICA DA", DFPais.GEORGIA_REPUBLICA_DA.getDescricao());
        Assert.assertEquals(new Integer(2917), DFPais.GEORGIA_REPUBLICA_DA.getCodigo());
        Assert.assertEquals("ILHAS GEORGIA DO SUL E SANDWICH DO SUL", DFPais.ILHAS_GEORGIA_DO_SUL_E_SANDWICH_DO_SUL.getDescricao());
        Assert.assertEquals(new Integer(2925), DFPais.ILHAS_GEORGIA_DO_SUL_E_SANDWICH_DO_SUL.getCodigo());
        Assert.assertEquals("GIBRALTAR", DFPais.GIBRALTAR.getDescricao());
        Assert.assertEquals(new Integer(2933), DFPais.GIBRALTAR.getCodigo());
        Assert.assertEquals("GRANADA", DFPais.GRANADA.getDescricao());
        Assert.assertEquals(new Integer(2976), DFPais.GRANADA.getCodigo());
        Assert.assertEquals("GRECIA", DFPais.GRECIA.getDescricao());
        Assert.assertEquals(new Integer(3018), DFPais.GRECIA.getCodigo());
        Assert.assertEquals("GROENLANDIA", DFPais.GROENLANDIA.getDescricao());
        Assert.assertEquals(new Integer(3050), DFPais.GROENLANDIA.getCodigo());
        Assert.assertEquals("GUADALUPE", DFPais.GUADALUPE.getDescricao());
        Assert.assertEquals(new Integer(3093), DFPais.GUADALUPE.getCodigo());
        Assert.assertEquals("GUAM", DFPais.GUAM.getDescricao());
        Assert.assertEquals(new Integer(3131), DFPais.GUAM.getCodigo());
        Assert.assertEquals("GUATEMALA", DFPais.GUATEMALA.getDescricao());
        Assert.assertEquals(new Integer(3174), DFPais.GUATEMALA.getCodigo());
        Assert.assertEquals("GUERNSEY, ILHA DO CANAL (INCLUI ALDERNEY E SARK)", DFPais.GUERNSEY_ILHA_DO_CANAL_INCLUI_ALDERNEY_E_SARK.getDescricao());
        Assert.assertEquals(new Integer(3212), DFPais.GUERNSEY_ILHA_DO_CANAL_INCLUI_ALDERNEY_E_SARK.getCodigo());
        Assert.assertEquals("GUIANA FRANCESA", DFPais.GUIANA_FRANCESA.getDescricao());
        Assert.assertEquals(new Integer(3255), DFPais.GUIANA_FRANCESA.getCodigo());
        Assert.assertEquals("GUINE", DFPais.GUINE.getDescricao());
        Assert.assertEquals(new Integer(3298), DFPais.GUINE.getCodigo());
        Assert.assertEquals("GUINE-EQUATORIAL", DFPais.GUINE_EQUATORIAL.getDescricao());
        Assert.assertEquals(new Integer(3310), DFPais.GUINE_EQUATORIAL.getCodigo());
        Assert.assertEquals("GUINE-BISSAU", DFPais.GUINE_BISSAU.getDescricao());
        Assert.assertEquals(new Integer(3344), DFPais.GUINE_BISSAU.getCodigo());
        Assert.assertEquals("GUIANA", DFPais.GUIANA.getDescricao());
        Assert.assertEquals(new Integer(3379), DFPais.GUIANA.getCodigo());
        Assert.assertEquals("HAITI", DFPais.HAITI.getDescricao());
        Assert.assertEquals(new Integer(3417), DFPais.HAITI.getCodigo());
        Assert.assertEquals("ILHA HEARD E ILHAS MCDONALD", DFPais.ILHA_HEARD_E_ILHAS_MCDONALD.getDescricao());
        Assert.assertEquals(new Integer(3433), DFPais.ILHA_HEARD_E_ILHAS_MCDONALD.getCodigo());
        Assert.assertEquals("HONDURAS", DFPais.HONDURAS.getDescricao());
        Assert.assertEquals(new Integer(3450), DFPais.HONDURAS.getCodigo());
        Assert.assertEquals("HONG KONG", DFPais.HONG_KONG.getDescricao());
        Assert.assertEquals(new Integer(3514), DFPais.HONG_KONG.getCodigo());
        Assert.assertEquals("HUNGRIA, REPUBLICA DA", DFPais.HUNGRIA_REPUBLICA_DA.getDescricao());
        Assert.assertEquals(new Integer(3557), DFPais.HUNGRIA_REPUBLICA_DA.getCodigo());
        Assert.assertEquals("IEMEN", DFPais.IEMEN.getDescricao());
        Assert.assertEquals(new Integer(3573), DFPais.IEMEN.getCodigo());
        Assert.assertEquals("MAN, ILHA DE", DFPais.MAN_ILHA_DE.getDescricao());
        Assert.assertEquals(new Integer(3595), DFPais.MAN_ILHA_DE.getCodigo());
        Assert.assertEquals("INDIA", DFPais.INDIA.getDescricao());
        Assert.assertEquals(new Integer(3611), DFPais.INDIA.getCodigo());
        Assert.assertEquals("INDONESIA", DFPais.INDONESIA.getDescricao());
        Assert.assertEquals(new Integer(3654), DFPais.INDONESIA.getCodigo());
        Assert.assertEquals("IRAQUE", DFPais.IRAQUE.getDescricao());
        Assert.assertEquals(new Integer(3697), DFPais.IRAQUE.getCodigo());
        Assert.assertEquals("IRA, REPUBLICA ISLAMICA DO", DFPais.IRA_REPUBLICA_ISLAMICA_DO.getDescricao());
        Assert.assertEquals(new Integer(3727), DFPais.IRA_REPUBLICA_ISLAMICA_DO.getCodigo());
        Assert.assertEquals("IRLANDA", DFPais.IRLANDA.getDescricao());
        Assert.assertEquals(new Integer(3751), DFPais.IRLANDA.getCodigo());
        Assert.assertEquals("ISLANDIA", DFPais.ISLANDIA.getDescricao());
        Assert.assertEquals(new Integer(3794), DFPais.ISLANDIA.getCodigo());
        Assert.assertEquals("ISRAEL", DFPais.ISRAEL.getDescricao());
        Assert.assertEquals(new Integer(3832), DFPais.ISRAEL.getCodigo());
        Assert.assertEquals("ITALIA", DFPais.ITALIA.getDescricao());
        Assert.assertEquals(new Integer(3867), DFPais.ITALIA.getCodigo());
        Assert.assertEquals("JAMAICA", DFPais.JAMAICA.getDescricao());
        Assert.assertEquals(new Integer(3913), DFPais.JAMAICA.getCodigo());
        Assert.assertEquals("JERSEY, ILHA DO CANAL", DFPais.JERSEY_ILHA_DO_CANAL.getDescricao());
        Assert.assertEquals(new Integer(3930), DFPais.JERSEY_ILHA_DO_CANAL.getCodigo());
        Assert.assertEquals("JOHNSTON, ILHAS", DFPais.JOHNSTON_ILHAS.getDescricao());
        Assert.assertEquals(new Integer(3964), DFPais.JOHNSTON_ILHAS.getCodigo());
        Assert.assertEquals("JAPAO", DFPais.JAPAO.getDescricao());
        Assert.assertEquals(new Integer(3999), DFPais.JAPAO.getCodigo());
        Assert.assertEquals("JORDANIA", DFPais.JORDANIA.getDescricao());
        Assert.assertEquals(new Integer(4030), DFPais.JORDANIA.getCodigo());
        Assert.assertEquals("KIRIBATI", DFPais.KIRIBATI.getDescricao());
        Assert.assertEquals(new Integer(4111), DFPais.KIRIBATI.getCodigo());
        Assert.assertEquals("LAOS, REP.POP.DEMOCR.DO", DFPais.LAOS_REP_POP_DEMOCR_DO.getDescricao());
        Assert.assertEquals(new Integer(4200), DFPais.LAOS_REP_POP_DEMOCR_DO.getCodigo());
        Assert.assertEquals("LEBUAN,ILHAS", DFPais.LEBUAN_ILHAS.getDescricao());
        Assert.assertEquals(new Integer(4235), DFPais.LEBUAN_ILHAS.getCodigo());
        Assert.assertEquals("LESOTO", DFPais.LESOTO.getDescricao());
        Assert.assertEquals(new Integer(4260), DFPais.LESOTO.getCodigo());
        Assert.assertEquals("LETONIA, REPUBLICA DA", DFPais.LETONIA_REPUBLICA_DA.getDescricao());
        Assert.assertEquals(new Integer(4278), DFPais.LETONIA_REPUBLICA_DA.getCodigo());
        Assert.assertEquals("LIBANO", DFPais.LIBANO.getDescricao());
        Assert.assertEquals(new Integer(4316), DFPais.LIBANO.getCodigo());
        Assert.assertEquals("LIBERIA", DFPais.LIBERIA.getDescricao());
        Assert.assertEquals(new Integer(4340), DFPais.LIBERIA.getCodigo());
        Assert.assertEquals("LIBIA", DFPais.LIBIA.getDescricao());
        Assert.assertEquals(new Integer(4383), DFPais.LIBIA.getCodigo());
        Assert.assertEquals("LIECHTENSTEIN", DFPais.LIECHTENSTEIN.getDescricao());
        Assert.assertEquals(new Integer(4405), DFPais.LIECHTENSTEIN.getCodigo());
        Assert.assertEquals("LITUANIA, REPUBLICA DA", DFPais.LITUANIA_REPUBLICA_DA.getDescricao());
        Assert.assertEquals(new Integer(4421), DFPais.LITUANIA_REPUBLICA_DA.getCodigo());
        Assert.assertEquals("LUXEMBURGO", DFPais.LUXEMBURGO.getDescricao());
        Assert.assertEquals(new Integer(4456), DFPais.LUXEMBURGO.getCodigo());
        Assert.assertEquals("MACAU", DFPais.MACAU.getDescricao());
        Assert.assertEquals(new Integer(4472), DFPais.MACAU.getCodigo());
        Assert.assertEquals("MACEDONIA, ANT.REP.IUGOSLAVA", DFPais.MACEDONIA_ANT_REP_IUGOSLAVA.getDescricao());
        Assert.assertEquals(new Integer(4499), DFPais.MACEDONIA_ANT_REP_IUGOSLAVA.getCodigo());
        Assert.assertEquals("MADAGASCAR", DFPais.MADAGASCAR.getDescricao());
        Assert.assertEquals(new Integer(4502), DFPais.MADAGASCAR.getCodigo());
        Assert.assertEquals("MADEIRA, ILHA DA", DFPais.MADEIRA_ILHA_DA.getDescricao());
        Assert.assertEquals(new Integer(4525), DFPais.MADEIRA_ILHA_DA.getCodigo());
        Assert.assertEquals("MALASIA", DFPais.MALASIA.getDescricao());
        Assert.assertEquals(new Integer(4553), DFPais.MALASIA.getCodigo());
        Assert.assertEquals("MALAVI", DFPais.MALAVI.getDescricao());
        Assert.assertEquals(new Integer(4588), DFPais.MALAVI.getCodigo());
        Assert.assertEquals("MALDIVAS", DFPais.MALDIVAS.getDescricao());
        Assert.assertEquals(new Integer(4618), DFPais.MALDIVAS.getCodigo());
        Assert.assertEquals("MALI", DFPais.MALI.getDescricao());
        Assert.assertEquals(new Integer(4642), DFPais.MALI.getCodigo());
        Assert.assertEquals("MALTA", DFPais.MALTA.getDescricao());
        Assert.assertEquals(new Integer(4677), DFPais.MALTA.getCodigo());
        Assert.assertEquals("MARIANAS DO NORTE", DFPais.MARIANAS_DO_NORTE.getDescricao());
        Assert.assertEquals(new Integer(4723), DFPais.MARIANAS_DO_NORTE.getCodigo());
        Assert.assertEquals("MARROCOS", DFPais.MARROCOS.getDescricao());
        Assert.assertEquals(new Integer(4740), DFPais.MARROCOS.getCodigo());
        Assert.assertEquals("MARSHALL,ILHAS", DFPais.MARSHALL_ILHAS.getDescricao());
        Assert.assertEquals(new Integer(4766), DFPais.MARSHALL_ILHAS.getCodigo());
        Assert.assertEquals("MARTINICA", DFPais.MARTINICA.getDescricao());
        Assert.assertEquals(new Integer(4774), DFPais.MARTINICA.getCodigo());
        Assert.assertEquals("MAURICIO", DFPais.MAURICIO.getDescricao());
        Assert.assertEquals(new Integer(4855), DFPais.MAURICIO.getCodigo());
        Assert.assertEquals("MAURITANIA", DFPais.MAURITANIA.getDescricao());
        Assert.assertEquals(new Integer(4880), DFPais.MAURITANIA.getCodigo());
        Assert.assertEquals("MAYOTTE (ILHAS FRANCESAS)", DFPais.MAYOTTE_ILHAS_FRANCESAS.getDescricao());
        Assert.assertEquals(new Integer(4898), DFPais.MAYOTTE_ILHAS_FRANCESAS.getCodigo());
        Assert.assertEquals("MIDWAY, ILHAS", DFPais.MIDWAY_ILHAS.getDescricao());
        Assert.assertEquals(new Integer(4901), DFPais.MIDWAY_ILHAS.getCodigo());
        Assert.assertEquals("MEXICO", DFPais.MEXICO.getDescricao());
        Assert.assertEquals(new Integer(4936), DFPais.MEXICO.getCodigo());
        Assert.assertEquals("MOLDAVIA, REPUBLICA DA", DFPais.MOLDAVIA_REPUBLICA_DA.getDescricao());
        Assert.assertEquals(new Integer(4944), DFPais.MOLDAVIA_REPUBLICA_DA.getCodigo());
        Assert.assertEquals("MONACO", DFPais.MONACO.getDescricao());
        Assert.assertEquals(new Integer(4952), DFPais.MONACO.getCodigo());
        Assert.assertEquals("MONGOLIA", DFPais.MONGOLIA.getDescricao());
        Assert.assertEquals(new Integer(4979), DFPais.MONGOLIA.getCodigo());
        Assert.assertEquals("MONTENEGRO", DFPais.MONTENEGRO.getDescricao());
        Assert.assertEquals(new Integer(4985), DFPais.MONTENEGRO.getCodigo());
        Assert.assertEquals("MICRONESIA", DFPais.MICRONESIA.getDescricao());
        Assert.assertEquals(new Integer(4995), DFPais.MICRONESIA.getCodigo());
        Assert.assertEquals("MONTSERRAT,ILHAS", DFPais.MONTSERRAT_ILHAS.getDescricao());
        Assert.assertEquals(new Integer(5010), DFPais.MONTSERRAT_ILHAS.getCodigo());
        Assert.assertEquals("MOCAMBIQUE", DFPais.MOCAMBIQUE.getDescricao());
        Assert.assertEquals(new Integer(5053), DFPais.MOCAMBIQUE.getCodigo());
        Assert.assertEquals("NAMIBIA", DFPais.NAMIBIA.getDescricao());
        Assert.assertEquals(new Integer(5070), DFPais.NAMIBIA.getCodigo());
        Assert.assertEquals("NAURU", DFPais.NAURU.getDescricao());
        Assert.assertEquals(new Integer(5088), DFPais.NAURU.getCodigo());
        Assert.assertEquals("CHRISTMAS,ILHA (NAVIDAD)", DFPais.CHRISTMAS_ILHA_NAVIDAD.getDescricao());
        Assert.assertEquals(new Integer(5118), DFPais.CHRISTMAS_ILHA_NAVIDAD.getCodigo());
        Assert.assertEquals("NEPAL", DFPais.NEPAL.getDescricao());
        Assert.assertEquals(new Integer(5177), DFPais.NEPAL.getCodigo());
        Assert.assertEquals("NICARAGUA", DFPais.NICARAGUA.getDescricao());
        Assert.assertEquals(new Integer(5215), DFPais.NICARAGUA.getCodigo());
        Assert.assertEquals("NIGER", DFPais.NIGER.getDescricao());
        Assert.assertEquals(new Integer(5258), DFPais.NIGER.getCodigo());
        Assert.assertEquals("NIGERIA", DFPais.NIGERIA.getDescricao());
        Assert.assertEquals(new Integer(5282), DFPais.NIGERIA.getCodigo());
        Assert.assertEquals("NIUE,ILHA", DFPais.NIUE_ILHA.getDescricao());
        Assert.assertEquals(new Integer(5312), DFPais.NIUE_ILHA.getCodigo());
        Assert.assertEquals("NORFOLK,ILHA", DFPais.NORFOLK_ILHA.getDescricao());
        Assert.assertEquals(new Integer(5355), DFPais.NORFOLK_ILHA.getCodigo());
        Assert.assertEquals("NORUEGA", DFPais.NORUEGA.getDescricao());
        Assert.assertEquals(new Integer(5380), DFPais.NORUEGA.getCodigo());
        Assert.assertEquals("NOVA CALEDONIA", DFPais.NOVA_CALEDONIA.getDescricao());
        Assert.assertEquals(new Integer(5428), DFPais.NOVA_CALEDONIA.getCodigo());
        Assert.assertEquals("PAPUA NOVA GUINE", DFPais.PAPUA_NOVA_GUINE.getDescricao());
        Assert.assertEquals(new Integer(5452), DFPais.PAPUA_NOVA_GUINE.getCodigo());
        Assert.assertEquals("NOVA ZELANDIA", DFPais.NOVA_ZELANDIA.getDescricao());
        Assert.assertEquals(new Integer(5487), DFPais.NOVA_ZELANDIA.getCodigo());
        Assert.assertEquals("VANUATU", DFPais.VANUATU.getDescricao());
        Assert.assertEquals(new Integer(5517), DFPais.VANUATU.getCodigo());
        Assert.assertEquals("OMA", DFPais.OMA.getDescricao());
        Assert.assertEquals(new Integer(5568), DFPais.OMA.getCodigo());
        Assert.assertEquals("PACIFICO,ILHAS DO (POSSESSAO DOS EUA)", DFPais.PACIFICO_ILHAS_DO_POSSESSAO_DOS_EUA.getDescricao());
        Assert.assertEquals(new Integer(5665), DFPais.PACIFICO_ILHAS_DO_POSSESSAO_DOS_EUA.getCodigo());
        Assert.assertEquals("PAISES BAIXOS (HOLANDA)", DFPais.PAISES_BAIXOS_HOLANDA.getDescricao());
        Assert.assertEquals(new Integer(5738), DFPais.PAISES_BAIXOS_HOLANDA.getCodigo());
        Assert.assertEquals("PALAU", DFPais.PALAU.getDescricao());
        Assert.assertEquals(new Integer(5754), DFPais.PALAU.getCodigo());
        Assert.assertEquals("PAQUISTAO", DFPais.PAQUISTAO.getDescricao());
        Assert.assertEquals(new Integer(5762), DFPais.PAQUISTAO.getCodigo());
        Assert.assertEquals("PALESTINA", DFPais.PALESTINA.getDescricao());
        Assert.assertEquals(new Integer(5780), DFPais.PALESTINA.getCodigo());
        Assert.assertEquals("PANAMA", DFPais.PANAMA.getDescricao());
        Assert.assertEquals(new Integer(5800), DFPais.PANAMA.getCodigo());
        Assert.assertEquals("PARAGUAI", DFPais.PARAGUAI.getDescricao());
        Assert.assertEquals(new Integer(5860), DFPais.PARAGUAI.getCodigo());
        Assert.assertEquals("PERU", DFPais.PERU.getDescricao());
        Assert.assertEquals(new Integer(5894), DFPais.PERU.getCodigo());
        Assert.assertEquals("PITCAIRN,ILHA", DFPais.PITCAIRN_ILHA.getDescricao());
        Assert.assertEquals(new Integer(5932), DFPais.PITCAIRN_ILHA.getCodigo());
        Assert.assertEquals("POLINESIA FRANCESA", DFPais.POLINESIA_FRANCESA.getDescricao());
        Assert.assertEquals(new Integer(5991), DFPais.POLINESIA_FRANCESA.getCodigo());
        Assert.assertEquals("POLONIA, REPUBLICA DA", DFPais.POLONIA_REPUBLICA_DA.getDescricao());
        Assert.assertEquals(new Integer(6033), DFPais.POLONIA_REPUBLICA_DA.getCodigo());
        Assert.assertEquals("PORTUGAL", DFPais.PORTUGAL.getDescricao());
        Assert.assertEquals(new Integer(6076), DFPais.PORTUGAL.getCodigo());
        Assert.assertEquals("PORTO RICO", DFPais.PORTO_RICO.getDescricao());
        Assert.assertEquals(new Integer(6114), DFPais.PORTO_RICO.getCodigo());
        Assert.assertEquals("QUENIA", DFPais.QUENIA.getDescricao());
        Assert.assertEquals(new Integer(6238), DFPais.QUENIA.getCodigo());
        Assert.assertEquals("QUIRGUIZ, REPUBLICA", DFPais.QUIRGUIZ_REPUBLICA.getDescricao());
        Assert.assertEquals(new Integer(6254), DFPais.QUIRGUIZ_REPUBLICA.getCodigo());
        Assert.assertEquals("REINO UNIDO", DFPais.REINO_UNIDO.getDescricao());
        Assert.assertEquals(new Integer(6289), DFPais.REINO_UNIDO.getCodigo());
        Assert.assertEquals("REPUBLICA CENTRO-AFRICANA", DFPais.REPUBLICA_CENTRO_AFRICANA.getDescricao());
        Assert.assertEquals(new Integer(6408), DFPais.REPUBLICA_CENTRO_AFRICANA.getCodigo());
        Assert.assertEquals("REPUBLICA DOMINICANA", DFPais.REPUBLICA_DOMINICANA.getDescricao());
        Assert.assertEquals(new Integer(6475), DFPais.REPUBLICA_DOMINICANA.getCodigo());
        Assert.assertEquals("REUNIAO, ILHA", DFPais.REUNIAO_ILHA.getDescricao());
        Assert.assertEquals(new Integer(6602), DFPais.REUNIAO_ILHA.getCodigo());
        Assert.assertEquals("ZIMBABUE", DFPais.ZIMBABUE.getDescricao());
        Assert.assertEquals(new Integer(6653), DFPais.ZIMBABUE.getCodigo());
        Assert.assertEquals("ROMENIA", DFPais.ROMENIA.getDescricao());
        Assert.assertEquals(new Integer(6700), DFPais.ROMENIA.getCodigo());
        Assert.assertEquals("RUANDA", DFPais.RUANDA.getDescricao());
        Assert.assertEquals(new Integer(6750), DFPais.RUANDA.getCodigo());
        Assert.assertEquals("RUSSIA, FEDERACAO DA", DFPais.RUSSIA_FEDERACAO_DA.getDescricao());
        Assert.assertEquals(new Integer(6769), DFPais.RUSSIA_FEDERACAO_DA.getCodigo());
        Assert.assertEquals("SALOMAO, ILHAS", DFPais.SALOMAO_ILHAS.getDescricao());
        Assert.assertEquals(new Integer(6777), DFPais.SALOMAO_ILHAS.getCodigo());
        Assert.assertEquals("SAARA OCIDENTAL", DFPais.SAARA_OCIDENTAL.getDescricao());
        Assert.assertEquals(new Integer(6858), DFPais.SAARA_OCIDENTAL.getCodigo());
        Assert.assertEquals("EL SALVADOR", DFPais.EL_SALVADOR.getDescricao());
        Assert.assertEquals(new Integer(6874), DFPais.EL_SALVADOR.getCodigo());
        Assert.assertEquals("SAMOA", DFPais.SAMOA.getDescricao());
        Assert.assertEquals(new Integer(6904), DFPais.SAMOA.getCodigo());
        Assert.assertEquals("SAMOA AMERICANA", DFPais.SAMOA_AMERICANA.getDescricao());
        Assert.assertEquals(new Integer(6912), DFPais.SAMOA_AMERICANA.getCodigo());
        Assert.assertEquals("SAO CRISTOVAO E NEVES,ILHAS", DFPais.SAO_CRISTOVAO_E_NEVES_ILHAS.getDescricao());
        Assert.assertEquals(new Integer(6955), DFPais.SAO_CRISTOVAO_E_NEVES_ILHAS.getCodigo());
        Assert.assertEquals("SAO BARTOLOMEU", DFPais.SAO_BARTOLOMEU.getDescricao());
        Assert.assertEquals(new Integer(6939), DFPais.SAO_BARTOLOMEU.getCodigo());
        Assert.assertEquals("SAN MARINO", DFPais.SAN_MARINO.getDescricao());
        Assert.assertEquals(new Integer(6971), DFPais.SAN_MARINO.getCodigo());
        Assert.assertEquals("ILHAS DE SAO MARTINHO (PARTE FRANCESA)", DFPais.ILHAS_DE_SAO_MARTINHO_PARTE_FRANCESA.getDescricao());
        Assert.assertEquals(new Integer(6980), DFPais.ILHAS_DE_SAO_MARTINHO_PARTE_FRANCESA.getCodigo());
        Assert.assertEquals("SAO MARTINHO, ILHA DE (PARTE FRANCESA)", DFPais.SAO_MARTINHO_ILHA_DE_PARTE_FRANCESA.getDescricao());
        Assert.assertEquals(new Integer(6998), DFPais.SAO_MARTINHO_ILHA_DE_PARTE_FRANCESA.getCodigo());
        Assert.assertEquals("SAO PEDRO E MIQUELON", DFPais.SAO_PEDRO_E_MIQUELON.getDescricao());
        Assert.assertEquals(new Integer(7005), DFPais.SAO_PEDRO_E_MIQUELON.getCodigo());
        Assert.assertEquals("SAO VICENTE E GRANADINAS", DFPais.SAO_VICENTE_E_GRANADINAS.getDescricao());
        Assert.assertEquals(new Integer(7056), DFPais.SAO_VICENTE_E_GRANADINAS.getCodigo());
        Assert.assertEquals("SANTA HELENA", DFPais.SANTA_HELENA.getDescricao());
        Assert.assertEquals(new Integer(7102), DFPais.SANTA_HELENA.getCodigo());
        Assert.assertEquals("SANTA LUCIA", DFPais.SANTA_LUCIA.getDescricao());
        Assert.assertEquals(new Integer(7153), DFPais.SANTA_LUCIA.getCodigo());
        Assert.assertEquals("SAO TOME E PRINCIPE, ILHAS", DFPais.SAO_TOME_E_PRINCIPE_ILHAS.getDescricao());
        Assert.assertEquals(new Integer(7200), DFPais.SAO_TOME_E_PRINCIPE_ILHAS.getCodigo());
        Assert.assertEquals("SENEGAL", DFPais.SENEGAL.getDescricao());
        Assert.assertEquals(new Integer(7285), DFPais.SENEGAL.getCodigo());
        Assert.assertEquals("SEYCHELLES", DFPais.SEYCHELLES.getDescricao());
        Assert.assertEquals(new Integer(7315), DFPais.SEYCHELLES.getCodigo());
        Assert.assertEquals("SERRA LEOA", DFPais.SERRA_LEOA.getDescricao());
        Assert.assertEquals(new Integer(7358), DFPais.SERRA_LEOA.getCodigo());
        Assert.assertEquals("SERVIA", DFPais.SERVIA.getDescricao());
        Assert.assertEquals(new Integer(7370), DFPais.SERVIA.getCodigo());
        Assert.assertEquals("CINGAPURA", DFPais.CINGAPURA.getDescricao());
        Assert.assertEquals(new Integer(7412), DFPais.CINGAPURA.getCodigo());
        Assert.assertEquals("SIRIA, REPUBLICA ARABE DA", DFPais.SIRIA_REPUBLICA_ARABE_DA.getDescricao());
        Assert.assertEquals(new Integer(7447), DFPais.SIRIA_REPUBLICA_ARABE_DA.getCodigo());
        Assert.assertEquals("SOMALIA", DFPais.SOMALIA.getDescricao());
        Assert.assertEquals(new Integer(7480), DFPais.SOMALIA.getCodigo());
        Assert.assertEquals("SRI LANKA", DFPais.SRI_LANKA.getDescricao());
        Assert.assertEquals(new Integer(7501), DFPais.SRI_LANKA.getCodigo());
        Assert.assertEquals("SUAZILANDIA", DFPais.SUAZILANDIA.getDescricao());
        Assert.assertEquals(new Integer(7544), DFPais.SUAZILANDIA.getCodigo());
        Assert.assertEquals("SVALBARD E JAN MAYERN", DFPais.SVALBARD_E_JAN_MAYERN.getDescricao());
        Assert.assertEquals(new Integer(7552), DFPais.SVALBARD_E_JAN_MAYERN.getCodigo());
        Assert.assertEquals("AFRICA DO SUL", DFPais.AFRICA_DO_SUL.getDescricao());
        Assert.assertEquals(new Integer(7560), DFPais.AFRICA_DO_SUL.getCodigo());
        Assert.assertEquals("SUDAO", DFPais.SUDAO.getDescricao());
        Assert.assertEquals(new Integer(7595), DFPais.SUDAO.getCodigo());
        Assert.assertEquals("SUDÃO DO SUL", DFPais.SUD_O_DO_SUL.getDescricao());
        Assert.assertEquals(new Integer(7600), DFPais.SUD_O_DO_SUL.getCodigo());
        Assert.assertEquals("SUECIA", DFPais.SUECIA.getDescricao());
        Assert.assertEquals(new Integer(7641), DFPais.SUECIA.getCodigo());
        Assert.assertEquals("SUICA", DFPais.SUICA.getDescricao());
        Assert.assertEquals(new Integer(7676), DFPais.SUICA.getCodigo());
        Assert.assertEquals("SURINAME", DFPais.SURINAME.getDescricao());
        Assert.assertEquals(new Integer(7706), DFPais.SURINAME.getCodigo());
        Assert.assertEquals("TADJIQUISTAO, REPUBLICA DO", DFPais.TADJIQUISTAO_REPUBLICA_DO.getDescricao());
        Assert.assertEquals(new Integer(7722), DFPais.TADJIQUISTAO_REPUBLICA_DO.getCodigo());
        Assert.assertEquals("TAILANDIA", DFPais.TAILANDIA.getDescricao());
        Assert.assertEquals(new Integer(7765), DFPais.TAILANDIA.getCodigo());
        Assert.assertEquals("TANZANIA, REP.UNIDA DA", DFPais.TANZANIA_REP_UNIDA_DA.getDescricao());
        Assert.assertEquals(new Integer(7803), DFPais.TANZANIA_REP_UNIDA_DA.getCodigo());
        Assert.assertEquals("TERRAS AUSTRAIS E ANTARTICAS FRANCESAS", DFPais.TERRAS_AUSTRAIS_E_ANTARTICAS_FRANCESAS.getDescricao());
        Assert.assertEquals(new Integer(7811), DFPais.TERRAS_AUSTRAIS_E_ANTARTICAS_FRANCESAS.getCodigo());
        Assert.assertEquals("TERRITORIO BRIT.OC.INDICO", DFPais.TERRITORIO_BRIT_OC_INDICO.getDescricao());
        Assert.assertEquals(new Integer(7820), DFPais.TERRITORIO_BRIT_OC_INDICO.getCodigo());
        Assert.assertEquals("DJIBUTI", DFPais.DJIBUTI.getDescricao());
        Assert.assertEquals(new Integer(7838), DFPais.DJIBUTI.getCodigo());
        Assert.assertEquals("CHADE", DFPais.CHADE.getDescricao());
        Assert.assertEquals(new Integer(7889), DFPais.CHADE.getCodigo());
        Assert.assertEquals("TCHECA, REPUBLICA", DFPais.TCHECA_REPUBLICA.getDescricao());
        Assert.assertEquals(new Integer(7919), DFPais.TCHECA_REPUBLICA.getCodigo());
        Assert.assertEquals("TIMOR LESTE", DFPais.TIMOR_LESTE.getDescricao());
        Assert.assertEquals(new Integer(7951), DFPais.TIMOR_LESTE.getCodigo());
        Assert.assertEquals("TOGO", DFPais.TOGO.getDescricao());
        Assert.assertEquals(new Integer(8001), DFPais.TOGO.getCodigo());
        Assert.assertEquals("TOQUELAU,ILHAS", DFPais.TOQUELAU_ILHAS.getDescricao());
        Assert.assertEquals(new Integer(8052), DFPais.TOQUELAU_ILHAS.getCodigo());
        Assert.assertEquals("TONGA", DFPais.TONGA.getDescricao());
        Assert.assertEquals(new Integer(8109), DFPais.TONGA.getCodigo());
        Assert.assertEquals("TRINIDAD E TOBAGO", DFPais.TRINIDAD_E_TOBAGO.getDescricao());
        Assert.assertEquals(new Integer(8150), DFPais.TRINIDAD_E_TOBAGO.getCodigo());
        Assert.assertEquals("TUNISIA", DFPais.TUNISIA.getDescricao());
        Assert.assertEquals(new Integer(8206), DFPais.TUNISIA.getCodigo());
        Assert.assertEquals("TURCAS E CAICOS,ILHAS", DFPais.TURCAS_E_CAICOS_ILHAS.getDescricao());
        Assert.assertEquals(new Integer(8230), DFPais.TURCAS_E_CAICOS_ILHAS.getCodigo());
        Assert.assertEquals("TURCOMENISTAO, REPUBLICA DO", DFPais.TURCOMENISTAO_REPUBLICA_DO.getDescricao());
        Assert.assertEquals(new Integer(8249), DFPais.TURCOMENISTAO_REPUBLICA_DO.getCodigo());
        Assert.assertEquals("TURQUIA", DFPais.TURQUIA.getDescricao());
        Assert.assertEquals(new Integer(8273), DFPais.TURQUIA.getCodigo());
        Assert.assertEquals("TUVALU", DFPais.TUVALU.getDescricao());
        Assert.assertEquals(new Integer(8281), DFPais.TUVALU.getCodigo());
        Assert.assertEquals("UCRANIA", DFPais.UCRANIA.getDescricao());
        Assert.assertEquals(new Integer(8311), DFPais.UCRANIA.getCodigo());
        Assert.assertEquals("UGANDA", DFPais.UGANDA.getDescricao());
        Assert.assertEquals(new Integer(8338), DFPais.UGANDA.getCodigo());
        Assert.assertEquals("URUGUAI", DFPais.URUGUAI.getDescricao());
        Assert.assertEquals(new Integer(8451), DFPais.URUGUAI.getCodigo());
        Assert.assertEquals("UZBEQUISTAO, REPUBLICA DO", DFPais.UZBEQUISTAO_REPUBLICA_DO.getDescricao());
        Assert.assertEquals(new Integer(8478), DFPais.UZBEQUISTAO_REPUBLICA_DO.getCodigo());
        Assert.assertEquals("VATICANO, EST.DA CIDADE DO", DFPais.VATICANO_EST_DA_CIDADE_DO.getDescricao());
        Assert.assertEquals(new Integer(8486), DFPais.VATICANO_EST_DA_CIDADE_DO.getCodigo());
        Assert.assertEquals("VENEZUELA", DFPais.VENEZUELA.getDescricao());
        Assert.assertEquals(new Integer(8508), DFPais.VENEZUELA.getCodigo());
        Assert.assertEquals("VIETNA", DFPais.VIETNA.getDescricao());
        Assert.assertEquals(new Integer(8583), DFPais.VIETNA.getCodigo());
        Assert.assertEquals("VIRGENS,ILHAS (BRITANICAS)", DFPais.VIRGENS_ILHAS_BRITANICAS.getDescricao());
        Assert.assertEquals(new Integer(8630), DFPais.VIRGENS_ILHAS_BRITANICAS.getCodigo());
        Assert.assertEquals("VIRGENS,ILHAS (E.U.A.)", DFPais.VIRGENS_ILHAS_E_U_A.getDescricao());
        Assert.assertEquals(new Integer(8664), DFPais.VIRGENS_ILHAS_E_U_A.getCodigo());
        Assert.assertEquals("FIJI", DFPais.FIJI.getDescricao());
        Assert.assertEquals(new Integer(8702), DFPais.FIJI.getCodigo());
        Assert.assertEquals("WALLIS E FUTUNA, ILHAS", DFPais.WALLIS_E_FUTUNA_ILHAS.getDescricao());
        Assert.assertEquals(new Integer(8753), DFPais.WALLIS_E_FUTUNA_ILHAS.getCodigo());
        Assert.assertEquals("WAKE, ILHA", DFPais.WAKE_ILHA.getDescricao());
        Assert.assertEquals(new Integer(8737), DFPais.WAKE_ILHA.getCodigo());
        Assert.assertEquals("CONGO, REPUBLICA DEMOCRATICA DO", DFPais.CONGO_REPUBLICA_DEMOCRATICA_DO.getDescricao());
        Assert.assertEquals(new Integer(8885), DFPais.CONGO_REPUBLICA_DEMOCRATICA_DO.getCodigo());
        Assert.assertEquals("ZAMBIA", DFPais.ZAMBIA.getDescricao());
        Assert.assertEquals(new Integer(8907), DFPais.ZAMBIA.getCodigo());

    }

    @Test
    public void deveRetornarNullCasoTenteBuscarUmCodigoErrado() {
        Assert.assertNull(DFPais.valueOfCodigo("1"));
        Assert.assertNull(DFPais.valueOfCodigo(1));
    }

    @Test
    public void deveSerADescricaoAoInvocarToString() {
        Assert.assertEquals("AFRICA DO SUL", DFPais.AFRICA_DO_SUL.toString());
        Assert.assertEquals("BOSNIA-HERZEGOVINA (REPUBLICA DA)", DFPais.BOSNIA_HERZEGOVINA_REPUBLICA_DA.toString());
    }

    @Test
    public void deveRetornarListaAoPesquisarPorNome() {
        Assert.assertEquals(Arrays.asList(DFPais.BRASIL, DFPais.GIBRALTAR), DFPais.getListByDesc("BRA"));
        Assert.assertEquals(Arrays.asList(DFPais.BRASIL, DFPais.GIBRALTAR), DFPais.getListByDesc("bra"));
        Assert.assertEquals(Arrays.asList(DFPais.BRASIL, DFPais.GIBRALTAR), DFPais.getListByDesc("Bra"));
        Assert.assertEquals(Arrays.asList(DFPais.HONDURAS, DFPais.BRASIL,
                DFPais.TERRAS_AUSTRAIS_E_ANTARTICAS_FRANCESAS), DFPais.getListByDesc("RAS"));
    }

}