package com.fincatto.documentofiscal;

import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Test;

import java.util.Arrays;

/**
 * Created by Eldevan Nery Junior on 07/05/18.
 * Define os Testes para a classe com.fincatto.documentofiscal.DFPais.java
 *
 */
public class DFPaisTest {

    @Test
    public void deveRepresentarOCodigoCorretamente() {
        Assertions.assertEquals("AFEGANISTAO", DFPais.AFEGANISTAO.getDescricao());
        Assertions.assertEquals(Integer.valueOf(132), DFPais.AFEGANISTAO.getCodigo());
        Assertions.assertEquals("ALAND, ILHAS", DFPais.ALAND_ILHAS.getDescricao());
        Assertions.assertEquals(Integer.valueOf(153), DFPais.ALAND_ILHAS.getCodigo());
        Assertions.assertEquals("ALBANIA, REPUBLICA  DA", DFPais.ALBANIA_REPUBLICA_DA.getDescricao());
        Assertions.assertEquals(Integer.valueOf(175), DFPais.ALBANIA_REPUBLICA_DA.getCodigo());
        Assertions.assertEquals("ALEMANHA", DFPais.ALEMANHA.getDescricao());
        Assertions.assertEquals(Integer.valueOf(230), DFPais.ALEMANHA.getCodigo());
        Assertions.assertEquals("BURKINA FASO", DFPais.BURKINA_FASO.getDescricao());
        Assertions.assertEquals(Integer.valueOf(310), DFPais.BURKINA_FASO.getCodigo());
        Assertions.assertEquals("ANDORRA", DFPais.ANDORRA.getDescricao());
        Assertions.assertEquals(Integer.valueOf(370), DFPais.ANDORRA.getCodigo());
        Assertions.assertEquals("ANGOLA", DFPais.ANGOLA.getDescricao());
        Assertions.assertEquals(Integer.valueOf(400), DFPais.ANGOLA.getCodigo());
        Assertions.assertEquals("ANGUILLA", DFPais.ANGUILLA.getDescricao());
        Assertions.assertEquals(Integer.valueOf(418), DFPais.ANGUILLA.getCodigo());
        Assertions.assertEquals("ANTARTICA", DFPais.ANTARTICA.getDescricao());
        Assertions.assertEquals(Integer.valueOf(420), DFPais.ANTARTICA.getCodigo());
        Assertions.assertEquals("ANTIGUA E BARBUDA", DFPais.ANTIGUA_E_BARBUDA.getDescricao());
        Assertions.assertEquals(Integer.valueOf(434), DFPais.ANTIGUA_E_BARBUDA.getCodigo());
        Assertions.assertEquals("ANTILHAS HOLANDESAS", DFPais.ANTILHAS_HOLANDESAS.getDescricao());
        Assertions.assertEquals(Integer.valueOf(477), DFPais.ANTILHAS_HOLANDESAS.getCodigo());
        Assertions.assertEquals("ARABIA SAUDITA", DFPais.ARABIA_SAUDITA.getDescricao());
        Assertions.assertEquals(Integer.valueOf(531), DFPais.ARABIA_SAUDITA.getCodigo());
        Assertions.assertEquals("ARGELIA", DFPais.ARGELIA.getDescricao());
        Assertions.assertEquals(Integer.valueOf(590), DFPais.ARGELIA.getCodigo());
        Assertions.assertEquals("ARGENTINA", DFPais.ARGENTINA.getDescricao());
        Assertions.assertEquals(Integer.valueOf(639), DFPais.ARGENTINA.getCodigo());
        Assertions.assertEquals("ARMENIA, REPUBLICA DA", DFPais.ARMENIA_REPUBLICA_DA.getDescricao());
        Assertions.assertEquals(Integer.valueOf(647), DFPais.ARMENIA_REPUBLICA_DA.getCodigo());
        Assertions.assertEquals("ARUBA", DFPais.ARUBA.getDescricao());
        Assertions.assertEquals(Integer.valueOf(655), DFPais.ARUBA.getCodigo());
        Assertions.assertEquals("AUSTRALIA", DFPais.AUSTRALIA.getDescricao());
        Assertions.assertEquals(Integer.valueOf(698), DFPais.AUSTRALIA.getCodigo());
        Assertions.assertEquals("AUSTRIA", DFPais.AUSTRIA.getDescricao());
        Assertions.assertEquals(Integer.valueOf(728), DFPais.AUSTRIA.getCodigo());
        Assertions.assertEquals("AZERBAIJAO, REPUBLICA DO", DFPais.AZERBAIJAO_REPUBLICA_DO.getDescricao());
        Assertions.assertEquals(Integer.valueOf(736), DFPais.AZERBAIJAO_REPUBLICA_DO.getCodigo());
        Assertions.assertEquals("BAHAMAS, ILHAS", DFPais.BAHAMAS_ILHAS.getDescricao());
        Assertions.assertEquals(Integer.valueOf(779), DFPais.BAHAMAS_ILHAS.getCodigo());
        Assertions.assertEquals("BAHREIN, ILHAS", DFPais.BAHREIN_ILHAS.getDescricao());
        Assertions.assertEquals(Integer.valueOf(809), DFPais.BAHREIN_ILHAS.getCodigo());
        Assertions.assertEquals("BANGLADESH", DFPais.BANGLADESH.getDescricao());
        Assertions.assertEquals(Integer.valueOf(817), DFPais.BANGLADESH.getCodigo());
        Assertions.assertEquals("BARBADOS", DFPais.BARBADOS.getDescricao());
        Assertions.assertEquals(Integer.valueOf(833), DFPais.BARBADOS.getCodigo());
        Assertions.assertEquals("BELARUS, REPUBLICA DA", DFPais.BELARUS_REPUBLICA_DA.getDescricao());
        Assertions.assertEquals(Integer.valueOf(850), DFPais.BELARUS_REPUBLICA_DA.getCodigo());
        Assertions.assertEquals("BELGICA", DFPais.BELGICA.getDescricao());
        Assertions.assertEquals(Integer.valueOf(876), DFPais.BELGICA.getCodigo());
        Assertions.assertEquals("BELIZE", DFPais.BELIZE.getDescricao());
        Assertions.assertEquals(Integer.valueOf(884), DFPais.BELIZE.getCodigo());
        Assertions.assertEquals("BERMUDAS", DFPais.BERMUDAS.getDescricao());
        Assertions.assertEquals(Integer.valueOf(906), DFPais.BERMUDAS.getCodigo());
        Assertions.assertEquals("MIANMAR (BIRMANIA)", DFPais.MIANMAR_BIRMANIA.getDescricao());
        Assertions.assertEquals(Integer.valueOf(930), DFPais.MIANMAR_BIRMANIA.getCodigo());
        Assertions.assertEquals("BOLIVIA, ESTADO PLURINACIONAL DA", DFPais.BOLIVIA_ESTADO_PLURINACIONAL_DA.getDescricao());
        Assertions.assertEquals(Integer.valueOf(973), DFPais.BOLIVIA_ESTADO_PLURINACIONAL_DA.getCodigo());
        Assertions.assertEquals("BOSNIA-HERZEGOVINA (REPUBLICA DA)", DFPais.BOSNIA_HERZEGOVINA_REPUBLICA_DA.getDescricao());
        Assertions.assertEquals(Integer.valueOf(981), DFPais.BOSNIA_HERZEGOVINA_REPUBLICA_DA.getCodigo());
        Assertions.assertEquals("BONAIRE", DFPais.BONAIRE.getDescricao());
        Assertions.assertEquals(Integer.valueOf(990), DFPais.BONAIRE.getCodigo());
        Assertions.assertEquals("BOTSUANA", DFPais.BOTSUANA.getDescricao());
        Assertions.assertEquals(Integer.valueOf(1015), DFPais.BOTSUANA.getCodigo());
        Assertions.assertEquals("BOUVET, ILHA", DFPais.BOUVET_ILHA.getDescricao());
        Assertions.assertEquals(Integer.valueOf(1023), DFPais.BOUVET_ILHA.getCodigo());
        Assertions.assertEquals("BRASIL", DFPais.BRASIL.getDescricao());
        Assertions.assertEquals(Integer.valueOf(1058), DFPais.BRASIL.getCodigo());
        Assertions.assertEquals("BRUNEI", DFPais.BRUNEI.getDescricao());
        Assertions.assertEquals(Integer.valueOf(1082), DFPais.BRUNEI.getCodigo());
        Assertions.assertEquals("BULGARIA, REPUBLICA DA", DFPais.BULGARIA_REPUBLICA_DA.getDescricao());
        Assertions.assertEquals(Integer.valueOf(1112), DFPais.BULGARIA_REPUBLICA_DA.getCodigo());
        Assertions.assertEquals("BURUNDI", DFPais.BURUNDI.getDescricao());
        Assertions.assertEquals(Integer.valueOf(1155), DFPais.BURUNDI.getCodigo());
        Assertions.assertEquals("BUTAO", DFPais.BUTAO.getDescricao());
        Assertions.assertEquals(Integer.valueOf(1198), DFPais.BUTAO.getCodigo());
        Assertions.assertEquals("CABO VERDE, REPUBLICA DE", DFPais.CABO_VERDE_REPUBLICA_DE.getDescricao());
        Assertions.assertEquals(Integer.valueOf(1279), DFPais.CABO_VERDE_REPUBLICA_DE.getCodigo());
        Assertions.assertEquals("CAYMAN, ILHAS", DFPais.CAYMAN_ILHAS.getDescricao());
        Assertions.assertEquals(Integer.valueOf(1376), DFPais.CAYMAN_ILHAS.getCodigo());
        Assertions.assertEquals("CAMBOJA", DFPais.CAMBOJA.getDescricao());
        Assertions.assertEquals(Integer.valueOf(1414), DFPais.CAMBOJA.getCodigo());
        Assertions.assertEquals("CAMAROES", DFPais.CAMAROES.getDescricao());
        Assertions.assertEquals(Integer.valueOf(1457), DFPais.CAMAROES.getCodigo());
        Assertions.assertEquals("CANADA", DFPais.CANADA.getDescricao());
        Assertions.assertEquals(Integer.valueOf(1490), DFPais.CANADA.getCodigo());
        Assertions.assertEquals("CAZAQUISTAO, REPUBLICA DO", DFPais.CAZAQUISTAO_REPUBLICA_DO.getDescricao());
        Assertions.assertEquals(Integer.valueOf(1538), DFPais.CAZAQUISTAO_REPUBLICA_DO.getCodigo());
        Assertions.assertEquals("CATAR", DFPais.CATAR.getDescricao());
        Assertions.assertEquals(Integer.valueOf(1546), DFPais.CATAR.getCodigo());
        Assertions.assertEquals("CHILE", DFPais.CHILE.getDescricao());
        Assertions.assertEquals(Integer.valueOf(1589), DFPais.CHILE.getCodigo());
        Assertions.assertEquals("CHINA, REPUBLICA POPULAR", DFPais.CHINA_REPUBLICA_POPULAR.getDescricao());
        Assertions.assertEquals(Integer.valueOf(1600), DFPais.CHINA_REPUBLICA_POPULAR.getCodigo());
        Assertions.assertEquals("FORMOSA (TAIWAN)", DFPais.FORMOSA_TAIWAN.getDescricao());
        Assertions.assertEquals(Integer.valueOf(1619), DFPais.FORMOSA_TAIWAN.getCodigo());
        Assertions.assertEquals("CHIPRE", DFPais.CHIPRE.getDescricao());
        Assertions.assertEquals(Integer.valueOf(1635), DFPais.CHIPRE.getCodigo());
        Assertions.assertEquals("COCOS(KEELING),ILHAS", DFPais.COCOS_KEELING_ILHAS.getDescricao());
        Assertions.assertEquals(Integer.valueOf(1651), DFPais.COCOS_KEELING_ILHAS.getCodigo());
        Assertions.assertEquals("COLOMBIA", DFPais.COLOMBIA.getDescricao());
        Assertions.assertEquals(Integer.valueOf(1694), DFPais.COLOMBIA.getCodigo());
        Assertions.assertEquals("COMORES, ILHAS", DFPais.COMORES_ILHAS.getDescricao());
        Assertions.assertEquals(Integer.valueOf(1732), DFPais.COMORES_ILHAS.getCodigo());
        Assertions.assertEquals("CONGO", DFPais.CONGO.getDescricao());
        Assertions.assertEquals(Integer.valueOf(1775), DFPais.CONGO.getCodigo());
        Assertions.assertEquals("COOK, ILHAS", DFPais.COOK_ILHAS.getDescricao());
        Assertions.assertEquals(Integer.valueOf(1830), DFPais.COOK_ILHAS.getCodigo());
        Assertions.assertEquals("COREIA (DO NORTE), REP.POP.DEMOCRATICA", DFPais.COREIA_DO_NORTE__REP_POP_DEMOCRATICA.getDescricao());
        Assertions.assertEquals(Integer.valueOf(1872), DFPais.COREIA_DO_NORTE__REP_POP_DEMOCRATICA.getCodigo());
        Assertions.assertEquals("COREIA (DO SUL), REPUBLICA DA", DFPais.COREIA_DO_SUL__REPUBLICA_DA.getDescricao());
        Assertions.assertEquals(Integer.valueOf(1902), DFPais.COREIA_DO_SUL__REPUBLICA_DA.getCodigo());
        Assertions.assertEquals("COSTA DO MARFIM", DFPais.COSTA_DO_MARFIM.getDescricao());
        Assertions.assertEquals(Integer.valueOf(1937), DFPais.COSTA_DO_MARFIM.getCodigo());
        Assertions.assertEquals("CROACIA (REPUBLICA DA)", DFPais.CROACIA_REPUBLICA_DA.getDescricao());
        Assertions.assertEquals(Integer.valueOf(1953), DFPais.CROACIA_REPUBLICA_DA.getCodigo());
        Assertions.assertEquals("COSTA RICA", DFPais.COSTA_RICA.getDescricao());
        Assertions.assertEquals(Integer.valueOf(1961), DFPais.COSTA_RICA.getCodigo());
        Assertions.assertEquals("KUWAIT", DFPais.KUWAIT.getDescricao());
        Assertions.assertEquals(Integer.valueOf(1988), DFPais.KUWAIT.getCodigo());
        Assertions.assertEquals("CUBA", DFPais.CUBA.getDescricao());
        Assertions.assertEquals(Integer.valueOf(1996), DFPais.CUBA.getCodigo());
        Assertions.assertEquals("CURACAO", DFPais.CURACAO.getDescricao());
        Assertions.assertEquals(Integer.valueOf(2003), DFPais.CURACAO.getCodigo());
        Assertions.assertEquals("BENIN", DFPais.BENIN.getDescricao());
        Assertions.assertEquals(Integer.valueOf(2291), DFPais.BENIN.getCodigo());
        Assertions.assertEquals("DINAMARCA", DFPais.DINAMARCA.getDescricao());
        Assertions.assertEquals(Integer.valueOf(2321), DFPais.DINAMARCA.getCodigo());
        Assertions.assertEquals("DOMINICA,ILHA", DFPais.DOMINICA_ILHA.getDescricao());
        Assertions.assertEquals(Integer.valueOf(2356), DFPais.DOMINICA_ILHA.getCodigo());
        Assertions.assertEquals("EQUADOR", DFPais.EQUADOR.getDescricao());
        Assertions.assertEquals(Integer.valueOf(2399), DFPais.EQUADOR.getCodigo());
        Assertions.assertEquals("EGITO", DFPais.EGITO.getDescricao());
        Assertions.assertEquals(Integer.valueOf(2402), DFPais.EGITO.getCodigo());
        Assertions.assertEquals("ERITREIA", DFPais.ERITREIA.getDescricao());
        Assertions.assertEquals(Integer.valueOf(2437), DFPais.ERITREIA.getCodigo());
        Assertions.assertEquals("EMIRADOS ARABES UNIDOS", DFPais.EMIRADOS_ARABES_UNIDOS.getDescricao());
        Assertions.assertEquals(Integer.valueOf(2445), DFPais.EMIRADOS_ARABES_UNIDOS.getCodigo());
        Assertions.assertEquals("ESPANHA", DFPais.ESPANHA.getDescricao());
        Assertions.assertEquals(Integer.valueOf(2453), DFPais.ESPANHA.getCodigo());
        Assertions.assertEquals("ESLOVENIA, REPUBLICA DA", DFPais.ESLOVENIA_REPUBLICA_DA.getDescricao());
        Assertions.assertEquals(Integer.valueOf(2461), DFPais.ESLOVENIA_REPUBLICA_DA.getCodigo());
        Assertions.assertEquals("ESLOVACA, REPUBLICA", DFPais.ESLOVACA_REPUBLICA.getDescricao());
        Assertions.assertEquals(Integer.valueOf(2470), DFPais.ESLOVACA_REPUBLICA.getCodigo());
        Assertions.assertEquals("ESTADOS UNIDOS", DFPais.ESTADOS_UNIDOS.getDescricao());
        Assertions.assertEquals(Integer.valueOf(2496), DFPais.ESTADOS_UNIDOS.getCodigo());
        Assertions.assertEquals("ESTONIA, REPUBLICA DA", DFPais.ESTONIA_REPUBLICA_DA.getDescricao());
        Assertions.assertEquals(Integer.valueOf(2518), DFPais.ESTONIA_REPUBLICA_DA.getCodigo());
        Assertions.assertEquals("ETIOPIA", DFPais.ETIOPIA.getDescricao());
        Assertions.assertEquals(Integer.valueOf(2534), DFPais.ETIOPIA.getCodigo());
        Assertions.assertEquals("FALKLAND (ILHAS MALVINAS)", DFPais.FALKLAND_ILHAS_MALVINAS.getDescricao());
        Assertions.assertEquals(Integer.valueOf(2550), DFPais.FALKLAND_ILHAS_MALVINAS.getCodigo());
        Assertions.assertEquals("FEROE, ILHAS", DFPais.FEROE_ILHAS.getDescricao());
        Assertions.assertEquals(Integer.valueOf(2593), DFPais.FEROE_ILHAS.getCodigo());
        Assertions.assertEquals("FILIPINAS", DFPais.FILIPINAS.getDescricao());
        Assertions.assertEquals(Integer.valueOf(2674), DFPais.FILIPINAS.getCodigo());
        Assertions.assertEquals("FINLANDIA", DFPais.FINLANDIA.getDescricao());
        Assertions.assertEquals(Integer.valueOf(2712), DFPais.FINLANDIA.getCodigo());
        Assertions.assertEquals("FRANCA", DFPais.FRANCA.getDescricao());
        Assertions.assertEquals(Integer.valueOf(2755), DFPais.FRANCA.getCodigo());
        Assertions.assertEquals("GABAO", DFPais.GABAO.getDescricao());
        Assertions.assertEquals(Integer.valueOf(2810), DFPais.GABAO.getCodigo());
        Assertions.assertEquals("GAMBIA", DFPais.GAMBIA.getDescricao());
        Assertions.assertEquals(Integer.valueOf(2852), DFPais.GAMBIA.getCodigo());
        Assertions.assertEquals("GANA", DFPais.GANA.getDescricao());
        Assertions.assertEquals(Integer.valueOf(2895), DFPais.GANA.getCodigo());
        Assertions.assertEquals("GEORGIA, REPUBLICA DA", DFPais.GEORGIA_REPUBLICA_DA.getDescricao());
        Assertions.assertEquals(Integer.valueOf(2917), DFPais.GEORGIA_REPUBLICA_DA.getCodigo());
        Assertions.assertEquals("ILHAS GEORGIA DO SUL E SANDWICH DO SUL", DFPais.ILHAS_GEORGIA_DO_SUL_E_SANDWICH_DO_SUL.getDescricao());
        Assertions.assertEquals(Integer.valueOf(2925), DFPais.ILHAS_GEORGIA_DO_SUL_E_SANDWICH_DO_SUL.getCodigo());
        Assertions.assertEquals("GIBRALTAR", DFPais.GIBRALTAR.getDescricao());
        Assertions.assertEquals(Integer.valueOf(2933), DFPais.GIBRALTAR.getCodigo());
        Assertions.assertEquals("GRANADA", DFPais.GRANADA.getDescricao());
        Assertions.assertEquals(Integer.valueOf(2976), DFPais.GRANADA.getCodigo());
        Assertions.assertEquals("GRECIA", DFPais.GRECIA.getDescricao());
        Assertions.assertEquals(Integer.valueOf(3018), DFPais.GRECIA.getCodigo());
        Assertions.assertEquals("GROENLANDIA", DFPais.GROENLANDIA.getDescricao());
        Assertions.assertEquals(Integer.valueOf(3050), DFPais.GROENLANDIA.getCodigo());
        Assertions.assertEquals("GUADALUPE", DFPais.GUADALUPE.getDescricao());
        Assertions.assertEquals(Integer.valueOf(3093), DFPais.GUADALUPE.getCodigo());
        Assertions.assertEquals("GUAM", DFPais.GUAM.getDescricao());
        Assertions.assertEquals(Integer.valueOf(3131), DFPais.GUAM.getCodigo());
        Assertions.assertEquals("GUATEMALA", DFPais.GUATEMALA.getDescricao());
        Assertions.assertEquals(Integer.valueOf(3174), DFPais.GUATEMALA.getCodigo());
        Assertions.assertEquals("GUERNSEY, ILHA DO CANAL (INCLUI ALDERNEY E SARK)", DFPais.GUERNSEY_ILHA_DO_CANAL_INCLUI_ALDERNEY_E_SARK.getDescricao());
        Assertions.assertEquals(Integer.valueOf(3212), DFPais.GUERNSEY_ILHA_DO_CANAL_INCLUI_ALDERNEY_E_SARK.getCodigo());
        Assertions.assertEquals("GUIANA FRANCESA", DFPais.GUIANA_FRANCESA.getDescricao());
        Assertions.assertEquals(Integer.valueOf(3255), DFPais.GUIANA_FRANCESA.getCodigo());
        Assertions.assertEquals("GUINE", DFPais.GUINE.getDescricao());
        Assertions.assertEquals(Integer.valueOf(3298), DFPais.GUINE.getCodigo());
        Assertions.assertEquals("GUINE-EQUATORIAL", DFPais.GUINE_EQUATORIAL.getDescricao());
        Assertions.assertEquals(Integer.valueOf(3310), DFPais.GUINE_EQUATORIAL.getCodigo());
        Assertions.assertEquals("GUINE-BISSAU", DFPais.GUINE_BISSAU.getDescricao());
        Assertions.assertEquals(Integer.valueOf(3344), DFPais.GUINE_BISSAU.getCodigo());
        Assertions.assertEquals("GUIANA", DFPais.GUIANA.getDescricao());
        Assertions.assertEquals(Integer.valueOf(3379), DFPais.GUIANA.getCodigo());
        Assertions.assertEquals("HAITI", DFPais.HAITI.getDescricao());
        Assertions.assertEquals(Integer.valueOf(3417), DFPais.HAITI.getCodigo());
        Assertions.assertEquals("ILHA HEARD E ILHAS MCDONALD", DFPais.ILHA_HEARD_E_ILHAS_MCDONALD.getDescricao());
        Assertions.assertEquals(Integer.valueOf(3433), DFPais.ILHA_HEARD_E_ILHAS_MCDONALD.getCodigo());
        Assertions.assertEquals("HONDURAS", DFPais.HONDURAS.getDescricao());
        Assertions.assertEquals(Integer.valueOf(3450), DFPais.HONDURAS.getCodigo());
        Assertions.assertEquals("HONG KONG", DFPais.HONG_KONG.getDescricao());
        Assertions.assertEquals(Integer.valueOf(3514), DFPais.HONG_KONG.getCodigo());
        Assertions.assertEquals("HUNGRIA, REPUBLICA DA", DFPais.HUNGRIA_REPUBLICA_DA.getDescricao());
        Assertions.assertEquals(Integer.valueOf(3557), DFPais.HUNGRIA_REPUBLICA_DA.getCodigo());
        Assertions.assertEquals("IEMEN", DFPais.IEMEN.getDescricao());
        Assertions.assertEquals(Integer.valueOf(3573), DFPais.IEMEN.getCodigo());
        Assertions.assertEquals("MAN, ILHA DE", DFPais.MAN_ILHA_DE.getDescricao());
        Assertions.assertEquals(Integer.valueOf(3595), DFPais.MAN_ILHA_DE.getCodigo());
        Assertions.assertEquals("INDIA", DFPais.INDIA.getDescricao());
        Assertions.assertEquals(Integer.valueOf(3611), DFPais.INDIA.getCodigo());
        Assertions.assertEquals("INDONESIA", DFPais.INDONESIA.getDescricao());
        Assertions.assertEquals(Integer.valueOf(3654), DFPais.INDONESIA.getCodigo());
        Assertions.assertEquals("IRAQUE", DFPais.IRAQUE.getDescricao());
        Assertions.assertEquals(Integer.valueOf(3697), DFPais.IRAQUE.getCodigo());
        Assertions.assertEquals("IRA, REPUBLICA ISLAMICA DO", DFPais.IRA_REPUBLICA_ISLAMICA_DO.getDescricao());
        Assertions.assertEquals(Integer.valueOf(3727), DFPais.IRA_REPUBLICA_ISLAMICA_DO.getCodigo());
        Assertions.assertEquals("IRLANDA", DFPais.IRLANDA.getDescricao());
        Assertions.assertEquals(Integer.valueOf(3751), DFPais.IRLANDA.getCodigo());
        Assertions.assertEquals("ISLANDIA", DFPais.ISLANDIA.getDescricao());
        Assertions.assertEquals(Integer.valueOf(3794), DFPais.ISLANDIA.getCodigo());
        Assertions.assertEquals("ISRAEL", DFPais.ISRAEL.getDescricao());
        Assertions.assertEquals(Integer.valueOf(3832), DFPais.ISRAEL.getCodigo());
        Assertions.assertEquals("ITALIA", DFPais.ITALIA.getDescricao());
        Assertions.assertEquals(Integer.valueOf(3867), DFPais.ITALIA.getCodigo());
        Assertions.assertEquals("JAMAICA", DFPais.JAMAICA.getDescricao());
        Assertions.assertEquals(Integer.valueOf(3913), DFPais.JAMAICA.getCodigo());
        Assertions.assertEquals("JERSEY, ILHA DO CANAL", DFPais.JERSEY_ILHA_DO_CANAL.getDescricao());
        Assertions.assertEquals(Integer.valueOf(3930), DFPais.JERSEY_ILHA_DO_CANAL.getCodigo());
        Assertions.assertEquals("JOHNSTON, ILHAS", DFPais.JOHNSTON_ILHAS.getDescricao());
        Assertions.assertEquals(Integer.valueOf(3964), DFPais.JOHNSTON_ILHAS.getCodigo());
        Assertions.assertEquals("JAPAO", DFPais.JAPAO.getDescricao());
        Assertions.assertEquals(Integer.valueOf(3999), DFPais.JAPAO.getCodigo());
        Assertions.assertEquals("JORDANIA", DFPais.JORDANIA.getDescricao());
        Assertions.assertEquals(Integer.valueOf(4030), DFPais.JORDANIA.getCodigo());
        Assertions.assertEquals("KIRIBATI", DFPais.KIRIBATI.getDescricao());
        Assertions.assertEquals(Integer.valueOf(4111), DFPais.KIRIBATI.getCodigo());
        Assertions.assertEquals("LAOS, REP.POP.DEMOCR.DO", DFPais.LAOS_REP_POP_DEMOCR_DO.getDescricao());
        Assertions.assertEquals(Integer.valueOf(4200), DFPais.LAOS_REP_POP_DEMOCR_DO.getCodigo());
        Assertions.assertEquals("LEBUAN,ILHAS", DFPais.LEBUAN_ILHAS.getDescricao());
        Assertions.assertEquals(Integer.valueOf(4235), DFPais.LEBUAN_ILHAS.getCodigo());
        Assertions.assertEquals("LESOTO", DFPais.LESOTO.getDescricao());
        Assertions.assertEquals(Integer.valueOf(4260), DFPais.LESOTO.getCodigo());
        Assertions.assertEquals("LETONIA, REPUBLICA DA", DFPais.LETONIA_REPUBLICA_DA.getDescricao());
        Assertions.assertEquals(Integer.valueOf(4278), DFPais.LETONIA_REPUBLICA_DA.getCodigo());
        Assertions.assertEquals("LIBANO", DFPais.LIBANO.getDescricao());
        Assertions.assertEquals(Integer.valueOf(4316), DFPais.LIBANO.getCodigo());
        Assertions.assertEquals("LIBERIA", DFPais.LIBERIA.getDescricao());
        Assertions.assertEquals(Integer.valueOf(4340), DFPais.LIBERIA.getCodigo());
        Assertions.assertEquals("LIBIA", DFPais.LIBIA.getDescricao());
        Assertions.assertEquals(Integer.valueOf(4383), DFPais.LIBIA.getCodigo());
        Assertions.assertEquals("LIECHTENSTEIN", DFPais.LIECHTENSTEIN.getDescricao());
        Assertions.assertEquals(Integer.valueOf(4405), DFPais.LIECHTENSTEIN.getCodigo());
        Assertions.assertEquals("LITUANIA, REPUBLICA DA", DFPais.LITUANIA_REPUBLICA_DA.getDescricao());
        Assertions.assertEquals(Integer.valueOf(4421), DFPais.LITUANIA_REPUBLICA_DA.getCodigo());
        Assertions.assertEquals("LUXEMBURGO", DFPais.LUXEMBURGO.getDescricao());
        Assertions.assertEquals(Integer.valueOf(4456), DFPais.LUXEMBURGO.getCodigo());
        Assertions.assertEquals("MACAU", DFPais.MACAU.getDescricao());
        Assertions.assertEquals(Integer.valueOf(4472), DFPais.MACAU.getCodigo());
        Assertions.assertEquals("MACEDONIA, ANT.REP.IUGOSLAVA", DFPais.MACEDONIA_ANT_REP_IUGOSLAVA.getDescricao());
        Assertions.assertEquals(Integer.valueOf(4499), DFPais.MACEDONIA_ANT_REP_IUGOSLAVA.getCodigo());
        Assertions.assertEquals("MADAGASCAR", DFPais.MADAGASCAR.getDescricao());
        Assertions.assertEquals(Integer.valueOf(4502), DFPais.MADAGASCAR.getCodigo());
        Assertions.assertEquals("MADEIRA, ILHA DA", DFPais.MADEIRA_ILHA_DA.getDescricao());
        Assertions.assertEquals(Integer.valueOf(4525), DFPais.MADEIRA_ILHA_DA.getCodigo());
        Assertions.assertEquals("MALASIA", DFPais.MALASIA.getDescricao());
        Assertions.assertEquals(Integer.valueOf(4553), DFPais.MALASIA.getCodigo());
        Assertions.assertEquals("MALAVI", DFPais.MALAVI.getDescricao());
        Assertions.assertEquals(Integer.valueOf(4588), DFPais.MALAVI.getCodigo());
        Assertions.assertEquals("MALDIVAS", DFPais.MALDIVAS.getDescricao());
        Assertions.assertEquals(Integer.valueOf(4618), DFPais.MALDIVAS.getCodigo());
        Assertions.assertEquals("MALI", DFPais.MALI.getDescricao());
        Assertions.assertEquals(Integer.valueOf(4642), DFPais.MALI.getCodigo());
        Assertions.assertEquals("MALTA", DFPais.MALTA.getDescricao());
        Assertions.assertEquals(Integer.valueOf(4677), DFPais.MALTA.getCodigo());
        Assertions.assertEquals("MARIANAS DO NORTE", DFPais.MARIANAS_DO_NORTE.getDescricao());
        Assertions.assertEquals(Integer.valueOf(4723), DFPais.MARIANAS_DO_NORTE.getCodigo());
        Assertions.assertEquals("MARROCOS", DFPais.MARROCOS.getDescricao());
        Assertions.assertEquals(Integer.valueOf(4740), DFPais.MARROCOS.getCodigo());
        Assertions.assertEquals("MARSHALL,ILHAS", DFPais.MARSHALL_ILHAS.getDescricao());
        Assertions.assertEquals(Integer.valueOf(4766), DFPais.MARSHALL_ILHAS.getCodigo());
        Assertions.assertEquals("MARTINICA", DFPais.MARTINICA.getDescricao());
        Assertions.assertEquals(Integer.valueOf(4774), DFPais.MARTINICA.getCodigo());
        Assertions.assertEquals("MAURICIO", DFPais.MAURICIO.getDescricao());
        Assertions.assertEquals(Integer.valueOf(4855), DFPais.MAURICIO.getCodigo());
        Assertions.assertEquals("MAURITANIA", DFPais.MAURITANIA.getDescricao());
        Assertions.assertEquals(Integer.valueOf(4880), DFPais.MAURITANIA.getCodigo());
        Assertions.assertEquals("MAYOTTE (ILHAS FRANCESAS)", DFPais.MAYOTTE_ILHAS_FRANCESAS.getDescricao());
        Assertions.assertEquals(Integer.valueOf(4898), DFPais.MAYOTTE_ILHAS_FRANCESAS.getCodigo());
        Assertions.assertEquals("MIDWAY, ILHAS", DFPais.MIDWAY_ILHAS.getDescricao());
        Assertions.assertEquals(Integer.valueOf(4901), DFPais.MIDWAY_ILHAS.getCodigo());
        Assertions.assertEquals("MEXICO", DFPais.MEXICO.getDescricao());
        Assertions.assertEquals(Integer.valueOf(4936), DFPais.MEXICO.getCodigo());
        Assertions.assertEquals("MOLDAVIA, REPUBLICA DA", DFPais.MOLDAVIA_REPUBLICA_DA.getDescricao());
        Assertions.assertEquals(Integer.valueOf(4944), DFPais.MOLDAVIA_REPUBLICA_DA.getCodigo());
        Assertions.assertEquals("MONACO", DFPais.MONACO.getDescricao());
        Assertions.assertEquals(Integer.valueOf(4952), DFPais.MONACO.getCodigo());
        Assertions.assertEquals("MONGOLIA", DFPais.MONGOLIA.getDescricao());
        Assertions.assertEquals(Integer.valueOf(4979), DFPais.MONGOLIA.getCodigo());
        Assertions.assertEquals("MONTENEGRO", DFPais.MONTENEGRO.getDescricao());
        Assertions.assertEquals(Integer.valueOf(4985), DFPais.MONTENEGRO.getCodigo());
        Assertions.assertEquals("MICRONESIA", DFPais.MICRONESIA.getDescricao());
        Assertions.assertEquals(Integer.valueOf(4995), DFPais.MICRONESIA.getCodigo());
        Assertions.assertEquals("MONTSERRAT,ILHAS", DFPais.MONTSERRAT_ILHAS.getDescricao());
        Assertions.assertEquals(Integer.valueOf(5010), DFPais.MONTSERRAT_ILHAS.getCodigo());
        Assertions.assertEquals("MOCAMBIQUE", DFPais.MOCAMBIQUE.getDescricao());
        Assertions.assertEquals(Integer.valueOf(5053), DFPais.MOCAMBIQUE.getCodigo());
        Assertions.assertEquals("NAMIBIA", DFPais.NAMIBIA.getDescricao());
        Assertions.assertEquals(Integer.valueOf(5070), DFPais.NAMIBIA.getCodigo());
        Assertions.assertEquals("NAURU", DFPais.NAURU.getDescricao());
        Assertions.assertEquals(Integer.valueOf(5088), DFPais.NAURU.getCodigo());
        Assertions.assertEquals("CHRISTMAS,ILHA (NAVIDAD)", DFPais.CHRISTMAS_ILHA_NAVIDAD.getDescricao());
        Assertions.assertEquals(Integer.valueOf(5118), DFPais.CHRISTMAS_ILHA_NAVIDAD.getCodigo());
        Assertions.assertEquals("NEPAL", DFPais.NEPAL.getDescricao());
        Assertions.assertEquals(Integer.valueOf(5177), DFPais.NEPAL.getCodigo());
        Assertions.assertEquals("NICARAGUA", DFPais.NICARAGUA.getDescricao());
        Assertions.assertEquals(Integer.valueOf(5215), DFPais.NICARAGUA.getCodigo());
        Assertions.assertEquals("NIGER", DFPais.NIGER.getDescricao());
        Assertions.assertEquals(Integer.valueOf(5258), DFPais.NIGER.getCodigo());
        Assertions.assertEquals("NIGERIA", DFPais.NIGERIA.getDescricao());
        Assertions.assertEquals(Integer.valueOf(5282), DFPais.NIGERIA.getCodigo());
        Assertions.assertEquals("NIUE,ILHA", DFPais.NIUE_ILHA.getDescricao());
        Assertions.assertEquals(Integer.valueOf(5312), DFPais.NIUE_ILHA.getCodigo());
        Assertions.assertEquals("NORFOLK,ILHA", DFPais.NORFOLK_ILHA.getDescricao());
        Assertions.assertEquals(Integer.valueOf(5355), DFPais.NORFOLK_ILHA.getCodigo());
        Assertions.assertEquals("NORUEGA", DFPais.NORUEGA.getDescricao());
        Assertions.assertEquals(Integer.valueOf(5380), DFPais.NORUEGA.getCodigo());
        Assertions.assertEquals("NOVA CALEDONIA", DFPais.NOVA_CALEDONIA.getDescricao());
        Assertions.assertEquals(Integer.valueOf(5428), DFPais.NOVA_CALEDONIA.getCodigo());
        Assertions.assertEquals("PAPUA NOVA GUINE", DFPais.PAPUA_NOVA_GUINE.getDescricao());
        Assertions.assertEquals(Integer.valueOf(5452), DFPais.PAPUA_NOVA_GUINE.getCodigo());
        Assertions.assertEquals("NOVA ZELANDIA", DFPais.NOVA_ZELANDIA.getDescricao());
        Assertions.assertEquals(Integer.valueOf(5487), DFPais.NOVA_ZELANDIA.getCodigo());
        Assertions.assertEquals("VANUATU", DFPais.VANUATU.getDescricao());
        Assertions.assertEquals(Integer.valueOf(5517), DFPais.VANUATU.getCodigo());
        Assertions.assertEquals("OMA", DFPais.OMA.getDescricao());
        Assertions.assertEquals(Integer.valueOf(5568), DFPais.OMA.getCodigo());
        Assertions.assertEquals("PACIFICO,ILHAS DO (POSSESSAO DOS EUA)", DFPais.PACIFICO_ILHAS_DO_POSSESSAO_DOS_EUA.getDescricao());
        Assertions.assertEquals(Integer.valueOf(5665), DFPais.PACIFICO_ILHAS_DO_POSSESSAO_DOS_EUA.getCodigo());
        Assertions.assertEquals("PAISES BAIXOS (HOLANDA)", DFPais.PAISES_BAIXOS_HOLANDA.getDescricao());
        Assertions.assertEquals(Integer.valueOf(5738), DFPais.PAISES_BAIXOS_HOLANDA.getCodigo());
        Assertions.assertEquals("PALAU", DFPais.PALAU.getDescricao());
        Assertions.assertEquals(Integer.valueOf(5754), DFPais.PALAU.getCodigo());
        Assertions.assertEquals("PAQUISTAO", DFPais.PAQUISTAO.getDescricao());
        Assertions.assertEquals(Integer.valueOf(5762), DFPais.PAQUISTAO.getCodigo());
        Assertions.assertEquals("PALESTINA", DFPais.PALESTINA.getDescricao());
        Assertions.assertEquals(Integer.valueOf(5780), DFPais.PALESTINA.getCodigo());
        Assertions.assertEquals("PANAMA", DFPais.PANAMA.getDescricao());
        Assertions.assertEquals(Integer.valueOf(5800), DFPais.PANAMA.getCodigo());
        Assertions.assertEquals("PARAGUAI", DFPais.PARAGUAI.getDescricao());
        Assertions.assertEquals(Integer.valueOf(5860), DFPais.PARAGUAI.getCodigo());
        Assertions.assertEquals("PERU", DFPais.PERU.getDescricao());
        Assertions.assertEquals(Integer.valueOf(5894), DFPais.PERU.getCodigo());
        Assertions.assertEquals("PITCAIRN,ILHA", DFPais.PITCAIRN_ILHA.getDescricao());
        Assertions.assertEquals(Integer.valueOf(5932), DFPais.PITCAIRN_ILHA.getCodigo());
        Assertions.assertEquals("POLINESIA FRANCESA", DFPais.POLINESIA_FRANCESA.getDescricao());
        Assertions.assertEquals(Integer.valueOf(5991), DFPais.POLINESIA_FRANCESA.getCodigo());
        Assertions.assertEquals("POLONIA, REPUBLICA DA", DFPais.POLONIA_REPUBLICA_DA.getDescricao());
        Assertions.assertEquals(Integer.valueOf(6033), DFPais.POLONIA_REPUBLICA_DA.getCodigo());
        Assertions.assertEquals("PORTUGAL", DFPais.PORTUGAL.getDescricao());
        Assertions.assertEquals(Integer.valueOf(6076), DFPais.PORTUGAL.getCodigo());
        Assertions.assertEquals("PORTO RICO", DFPais.PORTO_RICO.getDescricao());
        Assertions.assertEquals(Integer.valueOf(6114), DFPais.PORTO_RICO.getCodigo());
        Assertions.assertEquals("QUENIA", DFPais.QUENIA.getDescricao());
        Assertions.assertEquals(Integer.valueOf(6238), DFPais.QUENIA.getCodigo());
        Assertions.assertEquals("QUIRGUIZ, REPUBLICA", DFPais.QUIRGUIZ_REPUBLICA.getDescricao());
        Assertions.assertEquals(Integer.valueOf(6254), DFPais.QUIRGUIZ_REPUBLICA.getCodigo());
        Assertions.assertEquals("REINO UNIDO", DFPais.REINO_UNIDO.getDescricao());
        Assertions.assertEquals(Integer.valueOf(6289), DFPais.REINO_UNIDO.getCodigo());
        Assertions.assertEquals("REPUBLICA CENTRO-AFRICANA", DFPais.REPUBLICA_CENTRO_AFRICANA.getDescricao());
        Assertions.assertEquals(Integer.valueOf(6408), DFPais.REPUBLICA_CENTRO_AFRICANA.getCodigo());
        Assertions.assertEquals("REPUBLICA DOMINICANA", DFPais.REPUBLICA_DOMINICANA.getDescricao());
        Assertions.assertEquals(Integer.valueOf(6475), DFPais.REPUBLICA_DOMINICANA.getCodigo());
        Assertions.assertEquals("REUNIAO, ILHA", DFPais.REUNIAO_ILHA.getDescricao());
        Assertions.assertEquals(Integer.valueOf(6602), DFPais.REUNIAO_ILHA.getCodigo());
        Assertions.assertEquals("ZIMBABUE", DFPais.ZIMBABUE.getDescricao());
        Assertions.assertEquals(Integer.valueOf(6653), DFPais.ZIMBABUE.getCodigo());
        Assertions.assertEquals("ROMENIA", DFPais.ROMENIA.getDescricao());
        Assertions.assertEquals(Integer.valueOf(6700), DFPais.ROMENIA.getCodigo());
        Assertions.assertEquals("RUANDA", DFPais.RUANDA.getDescricao());
        Assertions.assertEquals(Integer.valueOf(6750), DFPais.RUANDA.getCodigo());
        Assertions.assertEquals("RUSSIA, FEDERACAO DA", DFPais.RUSSIA_FEDERACAO_DA.getDescricao());
        Assertions.assertEquals(Integer.valueOf(6769), DFPais.RUSSIA_FEDERACAO_DA.getCodigo());
        Assertions.assertEquals("SALOMAO, ILHAS", DFPais.SALOMAO_ILHAS.getDescricao());
        Assertions.assertEquals(Integer.valueOf(6777), DFPais.SALOMAO_ILHAS.getCodigo());
        Assertions.assertEquals("SAARA OCIDENTAL", DFPais.SAARA_OCIDENTAL.getDescricao());
        Assertions.assertEquals(Integer.valueOf(6858), DFPais.SAARA_OCIDENTAL.getCodigo());
        Assertions.assertEquals("EL SALVADOR", DFPais.EL_SALVADOR.getDescricao());
        Assertions.assertEquals(Integer.valueOf(6874), DFPais.EL_SALVADOR.getCodigo());
        Assertions.assertEquals("SAMOA", DFPais.SAMOA.getDescricao());
        Assertions.assertEquals(Integer.valueOf(6904), DFPais.SAMOA.getCodigo());
        Assertions.assertEquals("SAMOA AMERICANA", DFPais.SAMOA_AMERICANA.getDescricao());
        Assertions.assertEquals(Integer.valueOf(6912), DFPais.SAMOA_AMERICANA.getCodigo());
        Assertions.assertEquals("SAO CRISTOVAO E NEVES,ILHAS", DFPais.SAO_CRISTOVAO_E_NEVES_ILHAS.getDescricao());
        Assertions.assertEquals(Integer.valueOf(6955), DFPais.SAO_CRISTOVAO_E_NEVES_ILHAS.getCodigo());
        Assertions.assertEquals("SAO BARTOLOMEU", DFPais.SAO_BARTOLOMEU.getDescricao());
        Assertions.assertEquals(Integer.valueOf(6939), DFPais.SAO_BARTOLOMEU.getCodigo());
        Assertions.assertEquals("SAN MARINO", DFPais.SAN_MARINO.getDescricao());
        Assertions.assertEquals(Integer.valueOf(6971), DFPais.SAN_MARINO.getCodigo());
        Assertions.assertEquals("ILHAS DE SAO MARTINHO (PARTE FRANCESA)", DFPais.ILHAS_DE_SAO_MARTINHO_PARTE_FRANCESA.getDescricao());
        Assertions.assertEquals(Integer.valueOf(6980), DFPais.ILHAS_DE_SAO_MARTINHO_PARTE_FRANCESA.getCodigo());
        Assertions.assertEquals("SAO MARTINHO, ILHA DE (PARTE FRANCESA)", DFPais.SAO_MARTINHO_ILHA_DE_PARTE_FRANCESA.getDescricao());
        Assertions.assertEquals(Integer.valueOf(6998), DFPais.SAO_MARTINHO_ILHA_DE_PARTE_FRANCESA.getCodigo());
        Assertions.assertEquals("SAO PEDRO E MIQUELON", DFPais.SAO_PEDRO_E_MIQUELON.getDescricao());
        Assertions.assertEquals(Integer.valueOf(7005), DFPais.SAO_PEDRO_E_MIQUELON.getCodigo());
        Assertions.assertEquals("SAO VICENTE E GRANADINAS", DFPais.SAO_VICENTE_E_GRANADINAS.getDescricao());
        Assertions.assertEquals(Integer.valueOf(7056), DFPais.SAO_VICENTE_E_GRANADINAS.getCodigo());
        Assertions.assertEquals("SANTA HELENA", DFPais.SANTA_HELENA.getDescricao());
        Assertions.assertEquals(Integer.valueOf(7102), DFPais.SANTA_HELENA.getCodigo());
        Assertions.assertEquals("SANTA LUCIA", DFPais.SANTA_LUCIA.getDescricao());
        Assertions.assertEquals(Integer.valueOf(7153), DFPais.SANTA_LUCIA.getCodigo());
        Assertions.assertEquals("SAO TOME E PRINCIPE, ILHAS", DFPais.SAO_TOME_E_PRINCIPE_ILHAS.getDescricao());
        Assertions.assertEquals(Integer.valueOf(7200), DFPais.SAO_TOME_E_PRINCIPE_ILHAS.getCodigo());
        Assertions.assertEquals("SENEGAL", DFPais.SENEGAL.getDescricao());
        Assertions.assertEquals(Integer.valueOf(7285), DFPais.SENEGAL.getCodigo());
        Assertions.assertEquals("SEYCHELLES", DFPais.SEYCHELLES.getDescricao());
        Assertions.assertEquals(Integer.valueOf(7315), DFPais.SEYCHELLES.getCodigo());
        Assertions.assertEquals("SERRA LEOA", DFPais.SERRA_LEOA.getDescricao());
        Assertions.assertEquals(Integer.valueOf(7358), DFPais.SERRA_LEOA.getCodigo());
        Assertions.assertEquals("SERVIA", DFPais.SERVIA.getDescricao());
        Assertions.assertEquals(Integer.valueOf(7370), DFPais.SERVIA.getCodigo());
        Assertions.assertEquals("CINGAPURA", DFPais.CINGAPURA.getDescricao());
        Assertions.assertEquals(Integer.valueOf(7412), DFPais.CINGAPURA.getCodigo());
        Assertions.assertEquals("SIRIA, REPUBLICA ARABE DA", DFPais.SIRIA_REPUBLICA_ARABE_DA.getDescricao());
        Assertions.assertEquals(Integer.valueOf(7447), DFPais.SIRIA_REPUBLICA_ARABE_DA.getCodigo());
        Assertions.assertEquals("SOMALIA", DFPais.SOMALIA.getDescricao());
        Assertions.assertEquals(Integer.valueOf(7480), DFPais.SOMALIA.getCodigo());
        Assertions.assertEquals("SRI LANKA", DFPais.SRI_LANKA.getDescricao());
        Assertions.assertEquals(Integer.valueOf(7501), DFPais.SRI_LANKA.getCodigo());
        Assertions.assertEquals("SUAZILANDIA", DFPais.SUAZILANDIA.getDescricao());
        Assertions.assertEquals(Integer.valueOf(7544), DFPais.SUAZILANDIA.getCodigo());
        Assertions.assertEquals("SVALBARD E JAN MAYERN", DFPais.SVALBARD_E_JAN_MAYERN.getDescricao());
        Assertions.assertEquals(Integer.valueOf(7552), DFPais.SVALBARD_E_JAN_MAYERN.getCodigo());
        Assertions.assertEquals("AFRICA DO SUL", DFPais.AFRICA_DO_SUL.getDescricao());
        Assertions.assertEquals(Integer.valueOf(7560), DFPais.AFRICA_DO_SUL.getCodigo());
        Assertions.assertEquals("SUDAO", DFPais.SUDAO.getDescricao());
        Assertions.assertEquals(Integer.valueOf(7595), DFPais.SUDAO.getCodigo());
        Assertions.assertEquals("SUDÃO DO SUL", DFPais.SUD_O_DO_SUL.getDescricao());
        Assertions.assertEquals(Integer.valueOf(7600), DFPais.SUD_O_DO_SUL.getCodigo());
        Assertions.assertEquals("SUECIA", DFPais.SUECIA.getDescricao());
        Assertions.assertEquals(Integer.valueOf(7641), DFPais.SUECIA.getCodigo());
        Assertions.assertEquals("SUICA", DFPais.SUICA.getDescricao());
        Assertions.assertEquals(Integer.valueOf(7676), DFPais.SUICA.getCodigo());
        Assertions.assertEquals("SURINAME", DFPais.SURINAME.getDescricao());
        Assertions.assertEquals(Integer.valueOf(7706), DFPais.SURINAME.getCodigo());
        Assertions.assertEquals("TADJIQUISTAO, REPUBLICA DO", DFPais.TADJIQUISTAO_REPUBLICA_DO.getDescricao());
        Assertions.assertEquals(Integer.valueOf(7722), DFPais.TADJIQUISTAO_REPUBLICA_DO.getCodigo());
        Assertions.assertEquals("TAILANDIA", DFPais.TAILANDIA.getDescricao());
        Assertions.assertEquals(Integer.valueOf(7765), DFPais.TAILANDIA.getCodigo());
        Assertions.assertEquals("TANZANIA, REP.UNIDA DA", DFPais.TANZANIA_REP_UNIDA_DA.getDescricao());
        Assertions.assertEquals(Integer.valueOf(7803), DFPais.TANZANIA_REP_UNIDA_DA.getCodigo());
        Assertions.assertEquals("TERRAS AUSTRAIS E ANTARTICAS FRANCESAS", DFPais.TERRAS_AUSTRAIS_E_ANTARTICAS_FRANCESAS.getDescricao());
        Assertions.assertEquals(Integer.valueOf(7811), DFPais.TERRAS_AUSTRAIS_E_ANTARTICAS_FRANCESAS.getCodigo());
        Assertions.assertEquals("TERRITORIO BRIT.OC.INDICO", DFPais.TERRITORIO_BRIT_OC_INDICO.getDescricao());
        Assertions.assertEquals(Integer.valueOf(7820), DFPais.TERRITORIO_BRIT_OC_INDICO.getCodigo());
        Assertions.assertEquals("DJIBUTI", DFPais.DJIBUTI.getDescricao());
        Assertions.assertEquals(Integer.valueOf(7838), DFPais.DJIBUTI.getCodigo());
        Assertions.assertEquals("CHADE", DFPais.CHADE.getDescricao());
        Assertions.assertEquals(Integer.valueOf(7889), DFPais.CHADE.getCodigo());
        Assertions.assertEquals("TCHECA, REPUBLICA", DFPais.TCHECA_REPUBLICA.getDescricao());
        Assertions.assertEquals(Integer.valueOf(7919), DFPais.TCHECA_REPUBLICA.getCodigo());
        Assertions.assertEquals("TIMOR LESTE", DFPais.TIMOR_LESTE.getDescricao());
        Assertions.assertEquals(Integer.valueOf(7951), DFPais.TIMOR_LESTE.getCodigo());
        Assertions.assertEquals("TOGO", DFPais.TOGO.getDescricao());
        Assertions.assertEquals(Integer.valueOf(8001), DFPais.TOGO.getCodigo());
        Assertions.assertEquals("TOQUELAU,ILHAS", DFPais.TOQUELAU_ILHAS.getDescricao());
        Assertions.assertEquals(Integer.valueOf(8052), DFPais.TOQUELAU_ILHAS.getCodigo());
        Assertions.assertEquals("TONGA", DFPais.TONGA.getDescricao());
        Assertions.assertEquals(Integer.valueOf(8109), DFPais.TONGA.getCodigo());
        Assertions.assertEquals("TRINIDAD E TOBAGO", DFPais.TRINIDAD_E_TOBAGO.getDescricao());
        Assertions.assertEquals(Integer.valueOf(8150), DFPais.TRINIDAD_E_TOBAGO.getCodigo());
        Assertions.assertEquals("TUNISIA", DFPais.TUNISIA.getDescricao());
        Assertions.assertEquals(Integer.valueOf(8206), DFPais.TUNISIA.getCodigo());
        Assertions.assertEquals("TURCAS E CAICOS,ILHAS", DFPais.TURCAS_E_CAICOS_ILHAS.getDescricao());
        Assertions.assertEquals(Integer.valueOf(8230), DFPais.TURCAS_E_CAICOS_ILHAS.getCodigo());
        Assertions.assertEquals("TURCOMENISTAO, REPUBLICA DO", DFPais.TURCOMENISTAO_REPUBLICA_DO.getDescricao());
        Assertions.assertEquals(Integer.valueOf(8249), DFPais.TURCOMENISTAO_REPUBLICA_DO.getCodigo());
        Assertions.assertEquals("TURQUIA", DFPais.TURQUIA.getDescricao());
        Assertions.assertEquals(Integer.valueOf(8273), DFPais.TURQUIA.getCodigo());
        Assertions.assertEquals("TUVALU", DFPais.TUVALU.getDescricao());
        Assertions.assertEquals(Integer.valueOf(8281), DFPais.TUVALU.getCodigo());
        Assertions.assertEquals("UCRANIA", DFPais.UCRANIA.getDescricao());
        Assertions.assertEquals(Integer.valueOf(8311), DFPais.UCRANIA.getCodigo());
        Assertions.assertEquals("UGANDA", DFPais.UGANDA.getDescricao());
        Assertions.assertEquals(Integer.valueOf(8338), DFPais.UGANDA.getCodigo());
        Assertions.assertEquals("URUGUAI", DFPais.URUGUAI.getDescricao());
        Assertions.assertEquals(Integer.valueOf(8451), DFPais.URUGUAI.getCodigo());
        Assertions.assertEquals("UZBEQUISTAO, REPUBLICA DO", DFPais.UZBEQUISTAO_REPUBLICA_DO.getDescricao());
        Assertions.assertEquals(Integer.valueOf(8478), DFPais.UZBEQUISTAO_REPUBLICA_DO.getCodigo());
        Assertions.assertEquals("VATICANO, EST.DA CIDADE DO", DFPais.VATICANO_EST_DA_CIDADE_DO.getDescricao());
        Assertions.assertEquals(Integer.valueOf(8486), DFPais.VATICANO_EST_DA_CIDADE_DO.getCodigo());
        Assertions.assertEquals("VENEZUELA", DFPais.VENEZUELA.getDescricao());
        Assertions.assertEquals(Integer.valueOf(8508), DFPais.VENEZUELA.getCodigo());
        Assertions.assertEquals("VIETNA", DFPais.VIETNA.getDescricao());
        Assertions.assertEquals(Integer.valueOf(8583), DFPais.VIETNA.getCodigo());
        Assertions.assertEquals("VIRGENS,ILHAS (BRITANICAS)", DFPais.VIRGENS_ILHAS_BRITANICAS.getDescricao());
        Assertions.assertEquals(Integer.valueOf(8630), DFPais.VIRGENS_ILHAS_BRITANICAS.getCodigo());
        Assertions.assertEquals("VIRGENS,ILHAS (E.U.A.)", DFPais.VIRGENS_ILHAS_E_U_A.getDescricao());
        Assertions.assertEquals(Integer.valueOf(8664), DFPais.VIRGENS_ILHAS_E_U_A.getCodigo());
        Assertions.assertEquals("FIJI", DFPais.FIJI.getDescricao());
        Assertions.assertEquals(Integer.valueOf(8702), DFPais.FIJI.getCodigo());
        Assertions.assertEquals("WALLIS E FUTUNA, ILHAS", DFPais.WALLIS_E_FUTUNA_ILHAS.getDescricao());
        Assertions.assertEquals(Integer.valueOf(8753), DFPais.WALLIS_E_FUTUNA_ILHAS.getCodigo());
        Assertions.assertEquals("WAKE, ILHA", DFPais.WAKE_ILHA.getDescricao());
        Assertions.assertEquals(Integer.valueOf(8737), DFPais.WAKE_ILHA.getCodigo());
        Assertions.assertEquals("CONGO, REPUBLICA DEMOCRATICA DO", DFPais.CONGO_REPUBLICA_DEMOCRATICA_DO.getDescricao());
        Assertions.assertEquals(Integer.valueOf(8885), DFPais.CONGO_REPUBLICA_DEMOCRATICA_DO.getCodigo());
        Assertions.assertEquals("ZAMBIA", DFPais.ZAMBIA.getDescricao());
        Assertions.assertEquals(Integer.valueOf(8907), DFPais.ZAMBIA.getCodigo());

    }

    @Test
    public void deveRetornarNullCasoTenteBuscarUmCodigoErrado() {
        Assertions.assertNull(DFPais.valueOfCodigo("1"));
        Assertions.assertNull(DFPais.valueOfCodigo(1));
    }

    @Test
    public void deveSerADescricaoAoInvocarToString() {
        Assertions.assertEquals("AFRICA DO SUL", DFPais.AFRICA_DO_SUL.toString());
        Assertions.assertEquals("BOSNIA-HERZEGOVINA (REPUBLICA DA)", DFPais.BOSNIA_HERZEGOVINA_REPUBLICA_DA.toString());
    }

    @Test
    public void deveRetornarListaAoPesquisarPorNome() {
        Assertions.assertEquals(Arrays.asList(DFPais.BRASIL, DFPais.GIBRALTAR), DFPais.getListByDesc("BRA"));
        Assertions.assertEquals(Arrays.asList(DFPais.BRASIL, DFPais.GIBRALTAR), DFPais.getListByDesc("bra"));
        Assertions.assertEquals(Arrays.asList(DFPais.BRASIL, DFPais.GIBRALTAR), DFPais.getListByDesc("Bra"));
        Assertions.assertEquals(Arrays.asList( DFPais.BRASIL, DFPais.HONDURAS,
                DFPais.TERRAS_AUSTRAIS_E_ANTARTICAS_FRANCESAS), DFPais.getListByDesc("RAS"));
    }

     @Test
    public void deveRetornarPorCodigo() {
         Assertions.assertEquals(DFPais.valueOfCodigo("132"), DFPais.AFEGANISTAO);
         Assertions.assertEquals(DFPais.valueOfCodigo(132), DFPais.AFEGANISTAO);
         Assertions.assertEquals(DFPais.valueOfCodigo("153"), DFPais.ALAND_ILHAS);
         Assertions.assertEquals(DFPais.valueOfCodigo(153), DFPais.ALAND_ILHAS);
         Assertions.assertEquals(DFPais.valueOfCodigo("175"), DFPais.ALBANIA_REPUBLICA_DA);
         Assertions.assertEquals(DFPais.valueOfCodigo(175), DFPais.ALBANIA_REPUBLICA_DA);
         Assertions.assertEquals(DFPais.valueOfCodigo("230"), DFPais.ALEMANHA);
         Assertions.assertEquals(DFPais.valueOfCodigo(230), DFPais.ALEMANHA);
         Assertions.assertEquals(DFPais.valueOfCodigo("310"), DFPais.BURKINA_FASO);
         Assertions.assertEquals(DFPais.valueOfCodigo(310), DFPais.BURKINA_FASO);
         Assertions.assertEquals(DFPais.valueOfCodigo("370"), DFPais.ANDORRA);
         Assertions.assertEquals(DFPais.valueOfCodigo(370), DFPais.ANDORRA);
         Assertions.assertEquals(DFPais.valueOfCodigo("400"), DFPais.ANGOLA);
         Assertions.assertEquals(DFPais.valueOfCodigo(400), DFPais.ANGOLA);
         Assertions.assertEquals(DFPais.valueOfCodigo("418"), DFPais.ANGUILLA);
         Assertions.assertEquals(DFPais.valueOfCodigo(418), DFPais.ANGUILLA);
         Assertions.assertEquals(DFPais.valueOfCodigo("420"), DFPais.ANTARTICA);
         Assertions.assertEquals(DFPais.valueOfCodigo(420), DFPais.ANTARTICA);
         Assertions.assertEquals(DFPais.valueOfCodigo("434"), DFPais.ANTIGUA_E_BARBUDA);
         Assertions.assertEquals(DFPais.valueOfCodigo(434), DFPais.ANTIGUA_E_BARBUDA);
         Assertions.assertEquals(DFPais.valueOfCodigo("477"), DFPais.ANTILHAS_HOLANDESAS);
         Assertions.assertEquals(DFPais.valueOfCodigo(477), DFPais.ANTILHAS_HOLANDESAS);
         Assertions.assertEquals(DFPais.valueOfCodigo("531"), DFPais.ARABIA_SAUDITA);
         Assertions.assertEquals(DFPais.valueOfCodigo(531), DFPais.ARABIA_SAUDITA);
         Assertions.assertEquals(DFPais.valueOfCodigo("590"), DFPais.ARGELIA);
         Assertions.assertEquals(DFPais.valueOfCodigo(590), DFPais.ARGELIA);
         Assertions.assertEquals(DFPais.valueOfCodigo("639"), DFPais.ARGENTINA);
         Assertions.assertEquals(DFPais.valueOfCodigo(639), DFPais.ARGENTINA);
         Assertions.assertEquals(DFPais.valueOfCodigo("647"), DFPais.ARMENIA_REPUBLICA_DA);
         Assertions.assertEquals(DFPais.valueOfCodigo(647), DFPais.ARMENIA_REPUBLICA_DA);
         Assertions.assertEquals(DFPais.valueOfCodigo("655"), DFPais.ARUBA);
         Assertions.assertEquals(DFPais.valueOfCodigo(655), DFPais.ARUBA);
         Assertions.assertEquals(DFPais.valueOfCodigo("698"), DFPais.AUSTRALIA);
         Assertions.assertEquals(DFPais.valueOfCodigo(698), DFPais.AUSTRALIA);
         Assertions.assertEquals(DFPais.valueOfCodigo("728"), DFPais.AUSTRIA);
         Assertions.assertEquals(DFPais.valueOfCodigo(728), DFPais.AUSTRIA);
         Assertions.assertEquals(DFPais.valueOfCodigo("736"), DFPais.AZERBAIJAO_REPUBLICA_DO);
         Assertions.assertEquals(DFPais.valueOfCodigo(736), DFPais.AZERBAIJAO_REPUBLICA_DO);
         Assertions.assertEquals(DFPais.valueOfCodigo("779"), DFPais.BAHAMAS_ILHAS);
         Assertions.assertEquals(DFPais.valueOfCodigo(779), DFPais.BAHAMAS_ILHAS);
         Assertions.assertEquals(DFPais.valueOfCodigo("809"), DFPais.BAHREIN_ILHAS);
         Assertions.assertEquals(DFPais.valueOfCodigo(809), DFPais.BAHREIN_ILHAS);
         Assertions.assertEquals(DFPais.valueOfCodigo("817"), DFPais.BANGLADESH);
         Assertions.assertEquals(DFPais.valueOfCodigo(817), DFPais.BANGLADESH);
         Assertions.assertEquals(DFPais.valueOfCodigo("833"), DFPais.BARBADOS);
         Assertions.assertEquals(DFPais.valueOfCodigo(833), DFPais.BARBADOS);
         Assertions.assertEquals(DFPais.valueOfCodigo("850"), DFPais.BELARUS_REPUBLICA_DA);
         Assertions.assertEquals(DFPais.valueOfCodigo(850), DFPais.BELARUS_REPUBLICA_DA);
         Assertions.assertEquals(DFPais.valueOfCodigo("876"), DFPais.BELGICA);
         Assertions.assertEquals(DFPais.valueOfCodigo(876), DFPais.BELGICA);
         Assertions.assertEquals(DFPais.valueOfCodigo("884"), DFPais.BELIZE);
         Assertions.assertEquals(DFPais.valueOfCodigo(884), DFPais.BELIZE);
         Assertions.assertEquals(DFPais.valueOfCodigo("906"), DFPais.BERMUDAS);
         Assertions.assertEquals(DFPais.valueOfCodigo(906), DFPais.BERMUDAS);
         Assertions.assertEquals(DFPais.valueOfCodigo("930"), DFPais.MIANMAR_BIRMANIA);
         Assertions.assertEquals(DFPais.valueOfCodigo(930), DFPais.MIANMAR_BIRMANIA);
         Assertions.assertEquals(DFPais.valueOfCodigo("973"), DFPais.BOLIVIA_ESTADO_PLURINACIONAL_DA);
         Assertions.assertEquals(DFPais.valueOfCodigo(973), DFPais.BOLIVIA_ESTADO_PLURINACIONAL_DA);
         Assertions.assertEquals(DFPais.valueOfCodigo("981"), DFPais.BOSNIA_HERZEGOVINA_REPUBLICA_DA);
         Assertions.assertEquals(DFPais.valueOfCodigo(981), DFPais.BOSNIA_HERZEGOVINA_REPUBLICA_DA);
         Assertions.assertEquals(DFPais.valueOfCodigo("990"), DFPais.BONAIRE);
         Assertions.assertEquals(DFPais.valueOfCodigo(990), DFPais.BONAIRE);
         Assertions.assertEquals(DFPais.valueOfCodigo("1015"), DFPais.BOTSUANA);
         Assertions.assertEquals(DFPais.valueOfCodigo(1015), DFPais.BOTSUANA);
         Assertions.assertEquals(DFPais.valueOfCodigo("1023"), DFPais.BOUVET_ILHA);
         Assertions.assertEquals(DFPais.valueOfCodigo(1023), DFPais.BOUVET_ILHA);
         Assertions.assertEquals(DFPais.valueOfCodigo("1058"), DFPais.BRASIL);
         Assertions.assertEquals(DFPais.valueOfCodigo(1058), DFPais.BRASIL);
         Assertions.assertEquals(DFPais.valueOfCodigo("1082"), DFPais.BRUNEI);
         Assertions.assertEquals(DFPais.valueOfCodigo(1082), DFPais.BRUNEI);
         Assertions.assertEquals(DFPais.valueOfCodigo("1112"), DFPais.BULGARIA_REPUBLICA_DA);
         Assertions.assertEquals(DFPais.valueOfCodigo(1112), DFPais.BULGARIA_REPUBLICA_DA);
         Assertions.assertEquals(DFPais.valueOfCodigo("1155"), DFPais.BURUNDI);
         Assertions.assertEquals(DFPais.valueOfCodigo(1155), DFPais.BURUNDI);
         Assertions.assertEquals(DFPais.valueOfCodigo("1198"), DFPais.BUTAO);
         Assertions.assertEquals(DFPais.valueOfCodigo(1198), DFPais.BUTAO);
         Assertions.assertEquals(DFPais.valueOfCodigo("1279"), DFPais.CABO_VERDE_REPUBLICA_DE);
         Assertions.assertEquals(DFPais.valueOfCodigo(1279), DFPais.CABO_VERDE_REPUBLICA_DE);
         Assertions.assertEquals(DFPais.valueOfCodigo("1376"), DFPais.CAYMAN_ILHAS);
         Assertions.assertEquals(DFPais.valueOfCodigo(1376), DFPais.CAYMAN_ILHAS);
         Assertions.assertEquals(DFPais.valueOfCodigo("1414"), DFPais.CAMBOJA);
         Assertions.assertEquals(DFPais.valueOfCodigo(1414), DFPais.CAMBOJA);
         Assertions.assertEquals(DFPais.valueOfCodigo("1457"), DFPais.CAMAROES);
         Assertions.assertEquals(DFPais.valueOfCodigo(1457), DFPais.CAMAROES);
         Assertions.assertEquals(DFPais.valueOfCodigo("1490"), DFPais.CANADA);
         Assertions.assertEquals(DFPais.valueOfCodigo(1490), DFPais.CANADA);
         Assertions.assertEquals(DFPais.valueOfCodigo("1538"), DFPais.CAZAQUISTAO_REPUBLICA_DO);
         Assertions.assertEquals(DFPais.valueOfCodigo(1538), DFPais.CAZAQUISTAO_REPUBLICA_DO);
         Assertions.assertEquals(DFPais.valueOfCodigo("1546"), DFPais.CATAR);
         Assertions.assertEquals(DFPais.valueOfCodigo(1546), DFPais.CATAR);
         Assertions.assertEquals(DFPais.valueOfCodigo("1589"), DFPais.CHILE);
         Assertions.assertEquals(DFPais.valueOfCodigo(1589), DFPais.CHILE);
         Assertions.assertEquals(DFPais.valueOfCodigo("1600"), DFPais.CHINA_REPUBLICA_POPULAR);
         Assertions.assertEquals(DFPais.valueOfCodigo(1600), DFPais.CHINA_REPUBLICA_POPULAR);
         Assertions.assertEquals(DFPais.valueOfCodigo("1619"), DFPais.FORMOSA_TAIWAN);
         Assertions.assertEquals(DFPais.valueOfCodigo(1619), DFPais.FORMOSA_TAIWAN);
         Assertions.assertEquals(DFPais.valueOfCodigo("1635"), DFPais.CHIPRE);
         Assertions.assertEquals(DFPais.valueOfCodigo(1635), DFPais.CHIPRE);
         Assertions.assertEquals(DFPais.valueOfCodigo("1651"), DFPais.COCOS_KEELING_ILHAS);
         Assertions.assertEquals(DFPais.valueOfCodigo(1651), DFPais.COCOS_KEELING_ILHAS);
         Assertions.assertEquals(DFPais.valueOfCodigo("1694"), DFPais.COLOMBIA);
         Assertions.assertEquals(DFPais.valueOfCodigo(1694), DFPais.COLOMBIA);
         Assertions.assertEquals(DFPais.valueOfCodigo("1732"), DFPais.COMORES_ILHAS);
         Assertions.assertEquals(DFPais.valueOfCodigo(1732), DFPais.COMORES_ILHAS);
         Assertions.assertEquals(DFPais.valueOfCodigo("1775"), DFPais.CONGO);
         Assertions.assertEquals(DFPais.valueOfCodigo(1775), DFPais.CONGO);
         Assertions.assertEquals(DFPais.valueOfCodigo("1830"), DFPais.COOK_ILHAS);
         Assertions.assertEquals(DFPais.valueOfCodigo(1830), DFPais.COOK_ILHAS);
         Assertions.assertEquals(DFPais.valueOfCodigo("1872"), DFPais.COREIA_DO_NORTE__REP_POP_DEMOCRATICA);
         Assertions.assertEquals(DFPais.valueOfCodigo(1872), DFPais.COREIA_DO_NORTE__REP_POP_DEMOCRATICA);
         Assertions.assertEquals(DFPais.valueOfCodigo("1902"), DFPais.COREIA_DO_SUL__REPUBLICA_DA);
         Assertions.assertEquals(DFPais.valueOfCodigo(1902), DFPais.COREIA_DO_SUL__REPUBLICA_DA);
         Assertions.assertEquals(DFPais.valueOfCodigo("1937"), DFPais.COSTA_DO_MARFIM);
         Assertions.assertEquals(DFPais.valueOfCodigo(1937), DFPais.COSTA_DO_MARFIM);
         Assertions.assertEquals(DFPais.valueOfCodigo("1953"), DFPais.CROACIA_REPUBLICA_DA);
         Assertions.assertEquals(DFPais.valueOfCodigo(1953), DFPais.CROACIA_REPUBLICA_DA);
         Assertions.assertEquals(DFPais.valueOfCodigo("1961"), DFPais.COSTA_RICA);
         Assertions.assertEquals(DFPais.valueOfCodigo(1961), DFPais.COSTA_RICA);
         Assertions.assertEquals(DFPais.valueOfCodigo("1988"), DFPais.KUWAIT);
         Assertions.assertEquals(DFPais.valueOfCodigo(1988), DFPais.KUWAIT);
         Assertions.assertEquals(DFPais.valueOfCodigo("1996"), DFPais.CUBA);
         Assertions.assertEquals(DFPais.valueOfCodigo(1996), DFPais.CUBA);
         Assertions.assertEquals(DFPais.valueOfCodigo("2003"), DFPais.CURACAO);
         Assertions.assertEquals(DFPais.valueOfCodigo(2003), DFPais.CURACAO);
         Assertions.assertEquals(DFPais.valueOfCodigo("2291"), DFPais.BENIN);
         Assertions.assertEquals(DFPais.valueOfCodigo(2291), DFPais.BENIN);
         Assertions.assertEquals(DFPais.valueOfCodigo("2321"), DFPais.DINAMARCA);
         Assertions.assertEquals(DFPais.valueOfCodigo(2321), DFPais.DINAMARCA);
         Assertions.assertEquals(DFPais.valueOfCodigo("2356"), DFPais.DOMINICA_ILHA);
         Assertions.assertEquals(DFPais.valueOfCodigo(2356), DFPais.DOMINICA_ILHA);
         Assertions.assertEquals(DFPais.valueOfCodigo("2399"), DFPais.EQUADOR);
         Assertions.assertEquals(DFPais.valueOfCodigo(2399), DFPais.EQUADOR);
         Assertions.assertEquals(DFPais.valueOfCodigo("2402"), DFPais.EGITO);
         Assertions.assertEquals(DFPais.valueOfCodigo(2402), DFPais.EGITO);
         Assertions.assertEquals(DFPais.valueOfCodigo("2437"), DFPais.ERITREIA);
         Assertions.assertEquals(DFPais.valueOfCodigo(2437), DFPais.ERITREIA);
         Assertions.assertEquals(DFPais.valueOfCodigo("2445"), DFPais.EMIRADOS_ARABES_UNIDOS);
         Assertions.assertEquals(DFPais.valueOfCodigo(2445), DFPais.EMIRADOS_ARABES_UNIDOS);
         Assertions.assertEquals(DFPais.valueOfCodigo("2453"), DFPais.ESPANHA);
         Assertions.assertEquals(DFPais.valueOfCodigo(2453), DFPais.ESPANHA);
         Assertions.assertEquals(DFPais.valueOfCodigo("2461"), DFPais.ESLOVENIA_REPUBLICA_DA);
         Assertions.assertEquals(DFPais.valueOfCodigo(2461), DFPais.ESLOVENIA_REPUBLICA_DA);
         Assertions.assertEquals(DFPais.valueOfCodigo("2470"), DFPais.ESLOVACA_REPUBLICA);
         Assertions.assertEquals(DFPais.valueOfCodigo(2470), DFPais.ESLOVACA_REPUBLICA);
         Assertions.assertEquals(DFPais.valueOfCodigo("2496"), DFPais.ESTADOS_UNIDOS);
         Assertions.assertEquals(DFPais.valueOfCodigo(2496), DFPais.ESTADOS_UNIDOS);
         Assertions.assertEquals(DFPais.valueOfCodigo("2518"), DFPais.ESTONIA_REPUBLICA_DA);
         Assertions.assertEquals(DFPais.valueOfCodigo(2518), DFPais.ESTONIA_REPUBLICA_DA);
         Assertions.assertEquals(DFPais.valueOfCodigo("2534"), DFPais.ETIOPIA);
         Assertions.assertEquals(DFPais.valueOfCodigo(2534), DFPais.ETIOPIA);
         Assertions.assertEquals(DFPais.valueOfCodigo("2550"), DFPais.FALKLAND_ILHAS_MALVINAS);
         Assertions.assertEquals(DFPais.valueOfCodigo(2550), DFPais.FALKLAND_ILHAS_MALVINAS);
         Assertions.assertEquals(DFPais.valueOfCodigo("2593"), DFPais.FEROE_ILHAS);
         Assertions.assertEquals(DFPais.valueOfCodigo(2593), DFPais.FEROE_ILHAS);
         Assertions.assertEquals(DFPais.valueOfCodigo("2674"), DFPais.FILIPINAS);
         Assertions.assertEquals(DFPais.valueOfCodigo(2674), DFPais.FILIPINAS);
         Assertions.assertEquals(DFPais.valueOfCodigo("2712"), DFPais.FINLANDIA);
         Assertions.assertEquals(DFPais.valueOfCodigo(2712), DFPais.FINLANDIA);
         Assertions.assertEquals(DFPais.valueOfCodigo("2755"), DFPais.FRANCA);
         Assertions.assertEquals(DFPais.valueOfCodigo(2755), DFPais.FRANCA);
         Assertions.assertEquals(DFPais.valueOfCodigo("2810"), DFPais.GABAO);
         Assertions.assertEquals(DFPais.valueOfCodigo(2810), DFPais.GABAO);
         Assertions.assertEquals(DFPais.valueOfCodigo("2852"), DFPais.GAMBIA);
         Assertions.assertEquals(DFPais.valueOfCodigo(2852), DFPais.GAMBIA);
         Assertions.assertEquals(DFPais.valueOfCodigo("2895"), DFPais.GANA);
         Assertions.assertEquals(DFPais.valueOfCodigo(2895), DFPais.GANA);
         Assertions.assertEquals(DFPais.valueOfCodigo("2917"), DFPais.GEORGIA_REPUBLICA_DA);
         Assertions.assertEquals(DFPais.valueOfCodigo(2917), DFPais.GEORGIA_REPUBLICA_DA);
         Assertions.assertEquals(DFPais.valueOfCodigo("2925"), DFPais.ILHAS_GEORGIA_DO_SUL_E_SANDWICH_DO_SUL);
         Assertions.assertEquals(DFPais.valueOfCodigo(2925), DFPais.ILHAS_GEORGIA_DO_SUL_E_SANDWICH_DO_SUL);
         Assertions.assertEquals(DFPais.valueOfCodigo("2933"), DFPais.GIBRALTAR);
         Assertions.assertEquals(DFPais.valueOfCodigo(2933), DFPais.GIBRALTAR);
         Assertions.assertEquals(DFPais.valueOfCodigo("2976"), DFPais.GRANADA);
         Assertions.assertEquals(DFPais.valueOfCodigo(2976), DFPais.GRANADA);
         Assertions.assertEquals(DFPais.valueOfCodigo("3018"), DFPais.GRECIA);
         Assertions.assertEquals(DFPais.valueOfCodigo(3018), DFPais.GRECIA);
         Assertions.assertEquals(DFPais.valueOfCodigo("3050"), DFPais.GROENLANDIA);
         Assertions.assertEquals(DFPais.valueOfCodigo(3050), DFPais.GROENLANDIA);
         Assertions.assertEquals(DFPais.valueOfCodigo("3093"), DFPais.GUADALUPE);
         Assertions.assertEquals(DFPais.valueOfCodigo(3093), DFPais.GUADALUPE);
         Assertions.assertEquals(DFPais.valueOfCodigo("3131"), DFPais.GUAM);
         Assertions.assertEquals(DFPais.valueOfCodigo(3131), DFPais.GUAM);
         Assertions.assertEquals(DFPais.valueOfCodigo("3174"), DFPais.GUATEMALA);
         Assertions.assertEquals(DFPais.valueOfCodigo(3174), DFPais.GUATEMALA);
         Assertions.assertEquals(DFPais.valueOfCodigo("3212"), DFPais.GUERNSEY_ILHA_DO_CANAL_INCLUI_ALDERNEY_E_SARK);
         Assertions.assertEquals(DFPais.valueOfCodigo(3212), DFPais.GUERNSEY_ILHA_DO_CANAL_INCLUI_ALDERNEY_E_SARK);
         Assertions.assertEquals(DFPais.valueOfCodigo("3255"), DFPais.GUIANA_FRANCESA);
         Assertions.assertEquals(DFPais.valueOfCodigo(3255), DFPais.GUIANA_FRANCESA);
         Assertions.assertEquals(DFPais.valueOfCodigo("3298"), DFPais.GUINE);
         Assertions.assertEquals(DFPais.valueOfCodigo(3298), DFPais.GUINE);
         Assertions.assertEquals(DFPais.valueOfCodigo("3310"), DFPais.GUINE_EQUATORIAL);
         Assertions.assertEquals(DFPais.valueOfCodigo(3310), DFPais.GUINE_EQUATORIAL);
         Assertions.assertEquals(DFPais.valueOfCodigo("3344"), DFPais.GUINE_BISSAU);
         Assertions.assertEquals(DFPais.valueOfCodigo(3344), DFPais.GUINE_BISSAU);
         Assertions.assertEquals(DFPais.valueOfCodigo("3379"), DFPais.GUIANA);
         Assertions.assertEquals(DFPais.valueOfCodigo(3379), DFPais.GUIANA);
         Assertions.assertEquals(DFPais.valueOfCodigo("3417"), DFPais.HAITI);
         Assertions.assertEquals(DFPais.valueOfCodigo(3417), DFPais.HAITI);
         Assertions.assertEquals(DFPais.valueOfCodigo("3433"), DFPais.ILHA_HEARD_E_ILHAS_MCDONALD);
         Assertions.assertEquals(DFPais.valueOfCodigo(3433), DFPais.ILHA_HEARD_E_ILHAS_MCDONALD);
         Assertions.assertEquals(DFPais.valueOfCodigo("3450"), DFPais.HONDURAS);
         Assertions.assertEquals(DFPais.valueOfCodigo(3450), DFPais.HONDURAS);
         Assertions.assertEquals(DFPais.valueOfCodigo("3514"), DFPais.HONG_KONG);
         Assertions.assertEquals(DFPais.valueOfCodigo(3514), DFPais.HONG_KONG);
         Assertions.assertEquals(DFPais.valueOfCodigo("3557"), DFPais.HUNGRIA_REPUBLICA_DA);
         Assertions.assertEquals(DFPais.valueOfCodigo(3557), DFPais.HUNGRIA_REPUBLICA_DA);
         Assertions.assertEquals(DFPais.valueOfCodigo("3573"), DFPais.IEMEN);
         Assertions.assertEquals(DFPais.valueOfCodigo(3573), DFPais.IEMEN);
         Assertions.assertEquals(DFPais.valueOfCodigo("3595"), DFPais.MAN_ILHA_DE);
         Assertions.assertEquals(DFPais.valueOfCodigo(3595), DFPais.MAN_ILHA_DE);
         Assertions.assertEquals(DFPais.valueOfCodigo("3611"), DFPais.INDIA);
         Assertions.assertEquals(DFPais.valueOfCodigo(3611), DFPais.INDIA);
         Assertions.assertEquals(DFPais.valueOfCodigo("3654"), DFPais.INDONESIA);
         Assertions.assertEquals(DFPais.valueOfCodigo(3654), DFPais.INDONESIA);
         Assertions.assertEquals(DFPais.valueOfCodigo("3697"), DFPais.IRAQUE);
         Assertions.assertEquals(DFPais.valueOfCodigo(3697), DFPais.IRAQUE);
         Assertions.assertEquals(DFPais.valueOfCodigo("3727"), DFPais.IRA_REPUBLICA_ISLAMICA_DO);
         Assertions.assertEquals(DFPais.valueOfCodigo(3727), DFPais.IRA_REPUBLICA_ISLAMICA_DO);
         Assertions.assertEquals(DFPais.valueOfCodigo("3751"), DFPais.IRLANDA);
         Assertions.assertEquals(DFPais.valueOfCodigo(3751), DFPais.IRLANDA);
         Assertions.assertEquals(DFPais.valueOfCodigo("3794"), DFPais.ISLANDIA);
         Assertions.assertEquals(DFPais.valueOfCodigo(3794), DFPais.ISLANDIA);
         Assertions.assertEquals(DFPais.valueOfCodigo("3832"), DFPais.ISRAEL);
         Assertions.assertEquals(DFPais.valueOfCodigo(3832), DFPais.ISRAEL);
         Assertions.assertEquals(DFPais.valueOfCodigo("3867"), DFPais.ITALIA);
         Assertions.assertEquals(DFPais.valueOfCodigo(3867), DFPais.ITALIA);
         Assertions.assertEquals(DFPais.valueOfCodigo("3913"), DFPais.JAMAICA);
         Assertions.assertEquals(DFPais.valueOfCodigo(3913), DFPais.JAMAICA);
         Assertions.assertEquals(DFPais.valueOfCodigo("3930"), DFPais.JERSEY_ILHA_DO_CANAL);
         Assertions.assertEquals(DFPais.valueOfCodigo(3930), DFPais.JERSEY_ILHA_DO_CANAL);
         Assertions.assertEquals(DFPais.valueOfCodigo("3964"), DFPais.JOHNSTON_ILHAS);
         Assertions.assertEquals(DFPais.valueOfCodigo(3964), DFPais.JOHNSTON_ILHAS);
         Assertions.assertEquals(DFPais.valueOfCodigo("3999"), DFPais.JAPAO);
         Assertions.assertEquals(DFPais.valueOfCodigo(3999), DFPais.JAPAO);
         Assertions.assertEquals(DFPais.valueOfCodigo("4030"), DFPais.JORDANIA);
         Assertions.assertEquals(DFPais.valueOfCodigo(4030), DFPais.JORDANIA);
         Assertions.assertEquals(DFPais.valueOfCodigo("4111"), DFPais.KIRIBATI);
         Assertions.assertEquals(DFPais.valueOfCodigo(4111), DFPais.KIRIBATI);
         Assertions.assertEquals(DFPais.valueOfCodigo("4200"), DFPais.LAOS_REP_POP_DEMOCR_DO);
         Assertions.assertEquals(DFPais.valueOfCodigo(4200), DFPais.LAOS_REP_POP_DEMOCR_DO);
         Assertions.assertEquals(DFPais.valueOfCodigo("4235"), DFPais.LEBUAN_ILHAS);
         Assertions.assertEquals(DFPais.valueOfCodigo(4235), DFPais.LEBUAN_ILHAS);
         Assertions.assertEquals(DFPais.valueOfCodigo("4260"), DFPais.LESOTO);
         Assertions.assertEquals(DFPais.valueOfCodigo(4260), DFPais.LESOTO);
         Assertions.assertEquals(DFPais.valueOfCodigo("4278"), DFPais.LETONIA_REPUBLICA_DA);
         Assertions.assertEquals(DFPais.valueOfCodigo(4278), DFPais.LETONIA_REPUBLICA_DA);
         Assertions.assertEquals(DFPais.valueOfCodigo("4316"), DFPais.LIBANO);
         Assertions.assertEquals(DFPais.valueOfCodigo(4316), DFPais.LIBANO);
         Assertions.assertEquals(DFPais.valueOfCodigo("4340"), DFPais.LIBERIA);
         Assertions.assertEquals(DFPais.valueOfCodigo(4340), DFPais.LIBERIA);
         Assertions.assertEquals(DFPais.valueOfCodigo("4383"), DFPais.LIBIA);
         Assertions.assertEquals(DFPais.valueOfCodigo(4383), DFPais.LIBIA);
         Assertions.assertEquals(DFPais.valueOfCodigo("4405"), DFPais.LIECHTENSTEIN);
         Assertions.assertEquals(DFPais.valueOfCodigo(4405), DFPais.LIECHTENSTEIN);
         Assertions.assertEquals(DFPais.valueOfCodigo("4421"), DFPais.LITUANIA_REPUBLICA_DA);
         Assertions.assertEquals(DFPais.valueOfCodigo(4421), DFPais.LITUANIA_REPUBLICA_DA);
         Assertions.assertEquals(DFPais.valueOfCodigo("4456"), DFPais.LUXEMBURGO);
         Assertions.assertEquals(DFPais.valueOfCodigo(4456), DFPais.LUXEMBURGO);
         Assertions.assertEquals(DFPais.valueOfCodigo("4472"), DFPais.MACAU);
         Assertions.assertEquals(DFPais.valueOfCodigo(4472), DFPais.MACAU);
         Assertions.assertEquals(DFPais.valueOfCodigo("4499"), DFPais.MACEDONIA_ANT_REP_IUGOSLAVA);
         Assertions.assertEquals(DFPais.valueOfCodigo(4499), DFPais.MACEDONIA_ANT_REP_IUGOSLAVA);
         Assertions.assertEquals(DFPais.valueOfCodigo("4502"), DFPais.MADAGASCAR);
         Assertions.assertEquals(DFPais.valueOfCodigo(4502), DFPais.MADAGASCAR);
         Assertions.assertEquals(DFPais.valueOfCodigo("4525"), DFPais.MADEIRA_ILHA_DA);
         Assertions.assertEquals(DFPais.valueOfCodigo(4525), DFPais.MADEIRA_ILHA_DA);
         Assertions.assertEquals(DFPais.valueOfCodigo("4553"), DFPais.MALASIA);
         Assertions.assertEquals(DFPais.valueOfCodigo(4553), DFPais.MALASIA);
         Assertions.assertEquals(DFPais.valueOfCodigo("4588"), DFPais.MALAVI);
         Assertions.assertEquals(DFPais.valueOfCodigo(4588), DFPais.MALAVI);
         Assertions.assertEquals(DFPais.valueOfCodigo("4618"), DFPais.MALDIVAS);
         Assertions.assertEquals(DFPais.valueOfCodigo(4618), DFPais.MALDIVAS);
         Assertions.assertEquals(DFPais.valueOfCodigo("4642"), DFPais.MALI);
         Assertions.assertEquals(DFPais.valueOfCodigo(4642), DFPais.MALI);
         Assertions.assertEquals(DFPais.valueOfCodigo("4677"), DFPais.MALTA);
         Assertions.assertEquals(DFPais.valueOfCodigo(4677), DFPais.MALTA);
         Assertions.assertEquals(DFPais.valueOfCodigo("4723"), DFPais.MARIANAS_DO_NORTE);
         Assertions.assertEquals(DFPais.valueOfCodigo(4723), DFPais.MARIANAS_DO_NORTE);
         Assertions.assertEquals(DFPais.valueOfCodigo("4740"), DFPais.MARROCOS);
         Assertions.assertEquals(DFPais.valueOfCodigo(4740), DFPais.MARROCOS);
         Assertions.assertEquals(DFPais.valueOfCodigo("4766"), DFPais.MARSHALL_ILHAS);
         Assertions.assertEquals(DFPais.valueOfCodigo(4766), DFPais.MARSHALL_ILHAS);
         Assertions.assertEquals(DFPais.valueOfCodigo("4774"), DFPais.MARTINICA);
         Assertions.assertEquals(DFPais.valueOfCodigo(4774), DFPais.MARTINICA);
         Assertions.assertEquals(DFPais.valueOfCodigo("4855"), DFPais.MAURICIO);
         Assertions.assertEquals(DFPais.valueOfCodigo(4855), DFPais.MAURICIO);
         Assertions.assertEquals(DFPais.valueOfCodigo("4880"), DFPais.MAURITANIA);
         Assertions.assertEquals(DFPais.valueOfCodigo(4880), DFPais.MAURITANIA);
         Assertions.assertEquals(DFPais.valueOfCodigo("4898"), DFPais.MAYOTTE_ILHAS_FRANCESAS);
         Assertions.assertEquals(DFPais.valueOfCodigo(4898), DFPais.MAYOTTE_ILHAS_FRANCESAS);
         Assertions.assertEquals(DFPais.valueOfCodigo("4901"), DFPais.MIDWAY_ILHAS);
         Assertions.assertEquals(DFPais.valueOfCodigo(4901), DFPais.MIDWAY_ILHAS);
         Assertions.assertEquals(DFPais.valueOfCodigo("4936"), DFPais.MEXICO);
         Assertions.assertEquals(DFPais.valueOfCodigo(4936), DFPais.MEXICO);
         Assertions.assertEquals(DFPais.valueOfCodigo("4944"), DFPais.MOLDAVIA_REPUBLICA_DA);
         Assertions.assertEquals(DFPais.valueOfCodigo(4944), DFPais.MOLDAVIA_REPUBLICA_DA);
         Assertions.assertEquals(DFPais.valueOfCodigo("4952"), DFPais.MONACO);
         Assertions.assertEquals(DFPais.valueOfCodigo(4952), DFPais.MONACO);
         Assertions.assertEquals(DFPais.valueOfCodigo("4979"), DFPais.MONGOLIA);
         Assertions.assertEquals(DFPais.valueOfCodigo(4979), DFPais.MONGOLIA);
         Assertions.assertEquals(DFPais.valueOfCodigo("4985"), DFPais.MONTENEGRO);
         Assertions.assertEquals(DFPais.valueOfCodigo(4985), DFPais.MONTENEGRO);
         Assertions.assertEquals(DFPais.valueOfCodigo("4995"), DFPais.MICRONESIA);
         Assertions.assertEquals(DFPais.valueOfCodigo(4995), DFPais.MICRONESIA);
         Assertions.assertEquals(DFPais.valueOfCodigo("5010"), DFPais.MONTSERRAT_ILHAS);
         Assertions.assertEquals(DFPais.valueOfCodigo(5010), DFPais.MONTSERRAT_ILHAS);
         Assertions.assertEquals(DFPais.valueOfCodigo("5053"), DFPais.MOCAMBIQUE);
         Assertions.assertEquals(DFPais.valueOfCodigo(5053), DFPais.MOCAMBIQUE);
         Assertions.assertEquals(DFPais.valueOfCodigo("5070"), DFPais.NAMIBIA);
         Assertions.assertEquals(DFPais.valueOfCodigo(5070), DFPais.NAMIBIA);
         Assertions.assertEquals(DFPais.valueOfCodigo("5088"), DFPais.NAURU);
         Assertions.assertEquals(DFPais.valueOfCodigo(5088), DFPais.NAURU);
         Assertions.assertEquals(DFPais.valueOfCodigo("5118"), DFPais.CHRISTMAS_ILHA_NAVIDAD);
         Assertions.assertEquals(DFPais.valueOfCodigo(5118), DFPais.CHRISTMAS_ILHA_NAVIDAD);
         Assertions.assertEquals(DFPais.valueOfCodigo("5177"), DFPais.NEPAL);
         Assertions.assertEquals(DFPais.valueOfCodigo(5177), DFPais.NEPAL);
         Assertions.assertEquals(DFPais.valueOfCodigo("5215"), DFPais.NICARAGUA);
         Assertions.assertEquals(DFPais.valueOfCodigo(5215), DFPais.NICARAGUA);
         Assertions.assertEquals(DFPais.valueOfCodigo("5258"), DFPais.NIGER);
         Assertions.assertEquals(DFPais.valueOfCodigo(5258), DFPais.NIGER);
         Assertions.assertEquals(DFPais.valueOfCodigo("5282"), DFPais.NIGERIA);
         Assertions.assertEquals(DFPais.valueOfCodigo(5282), DFPais.NIGERIA);
         Assertions.assertEquals(DFPais.valueOfCodigo("5312"), DFPais.NIUE_ILHA);
         Assertions.assertEquals(DFPais.valueOfCodigo(5312), DFPais.NIUE_ILHA);
         Assertions.assertEquals(DFPais.valueOfCodigo("5355"), DFPais.NORFOLK_ILHA);
         Assertions.assertEquals(DFPais.valueOfCodigo(5355), DFPais.NORFOLK_ILHA);
         Assertions.assertEquals(DFPais.valueOfCodigo("5380"), DFPais.NORUEGA);
         Assertions.assertEquals(DFPais.valueOfCodigo(5380), DFPais.NORUEGA);
         Assertions.assertEquals(DFPais.valueOfCodigo("5428"), DFPais.NOVA_CALEDONIA);
         Assertions.assertEquals(DFPais.valueOfCodigo(5428), DFPais.NOVA_CALEDONIA);
         Assertions.assertEquals(DFPais.valueOfCodigo("5452"), DFPais.PAPUA_NOVA_GUINE);
         Assertions.assertEquals(DFPais.valueOfCodigo(5452), DFPais.PAPUA_NOVA_GUINE);
         Assertions.assertEquals(DFPais.valueOfCodigo("5487"), DFPais.NOVA_ZELANDIA);
         Assertions.assertEquals(DFPais.valueOfCodigo(5487), DFPais.NOVA_ZELANDIA);
         Assertions.assertEquals(DFPais.valueOfCodigo("5517"), DFPais.VANUATU);
         Assertions.assertEquals(DFPais.valueOfCodigo(5517), DFPais.VANUATU);
         Assertions.assertEquals(DFPais.valueOfCodigo("5568"), DFPais.OMA);
         Assertions.assertEquals(DFPais.valueOfCodigo(5568), DFPais.OMA);
         Assertions.assertEquals(DFPais.valueOfCodigo("5665"), DFPais.PACIFICO_ILHAS_DO_POSSESSAO_DOS_EUA);
         Assertions.assertEquals(DFPais.valueOfCodigo(5665), DFPais.PACIFICO_ILHAS_DO_POSSESSAO_DOS_EUA);
         Assertions.assertEquals(DFPais.valueOfCodigo("5738"), DFPais.PAISES_BAIXOS_HOLANDA);
         Assertions.assertEquals(DFPais.valueOfCodigo(5738), DFPais.PAISES_BAIXOS_HOLANDA);
         Assertions.assertEquals(DFPais.valueOfCodigo("5754"), DFPais.PALAU);
         Assertions.assertEquals(DFPais.valueOfCodigo(5754), DFPais.PALAU);
         Assertions.assertEquals(DFPais.valueOfCodigo("5762"), DFPais.PAQUISTAO);
         Assertions.assertEquals(DFPais.valueOfCodigo(5762), DFPais.PAQUISTAO);
         Assertions.assertEquals(DFPais.valueOfCodigo("5780"), DFPais.PALESTINA);
         Assertions.assertEquals(DFPais.valueOfCodigo(5780), DFPais.PALESTINA);
         Assertions.assertEquals(DFPais.valueOfCodigo("5800"), DFPais.PANAMA);
         Assertions.assertEquals(DFPais.valueOfCodigo(5800), DFPais.PANAMA);
         Assertions.assertEquals(DFPais.valueOfCodigo("5860"), DFPais.PARAGUAI);
         Assertions.assertEquals(DFPais.valueOfCodigo(5860), DFPais.PARAGUAI);
         Assertions.assertEquals(DFPais.valueOfCodigo("5894"), DFPais.PERU);
         Assertions.assertEquals(DFPais.valueOfCodigo(5894), DFPais.PERU);
         Assertions.assertEquals(DFPais.valueOfCodigo("5932"), DFPais.PITCAIRN_ILHA);
         Assertions.assertEquals(DFPais.valueOfCodigo(5932), DFPais.PITCAIRN_ILHA);
         Assertions.assertEquals(DFPais.valueOfCodigo("5991"), DFPais.POLINESIA_FRANCESA);
         Assertions.assertEquals(DFPais.valueOfCodigo(5991), DFPais.POLINESIA_FRANCESA);
         Assertions.assertEquals(DFPais.valueOfCodigo("6033"), DFPais.POLONIA_REPUBLICA_DA);
         Assertions.assertEquals(DFPais.valueOfCodigo(6033), DFPais.POLONIA_REPUBLICA_DA);
         Assertions.assertEquals(DFPais.valueOfCodigo("6076"), DFPais.PORTUGAL);
         Assertions.assertEquals(DFPais.valueOfCodigo(6076), DFPais.PORTUGAL);
         Assertions.assertEquals(DFPais.valueOfCodigo("6114"), DFPais.PORTO_RICO);
         Assertions.assertEquals(DFPais.valueOfCodigo(6114), DFPais.PORTO_RICO);
         Assertions.assertEquals(DFPais.valueOfCodigo("6238"), DFPais.QUENIA);
         Assertions.assertEquals(DFPais.valueOfCodigo(6238), DFPais.QUENIA);
         Assertions.assertEquals(DFPais.valueOfCodigo("6254"), DFPais.QUIRGUIZ_REPUBLICA);
         Assertions.assertEquals(DFPais.valueOfCodigo(6254), DFPais.QUIRGUIZ_REPUBLICA);
         Assertions.assertEquals(DFPais.valueOfCodigo("6289"), DFPais.REINO_UNIDO);
         Assertions.assertEquals(DFPais.valueOfCodigo(6289), DFPais.REINO_UNIDO);
         Assertions.assertEquals(DFPais.valueOfCodigo("6408"), DFPais.REPUBLICA_CENTRO_AFRICANA);
         Assertions.assertEquals(DFPais.valueOfCodigo(6408), DFPais.REPUBLICA_CENTRO_AFRICANA);
         Assertions.assertEquals(DFPais.valueOfCodigo("6475"), DFPais.REPUBLICA_DOMINICANA);
         Assertions.assertEquals(DFPais.valueOfCodigo(6475), DFPais.REPUBLICA_DOMINICANA);
         Assertions.assertEquals(DFPais.valueOfCodigo("6602"), DFPais.REUNIAO_ILHA);
         Assertions.assertEquals(DFPais.valueOfCodigo(6602), DFPais.REUNIAO_ILHA);
         Assertions.assertEquals(DFPais.valueOfCodigo("6653"), DFPais.ZIMBABUE);
         Assertions.assertEquals(DFPais.valueOfCodigo(6653), DFPais.ZIMBABUE);
         Assertions.assertEquals(DFPais.valueOfCodigo("6700"), DFPais.ROMENIA);
         Assertions.assertEquals(DFPais.valueOfCodigo(6700), DFPais.ROMENIA);
         Assertions.assertEquals(DFPais.valueOfCodigo("6750"), DFPais.RUANDA);
         Assertions.assertEquals(DFPais.valueOfCodigo(6750), DFPais.RUANDA);
         Assertions.assertEquals(DFPais.valueOfCodigo("6769"), DFPais.RUSSIA_FEDERACAO_DA);
         Assertions.assertEquals(DFPais.valueOfCodigo(6769), DFPais.RUSSIA_FEDERACAO_DA);
         Assertions.assertEquals(DFPais.valueOfCodigo("6777"), DFPais.SALOMAO_ILHAS);
         Assertions.assertEquals(DFPais.valueOfCodigo(6777), DFPais.SALOMAO_ILHAS);
         Assertions.assertEquals(DFPais.valueOfCodigo("6858"), DFPais.SAARA_OCIDENTAL);
         Assertions.assertEquals(DFPais.valueOfCodigo(6858), DFPais.SAARA_OCIDENTAL);
         Assertions.assertEquals(DFPais.valueOfCodigo("6874"), DFPais.EL_SALVADOR);
         Assertions.assertEquals(DFPais.valueOfCodigo(6874), DFPais.EL_SALVADOR);
         Assertions.assertEquals(DFPais.valueOfCodigo("6904"), DFPais.SAMOA);
         Assertions.assertEquals(DFPais.valueOfCodigo(6904), DFPais.SAMOA);
         Assertions.assertEquals(DFPais.valueOfCodigo("6912"), DFPais.SAMOA_AMERICANA);
         Assertions.assertEquals(DFPais.valueOfCodigo(6912), DFPais.SAMOA_AMERICANA);
         Assertions.assertEquals(DFPais.valueOfCodigo("6955"), DFPais.SAO_CRISTOVAO_E_NEVES_ILHAS);
         Assertions.assertEquals(DFPais.valueOfCodigo(6955), DFPais.SAO_CRISTOVAO_E_NEVES_ILHAS);
         Assertions.assertEquals(DFPais.valueOfCodigo("6939"), DFPais.SAO_BARTOLOMEU);
         Assertions.assertEquals(DFPais.valueOfCodigo(6939), DFPais.SAO_BARTOLOMEU);
         Assertions.assertEquals(DFPais.valueOfCodigo("6971"), DFPais.SAN_MARINO);
         Assertions.assertEquals(DFPais.valueOfCodigo(6971), DFPais.SAN_MARINO);
         Assertions.assertEquals(DFPais.valueOfCodigo("6980"), DFPais.ILHAS_DE_SAO_MARTINHO_PARTE_FRANCESA);
         Assertions.assertEquals(DFPais.valueOfCodigo(6980), DFPais.ILHAS_DE_SAO_MARTINHO_PARTE_FRANCESA);
         Assertions.assertEquals(DFPais.valueOfCodigo("6998"), DFPais.SAO_MARTINHO_ILHA_DE_PARTE_FRANCESA);
         Assertions.assertEquals(DFPais.valueOfCodigo(6998), DFPais.SAO_MARTINHO_ILHA_DE_PARTE_FRANCESA);
         Assertions.assertEquals(DFPais.valueOfCodigo("7005"), DFPais.SAO_PEDRO_E_MIQUELON);
         Assertions.assertEquals(DFPais.valueOfCodigo(7005), DFPais.SAO_PEDRO_E_MIQUELON);
         Assertions.assertEquals(DFPais.valueOfCodigo("7056"), DFPais.SAO_VICENTE_E_GRANADINAS);
         Assertions.assertEquals(DFPais.valueOfCodigo(7056), DFPais.SAO_VICENTE_E_GRANADINAS);
         Assertions.assertEquals(DFPais.valueOfCodigo("7102"), DFPais.SANTA_HELENA);
         Assertions.assertEquals(DFPais.valueOfCodigo(7102), DFPais.SANTA_HELENA);
         Assertions.assertEquals(DFPais.valueOfCodigo("7153"), DFPais.SANTA_LUCIA);
         Assertions.assertEquals(DFPais.valueOfCodigo(7153), DFPais.SANTA_LUCIA);
         Assertions.assertEquals(DFPais.valueOfCodigo("7200"), DFPais.SAO_TOME_E_PRINCIPE_ILHAS);
         Assertions.assertEquals(DFPais.valueOfCodigo(7200), DFPais.SAO_TOME_E_PRINCIPE_ILHAS);
         Assertions.assertEquals(DFPais.valueOfCodigo("7285"), DFPais.SENEGAL);
         Assertions.assertEquals(DFPais.valueOfCodigo(7285), DFPais.SENEGAL);
         Assertions.assertEquals(DFPais.valueOfCodigo("7315"), DFPais.SEYCHELLES);
         Assertions.assertEquals(DFPais.valueOfCodigo(7315), DFPais.SEYCHELLES);
         Assertions.assertEquals(DFPais.valueOfCodigo("7358"), DFPais.SERRA_LEOA);
         Assertions.assertEquals(DFPais.valueOfCodigo(7358), DFPais.SERRA_LEOA);
         Assertions.assertEquals(DFPais.valueOfCodigo("7370"), DFPais.SERVIA);
         Assertions.assertEquals(DFPais.valueOfCodigo(7370), DFPais.SERVIA);
         Assertions.assertEquals(DFPais.valueOfCodigo("7412"), DFPais.CINGAPURA);
         Assertions.assertEquals(DFPais.valueOfCodigo(7412), DFPais.CINGAPURA);
         Assertions.assertEquals(DFPais.valueOfCodigo("7447"), DFPais.SIRIA_REPUBLICA_ARABE_DA);
         Assertions.assertEquals(DFPais.valueOfCodigo(7447), DFPais.SIRIA_REPUBLICA_ARABE_DA);
         Assertions.assertEquals(DFPais.valueOfCodigo("7480"), DFPais.SOMALIA);
         Assertions.assertEquals(DFPais.valueOfCodigo(7480), DFPais.SOMALIA);
         Assertions.assertEquals(DFPais.valueOfCodigo("7501"), DFPais.SRI_LANKA);
         Assertions.assertEquals(DFPais.valueOfCodigo(7501), DFPais.SRI_LANKA);
         Assertions.assertEquals(DFPais.valueOfCodigo("7544"), DFPais.SUAZILANDIA);
         Assertions.assertEquals(DFPais.valueOfCodigo(7544), DFPais.SUAZILANDIA);
         Assertions.assertEquals(DFPais.valueOfCodigo("7552"), DFPais.SVALBARD_E_JAN_MAYERN);
         Assertions.assertEquals(DFPais.valueOfCodigo(7552), DFPais.SVALBARD_E_JAN_MAYERN);
         Assertions.assertEquals(DFPais.valueOfCodigo("7560"), DFPais.AFRICA_DO_SUL);
         Assertions.assertEquals(DFPais.valueOfCodigo(7560), DFPais.AFRICA_DO_SUL);
         Assertions.assertEquals(DFPais.valueOfCodigo("7595"), DFPais.SUDAO);
         Assertions.assertEquals(DFPais.valueOfCodigo(7595), DFPais.SUDAO);
         Assertions.assertEquals(DFPais.valueOfCodigo("7600"), DFPais.SUD_O_DO_SUL);
         Assertions.assertEquals(DFPais.valueOfCodigo(7600), DFPais.SUD_O_DO_SUL);
         Assertions.assertEquals(DFPais.valueOfCodigo("7641"), DFPais.SUECIA);
         Assertions.assertEquals(DFPais.valueOfCodigo(7641), DFPais.SUECIA);
         Assertions.assertEquals(DFPais.valueOfCodigo("7676"), DFPais.SUICA);
         Assertions.assertEquals(DFPais.valueOfCodigo(7676), DFPais.SUICA);
         Assertions.assertEquals(DFPais.valueOfCodigo("7706"), DFPais.SURINAME);
         Assertions.assertEquals(DFPais.valueOfCodigo(7706), DFPais.SURINAME);
         Assertions.assertEquals(DFPais.valueOfCodigo("7722"), DFPais.TADJIQUISTAO_REPUBLICA_DO);
         Assertions.assertEquals(DFPais.valueOfCodigo(7722), DFPais.TADJIQUISTAO_REPUBLICA_DO);
         Assertions.assertEquals(DFPais.valueOfCodigo("7765"), DFPais.TAILANDIA);
         Assertions.assertEquals(DFPais.valueOfCodigo(7765), DFPais.TAILANDIA);
         Assertions.assertEquals(DFPais.valueOfCodigo("7803"), DFPais.TANZANIA_REP_UNIDA_DA);
         Assertions.assertEquals(DFPais.valueOfCodigo(7803), DFPais.TANZANIA_REP_UNIDA_DA);
         Assertions.assertEquals(DFPais.valueOfCodigo("7811"), DFPais.TERRAS_AUSTRAIS_E_ANTARTICAS_FRANCESAS);
         Assertions.assertEquals(DFPais.valueOfCodigo(7811), DFPais.TERRAS_AUSTRAIS_E_ANTARTICAS_FRANCESAS);
         Assertions.assertEquals(DFPais.valueOfCodigo("7820"), DFPais.TERRITORIO_BRIT_OC_INDICO);
         Assertions.assertEquals(DFPais.valueOfCodigo(7820), DFPais.TERRITORIO_BRIT_OC_INDICO);
         Assertions.assertEquals(DFPais.valueOfCodigo("7838"), DFPais.DJIBUTI);
         Assertions.assertEquals(DFPais.valueOfCodigo(7838), DFPais.DJIBUTI);
         Assertions.assertEquals(DFPais.valueOfCodigo("7889"), DFPais.CHADE);
         Assertions.assertEquals(DFPais.valueOfCodigo(7889), DFPais.CHADE);
         Assertions.assertEquals(DFPais.valueOfCodigo("7919"), DFPais.TCHECA_REPUBLICA);
         Assertions.assertEquals(DFPais.valueOfCodigo(7919), DFPais.TCHECA_REPUBLICA);
         Assertions.assertEquals(DFPais.valueOfCodigo("7951"), DFPais.TIMOR_LESTE);
         Assertions.assertEquals(DFPais.valueOfCodigo(7951), DFPais.TIMOR_LESTE);
         Assertions.assertEquals(DFPais.valueOfCodigo("8001"), DFPais.TOGO);
         Assertions.assertEquals(DFPais.valueOfCodigo(8001), DFPais.TOGO);
         Assertions.assertEquals(DFPais.valueOfCodigo("8052"), DFPais.TOQUELAU_ILHAS);
         Assertions.assertEquals(DFPais.valueOfCodigo(8052), DFPais.TOQUELAU_ILHAS);
         Assertions.assertEquals(DFPais.valueOfCodigo("8109"), DFPais.TONGA);
         Assertions.assertEquals(DFPais.valueOfCodigo(8109), DFPais.TONGA);
         Assertions.assertEquals(DFPais.valueOfCodigo("8150"), DFPais.TRINIDAD_E_TOBAGO);
         Assertions.assertEquals(DFPais.valueOfCodigo(8150), DFPais.TRINIDAD_E_TOBAGO);
         Assertions.assertEquals(DFPais.valueOfCodigo("8206"), DFPais.TUNISIA);
         Assertions.assertEquals(DFPais.valueOfCodigo(8206), DFPais.TUNISIA);
         Assertions.assertEquals(DFPais.valueOfCodigo("8230"), DFPais.TURCAS_E_CAICOS_ILHAS);
         Assertions.assertEquals(DFPais.valueOfCodigo(8230), DFPais.TURCAS_E_CAICOS_ILHAS);
         Assertions.assertEquals(DFPais.valueOfCodigo("8249"), DFPais.TURCOMENISTAO_REPUBLICA_DO);
         Assertions.assertEquals(DFPais.valueOfCodigo(8249), DFPais.TURCOMENISTAO_REPUBLICA_DO);
         Assertions.assertEquals(DFPais.valueOfCodigo("8273"), DFPais.TURQUIA);
         Assertions.assertEquals(DFPais.valueOfCodigo(8273), DFPais.TURQUIA);
         Assertions.assertEquals(DFPais.valueOfCodigo("8281"), DFPais.TUVALU);
         Assertions.assertEquals(DFPais.valueOfCodigo(8281), DFPais.TUVALU);
         Assertions.assertEquals(DFPais.valueOfCodigo("8311"), DFPais.UCRANIA);
         Assertions.assertEquals(DFPais.valueOfCodigo(8311), DFPais.UCRANIA);
         Assertions.assertEquals(DFPais.valueOfCodigo("8338"), DFPais.UGANDA);
         Assertions.assertEquals(DFPais.valueOfCodigo(8338), DFPais.UGANDA);
         Assertions.assertEquals(DFPais.valueOfCodigo("8451"), DFPais.URUGUAI);
         Assertions.assertEquals(DFPais.valueOfCodigo(8451), DFPais.URUGUAI);
         Assertions.assertEquals(DFPais.valueOfCodigo("8478"), DFPais.UZBEQUISTAO_REPUBLICA_DO);
         Assertions.assertEquals(DFPais.valueOfCodigo(8478), DFPais.UZBEQUISTAO_REPUBLICA_DO);
         Assertions.assertEquals(DFPais.valueOfCodigo("8486"), DFPais.VATICANO_EST_DA_CIDADE_DO);
         Assertions.assertEquals(DFPais.valueOfCodigo(8486), DFPais.VATICANO_EST_DA_CIDADE_DO);
         Assertions.assertEquals(DFPais.valueOfCodigo("8508"), DFPais.VENEZUELA);
         Assertions.assertEquals(DFPais.valueOfCodigo(8508), DFPais.VENEZUELA);
         Assertions.assertEquals(DFPais.valueOfCodigo("8583"), DFPais.VIETNA);
         Assertions.assertEquals(DFPais.valueOfCodigo(8583), DFPais.VIETNA);
         Assertions.assertEquals(DFPais.valueOfCodigo("8630"), DFPais.VIRGENS_ILHAS_BRITANICAS);
         Assertions.assertEquals(DFPais.valueOfCodigo(8630), DFPais.VIRGENS_ILHAS_BRITANICAS);
         Assertions.assertEquals(DFPais.valueOfCodigo("8664"), DFPais.VIRGENS_ILHAS_E_U_A);
         Assertions.assertEquals(DFPais.valueOfCodigo(8664), DFPais.VIRGENS_ILHAS_E_U_A);
         Assertions.assertEquals(DFPais.valueOfCodigo("8702"), DFPais.FIJI);
         Assertions.assertEquals(DFPais.valueOfCodigo(8702), DFPais.FIJI);
         Assertions.assertEquals(DFPais.valueOfCodigo("8753"), DFPais.WALLIS_E_FUTUNA_ILHAS);
         Assertions.assertEquals(DFPais.valueOfCodigo(8753), DFPais.WALLIS_E_FUTUNA_ILHAS);
         Assertions.assertEquals(DFPais.valueOfCodigo("8737"), DFPais.WAKE_ILHA);
         Assertions.assertEquals(DFPais.valueOfCodigo(8737), DFPais.WAKE_ILHA);
         Assertions.assertEquals(DFPais.valueOfCodigo("8885"), DFPais.CONGO_REPUBLICA_DEMOCRATICA_DO);
         Assertions.assertEquals(DFPais.valueOfCodigo(8885), DFPais.CONGO_REPUBLICA_DEMOCRATICA_DO);
         Assertions.assertEquals(DFPais.valueOfCodigo("8907"), DFPais.ZAMBIA);
         Assertions.assertEquals(DFPais.valueOfCodigo(8907), DFPais.ZAMBIA);

     }

}