
package br.inf.portalfiscal.nfe.wsdl.cadconsultacadastro2.svrs;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b14002
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "CadConsultaCadastro2", targetNamespace = "http://www.portalfiscal.inf.br/nfe/wsdl/CadConsultaCadastro2", wsdlLocation = "https://cad.svrs.rs.gov.br/ws/cadconsultacadastro/cadconsultacadastro2.asmx?WSDL")
public class CadConsultaCadastro2
    extends Service
{

    private final static URL CADCONSULTACADASTRO2_WSDL_LOCATION;
    private final static WebServiceException CADCONSULTACADASTRO2_EXCEPTION;
    private final static QName CADCONSULTACADASTRO2_QNAME = new QName("http://www.portalfiscal.inf.br/nfe/wsdl/CadConsultaCadastro2", "CadConsultaCadastro2");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("https://cad.svrs.rs.gov.br/ws/cadconsultacadastro/cadconsultacadastro2.asmx?WSDL");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        CADCONSULTACADASTRO2_WSDL_LOCATION = url;
        CADCONSULTACADASTRO2_EXCEPTION = e;
    }

    public CadConsultaCadastro2() {
        super(__getWsdlLocation(), CADCONSULTACADASTRO2_QNAME);
    }

    public CadConsultaCadastro2(WebServiceFeature... features) {
        super(__getWsdlLocation(), CADCONSULTACADASTRO2_QNAME, features);
    }

    public CadConsultaCadastro2(URL wsdlLocation) {
        super(wsdlLocation, CADCONSULTACADASTRO2_QNAME);
    }

    public CadConsultaCadastro2(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, CADCONSULTACADASTRO2_QNAME, features);
    }

    public CadConsultaCadastro2(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public CadConsultaCadastro2(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns CadConsultaCadastro2Soap
     */
    @WebEndpoint(name = "CadConsultaCadastro2Soap")
    public CadConsultaCadastro2Soap getCadConsultaCadastro2Soap() {
        return super.getPort(new QName("http://www.portalfiscal.inf.br/nfe/wsdl/CadConsultaCadastro2", "CadConsultaCadastro2Soap"), CadConsultaCadastro2Soap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns CadConsultaCadastro2Soap
     */
    @WebEndpoint(name = "CadConsultaCadastro2Soap")
    public CadConsultaCadastro2Soap getCadConsultaCadastro2Soap(WebServiceFeature... features) {
        return super.getPort(new QName("http://www.portalfiscal.inf.br/nfe/wsdl/CadConsultaCadastro2", "CadConsultaCadastro2Soap"), CadConsultaCadastro2Soap.class, features);
    }

    /**
     * 
     * @return
     *     returns CadConsultaCadastro2Soap
     */
    @WebEndpoint(name = "CadConsultaCadastro2Soap12")
    public CadConsultaCadastro2Soap getCadConsultaCadastro2Soap12() {
        return super.getPort(new QName("http://www.portalfiscal.inf.br/nfe/wsdl/CadConsultaCadastro2", "CadConsultaCadastro2Soap12"), CadConsultaCadastro2Soap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns CadConsultaCadastro2Soap
     */
    @WebEndpoint(name = "CadConsultaCadastro2Soap12")
    public CadConsultaCadastro2Soap getCadConsultaCadastro2Soap12(WebServiceFeature... features) {
        return super.getPort(new QName("http://www.portalfiscal.inf.br/nfe/wsdl/CadConsultaCadastro2", "CadConsultaCadastro2Soap12"), CadConsultaCadastro2Soap.class, features);
    }

    private static URL __getWsdlLocation() {
        if (CADCONSULTACADASTRO2_EXCEPTION!= null) {
            throw CADCONSULTACADASTRO2_EXCEPTION;
        }
        return CADCONSULTACADASTRO2_WSDL_LOCATION;
    }

}
